
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Chat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Chat
 * 
 */
export type ChatModel = runtime.Types.Result.DefaultSelection<Prisma.$ChatPayload>

export type AggregateChat = {
  _count: ChatCountAggregateOutputType | null
  _min: ChatMinAggregateOutputType | null
  _max: ChatMaxAggregateOutputType | null
}

export type ChatMinAggregateOutputType = {
  id: string | null
  clientFullName: string | null
  checkoutDate: string | null
  guestLanguage: string | null
  hotelResponding: boolean | null
  isChatting: boolean | null
  room: string | null
  status: boolean | null
  userId: string | null
  hotelId: string | null
  supportId: string | null
  guestTokenId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChatMaxAggregateOutputType = {
  id: string | null
  clientFullName: string | null
  checkoutDate: string | null
  guestLanguage: string | null
  hotelResponding: boolean | null
  isChatting: boolean | null
  room: string | null
  status: boolean | null
  userId: string | null
  hotelId: string | null
  supportId: string | null
  guestTokenId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChatCountAggregateOutputType = {
  id: number
  clientFullName: number
  checkoutDate: number
  guestLanguage: number
  hotelResponding: number
  isChatting: number
  room: number
  status: number
  userId: number
  hotelId: number
  supportId: number
  guestTokenId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ChatMinAggregateInputType = {
  id?: true
  clientFullName?: true
  checkoutDate?: true
  guestLanguage?: true
  hotelResponding?: true
  isChatting?: true
  room?: true
  status?: true
  userId?: true
  hotelId?: true
  supportId?: true
  guestTokenId?: true
  createdAt?: true
  updatedAt?: true
}

export type ChatMaxAggregateInputType = {
  id?: true
  clientFullName?: true
  checkoutDate?: true
  guestLanguage?: true
  hotelResponding?: true
  isChatting?: true
  room?: true
  status?: true
  userId?: true
  hotelId?: true
  supportId?: true
  guestTokenId?: true
  createdAt?: true
  updatedAt?: true
}

export type ChatCountAggregateInputType = {
  id?: true
  clientFullName?: true
  checkoutDate?: true
  guestLanguage?: true
  hotelResponding?: true
  isChatting?: true
  room?: true
  status?: true
  userId?: true
  hotelId?: true
  supportId?: true
  guestTokenId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ChatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Chat to aggregate.
   */
  where?: Prisma.ChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Chats to fetch.
   */
  orderBy?: Prisma.ChatOrderByWithRelationInput | Prisma.ChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Chats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Chats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Chats
  **/
  _count?: true | ChatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ChatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ChatMaxAggregateInputType
}

export type GetChatAggregateType<T extends ChatAggregateArgs> = {
      [P in keyof T & keyof AggregateChat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateChat[P]>
    : Prisma.GetScalarType<T[P], AggregateChat[P]>
}




export type ChatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChatWhereInput
  orderBy?: Prisma.ChatOrderByWithAggregationInput | Prisma.ChatOrderByWithAggregationInput[]
  by: Prisma.ChatScalarFieldEnum[] | Prisma.ChatScalarFieldEnum
  having?: Prisma.ChatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ChatCountAggregateInputType | true
  _min?: ChatMinAggregateInputType
  _max?: ChatMaxAggregateInputType
}

export type ChatGroupByOutputType = {
  id: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  hotelId: string | null
  supportId: string | null
  guestTokenId: string | null
  createdAt: Date
  updatedAt: Date
  _count: ChatCountAggregateOutputType | null
  _min: ChatMinAggregateOutputType | null
  _max: ChatMaxAggregateOutputType | null
}

export type GetChatGroupByPayload<T extends ChatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ChatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ChatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ChatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ChatGroupByOutputType[P]>
      }
    >
  >



export type ChatWhereInput = {
  AND?: Prisma.ChatWhereInput | Prisma.ChatWhereInput[]
  OR?: Prisma.ChatWhereInput[]
  NOT?: Prisma.ChatWhereInput | Prisma.ChatWhereInput[]
  id?: Prisma.StringFilter<"Chat"> | string
  clientFullName?: Prisma.StringFilter<"Chat"> | string
  checkoutDate?: Prisma.StringFilter<"Chat"> | string
  guestLanguage?: Prisma.StringFilter<"Chat"> | string
  hotelResponding?: Prisma.BoolFilter<"Chat"> | boolean
  isChatting?: Prisma.BoolFilter<"Chat"> | boolean
  room?: Prisma.StringFilter<"Chat"> | string
  status?: Prisma.BoolFilter<"Chat"> | boolean
  userId?: Prisma.StringFilter<"Chat"> | string
  hotelId?: Prisma.StringNullableFilter<"Chat"> | string | null
  supportId?: Prisma.StringNullableFilter<"Chat"> | string | null
  guestTokenId?: Prisma.StringNullableFilter<"Chat"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Chat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Chat"> | Date | string
  hotel?: Prisma.XOR<Prisma.HotelNullableScalarRelationFilter, Prisma.HotelWhereInput> | null
  support?: Prisma.XOR<Prisma.SupportNullableScalarRelationFilter, Prisma.SupportWhereInput> | null
  token?: Prisma.XOR<Prisma.GuestTokenNullableScalarRelationFilter, Prisma.GuestTokenWhereInput> | null
  chatRoom?: Prisma.ChatMessageListRelationFilter
}

export type ChatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  clientFullName?: Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  guestLanguage?: Prisma.SortOrder
  hotelResponding?: Prisma.SortOrder
  isChatting?: Prisma.SortOrder
  room?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  hotelId?: Prisma.SortOrderInput | Prisma.SortOrder
  supportId?: Prisma.SortOrderInput | Prisma.SortOrder
  guestTokenId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  hotel?: Prisma.HotelOrderByWithRelationInput
  support?: Prisma.SupportOrderByWithRelationInput
  token?: Prisma.GuestTokenOrderByWithRelationInput
  chatRoom?: Prisma.ChatMessageOrderByRelationAggregateInput
}

export type ChatWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ChatWhereInput | Prisma.ChatWhereInput[]
  OR?: Prisma.ChatWhereInput[]
  NOT?: Prisma.ChatWhereInput | Prisma.ChatWhereInput[]
  clientFullName?: Prisma.StringFilter<"Chat"> | string
  checkoutDate?: Prisma.StringFilter<"Chat"> | string
  guestLanguage?: Prisma.StringFilter<"Chat"> | string
  hotelResponding?: Prisma.BoolFilter<"Chat"> | boolean
  isChatting?: Prisma.BoolFilter<"Chat"> | boolean
  room?: Prisma.StringFilter<"Chat"> | string
  status?: Prisma.BoolFilter<"Chat"> | boolean
  userId?: Prisma.StringFilter<"Chat"> | string
  hotelId?: Prisma.StringNullableFilter<"Chat"> | string | null
  supportId?: Prisma.StringNullableFilter<"Chat"> | string | null
  guestTokenId?: Prisma.StringNullableFilter<"Chat"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Chat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Chat"> | Date | string
  hotel?: Prisma.XOR<Prisma.HotelNullableScalarRelationFilter, Prisma.HotelWhereInput> | null
  support?: Prisma.XOR<Prisma.SupportNullableScalarRelationFilter, Prisma.SupportWhereInput> | null
  token?: Prisma.XOR<Prisma.GuestTokenNullableScalarRelationFilter, Prisma.GuestTokenWhereInput> | null
  chatRoom?: Prisma.ChatMessageListRelationFilter
}, "id">

export type ChatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  clientFullName?: Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  guestLanguage?: Prisma.SortOrder
  hotelResponding?: Prisma.SortOrder
  isChatting?: Prisma.SortOrder
  room?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  hotelId?: Prisma.SortOrderInput | Prisma.SortOrder
  supportId?: Prisma.SortOrderInput | Prisma.SortOrder
  guestTokenId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ChatCountOrderByAggregateInput
  _max?: Prisma.ChatMaxOrderByAggregateInput
  _min?: Prisma.ChatMinOrderByAggregateInput
}

export type ChatScalarWhereWithAggregatesInput = {
  AND?: Prisma.ChatScalarWhereWithAggregatesInput | Prisma.ChatScalarWhereWithAggregatesInput[]
  OR?: Prisma.ChatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ChatScalarWhereWithAggregatesInput | Prisma.ChatScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Chat"> | string
  clientFullName?: Prisma.StringWithAggregatesFilter<"Chat"> | string
  checkoutDate?: Prisma.StringWithAggregatesFilter<"Chat"> | string
  guestLanguage?: Prisma.StringWithAggregatesFilter<"Chat"> | string
  hotelResponding?: Prisma.BoolWithAggregatesFilter<"Chat"> | boolean
  isChatting?: Prisma.BoolWithAggregatesFilter<"Chat"> | boolean
  room?: Prisma.StringWithAggregatesFilter<"Chat"> | string
  status?: Prisma.BoolWithAggregatesFilter<"Chat"> | boolean
  userId?: Prisma.StringWithAggregatesFilter<"Chat"> | string
  hotelId?: Prisma.StringNullableWithAggregatesFilter<"Chat"> | string | null
  supportId?: Prisma.StringNullableWithAggregatesFilter<"Chat"> | string | null
  guestTokenId?: Prisma.StringNullableWithAggregatesFilter<"Chat"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Chat"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Chat"> | Date | string
}

export type ChatCreateInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  createdAt: Date | string
  updatedAt: Date | string
  hotel?: Prisma.HotelCreateNestedOneWithoutChatRoomInput
  support?: Prisma.SupportCreateNestedOneWithoutChatRoomInput
  token?: Prisma.GuestTokenCreateNestedOneWithoutChatsInput
  chatRoom?: Prisma.ChatMessageCreateNestedManyWithoutChatInput
}

export type ChatUncheckedCreateInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  hotelId?: string | null
  supportId?: string | null
  guestTokenId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
  chatRoom?: Prisma.ChatMessageUncheckedCreateNestedManyWithoutChatInput
}

export type ChatUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotel?: Prisma.HotelUpdateOneWithoutChatRoomNestedInput
  support?: Prisma.SupportUpdateOneWithoutChatRoomNestedInput
  token?: Prisma.GuestTokenUpdateOneWithoutChatsNestedInput
  chatRoom?: Prisma.ChatMessageUpdateManyWithoutChatNestedInput
}

export type ChatUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  supportId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatRoom?: Prisma.ChatMessageUncheckedUpdateManyWithoutChatNestedInput
}

export type ChatCreateManyInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  hotelId?: string | null
  supportId?: string | null
  guestTokenId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type ChatUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChatUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  supportId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChatListRelationFilter = {
  every?: Prisma.ChatWhereInput
  some?: Prisma.ChatWhereInput
  none?: Prisma.ChatWhereInput
}

export type ChatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ChatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clientFullName?: Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  guestLanguage?: Prisma.SortOrder
  hotelResponding?: Prisma.SortOrder
  isChatting?: Prisma.SortOrder
  room?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  supportId?: Prisma.SortOrder
  guestTokenId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clientFullName?: Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  guestLanguage?: Prisma.SortOrder
  hotelResponding?: Prisma.SortOrder
  isChatting?: Prisma.SortOrder
  room?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  supportId?: Prisma.SortOrder
  guestTokenId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clientFullName?: Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  guestLanguage?: Prisma.SortOrder
  hotelResponding?: Prisma.SortOrder
  isChatting?: Prisma.SortOrder
  room?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  supportId?: Prisma.SortOrder
  guestTokenId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChatScalarRelationFilter = {
  is?: Prisma.ChatWhereInput
  isNot?: Prisma.ChatWhereInput
}

export type ChatCreateNestedManyWithoutHotelInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutHotelInput, Prisma.ChatUncheckedCreateWithoutHotelInput> | Prisma.ChatCreateWithoutHotelInput[] | Prisma.ChatUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutHotelInput | Prisma.ChatCreateOrConnectWithoutHotelInput[]
  createMany?: Prisma.ChatCreateManyHotelInputEnvelope
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
}

export type ChatUncheckedCreateNestedManyWithoutHotelInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutHotelInput, Prisma.ChatUncheckedCreateWithoutHotelInput> | Prisma.ChatCreateWithoutHotelInput[] | Prisma.ChatUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutHotelInput | Prisma.ChatCreateOrConnectWithoutHotelInput[]
  createMany?: Prisma.ChatCreateManyHotelInputEnvelope
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
}

export type ChatUpdateManyWithoutHotelNestedInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutHotelInput, Prisma.ChatUncheckedCreateWithoutHotelInput> | Prisma.ChatCreateWithoutHotelInput[] | Prisma.ChatUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutHotelInput | Prisma.ChatCreateOrConnectWithoutHotelInput[]
  upsert?: Prisma.ChatUpsertWithWhereUniqueWithoutHotelInput | Prisma.ChatUpsertWithWhereUniqueWithoutHotelInput[]
  createMany?: Prisma.ChatCreateManyHotelInputEnvelope
  set?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  disconnect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  delete?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  update?: Prisma.ChatUpdateWithWhereUniqueWithoutHotelInput | Prisma.ChatUpdateWithWhereUniqueWithoutHotelInput[]
  updateMany?: Prisma.ChatUpdateManyWithWhereWithoutHotelInput | Prisma.ChatUpdateManyWithWhereWithoutHotelInput[]
  deleteMany?: Prisma.ChatScalarWhereInput | Prisma.ChatScalarWhereInput[]
}

export type ChatUncheckedUpdateManyWithoutHotelNestedInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutHotelInput, Prisma.ChatUncheckedCreateWithoutHotelInput> | Prisma.ChatCreateWithoutHotelInput[] | Prisma.ChatUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutHotelInput | Prisma.ChatCreateOrConnectWithoutHotelInput[]
  upsert?: Prisma.ChatUpsertWithWhereUniqueWithoutHotelInput | Prisma.ChatUpsertWithWhereUniqueWithoutHotelInput[]
  createMany?: Prisma.ChatCreateManyHotelInputEnvelope
  set?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  disconnect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  delete?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  update?: Prisma.ChatUpdateWithWhereUniqueWithoutHotelInput | Prisma.ChatUpdateWithWhereUniqueWithoutHotelInput[]
  updateMany?: Prisma.ChatUpdateManyWithWhereWithoutHotelInput | Prisma.ChatUpdateManyWithWhereWithoutHotelInput[]
  deleteMany?: Prisma.ChatScalarWhereInput | Prisma.ChatScalarWhereInput[]
}

export type ChatCreateNestedManyWithoutTokenInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutTokenInput, Prisma.ChatUncheckedCreateWithoutTokenInput> | Prisma.ChatCreateWithoutTokenInput[] | Prisma.ChatUncheckedCreateWithoutTokenInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutTokenInput | Prisma.ChatCreateOrConnectWithoutTokenInput[]
  createMany?: Prisma.ChatCreateManyTokenInputEnvelope
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
}

export type ChatUncheckedCreateNestedManyWithoutTokenInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutTokenInput, Prisma.ChatUncheckedCreateWithoutTokenInput> | Prisma.ChatCreateWithoutTokenInput[] | Prisma.ChatUncheckedCreateWithoutTokenInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutTokenInput | Prisma.ChatCreateOrConnectWithoutTokenInput[]
  createMany?: Prisma.ChatCreateManyTokenInputEnvelope
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
}

export type ChatUpdateManyWithoutTokenNestedInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutTokenInput, Prisma.ChatUncheckedCreateWithoutTokenInput> | Prisma.ChatCreateWithoutTokenInput[] | Prisma.ChatUncheckedCreateWithoutTokenInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutTokenInput | Prisma.ChatCreateOrConnectWithoutTokenInput[]
  upsert?: Prisma.ChatUpsertWithWhereUniqueWithoutTokenInput | Prisma.ChatUpsertWithWhereUniqueWithoutTokenInput[]
  createMany?: Prisma.ChatCreateManyTokenInputEnvelope
  set?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  disconnect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  delete?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  update?: Prisma.ChatUpdateWithWhereUniqueWithoutTokenInput | Prisma.ChatUpdateWithWhereUniqueWithoutTokenInput[]
  updateMany?: Prisma.ChatUpdateManyWithWhereWithoutTokenInput | Prisma.ChatUpdateManyWithWhereWithoutTokenInput[]
  deleteMany?: Prisma.ChatScalarWhereInput | Prisma.ChatScalarWhereInput[]
}

export type ChatUncheckedUpdateManyWithoutTokenNestedInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutTokenInput, Prisma.ChatUncheckedCreateWithoutTokenInput> | Prisma.ChatCreateWithoutTokenInput[] | Prisma.ChatUncheckedCreateWithoutTokenInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutTokenInput | Prisma.ChatCreateOrConnectWithoutTokenInput[]
  upsert?: Prisma.ChatUpsertWithWhereUniqueWithoutTokenInput | Prisma.ChatUpsertWithWhereUniqueWithoutTokenInput[]
  createMany?: Prisma.ChatCreateManyTokenInputEnvelope
  set?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  disconnect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  delete?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  update?: Prisma.ChatUpdateWithWhereUniqueWithoutTokenInput | Prisma.ChatUpdateWithWhereUniqueWithoutTokenInput[]
  updateMany?: Prisma.ChatUpdateManyWithWhereWithoutTokenInput | Prisma.ChatUpdateManyWithWhereWithoutTokenInput[]
  deleteMany?: Prisma.ChatScalarWhereInput | Prisma.ChatScalarWhereInput[]
}

export type ChatCreateNestedManyWithoutSupportInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutSupportInput, Prisma.ChatUncheckedCreateWithoutSupportInput> | Prisma.ChatCreateWithoutSupportInput[] | Prisma.ChatUncheckedCreateWithoutSupportInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutSupportInput | Prisma.ChatCreateOrConnectWithoutSupportInput[]
  createMany?: Prisma.ChatCreateManySupportInputEnvelope
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
}

export type ChatUncheckedCreateNestedManyWithoutSupportInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutSupportInput, Prisma.ChatUncheckedCreateWithoutSupportInput> | Prisma.ChatCreateWithoutSupportInput[] | Prisma.ChatUncheckedCreateWithoutSupportInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutSupportInput | Prisma.ChatCreateOrConnectWithoutSupportInput[]
  createMany?: Prisma.ChatCreateManySupportInputEnvelope
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
}

export type ChatUpdateManyWithoutSupportNestedInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutSupportInput, Prisma.ChatUncheckedCreateWithoutSupportInput> | Prisma.ChatCreateWithoutSupportInput[] | Prisma.ChatUncheckedCreateWithoutSupportInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutSupportInput | Prisma.ChatCreateOrConnectWithoutSupportInput[]
  upsert?: Prisma.ChatUpsertWithWhereUniqueWithoutSupportInput | Prisma.ChatUpsertWithWhereUniqueWithoutSupportInput[]
  createMany?: Prisma.ChatCreateManySupportInputEnvelope
  set?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  disconnect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  delete?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  update?: Prisma.ChatUpdateWithWhereUniqueWithoutSupportInput | Prisma.ChatUpdateWithWhereUniqueWithoutSupportInput[]
  updateMany?: Prisma.ChatUpdateManyWithWhereWithoutSupportInput | Prisma.ChatUpdateManyWithWhereWithoutSupportInput[]
  deleteMany?: Prisma.ChatScalarWhereInput | Prisma.ChatScalarWhereInput[]
}

export type ChatUncheckedUpdateManyWithoutSupportNestedInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutSupportInput, Prisma.ChatUncheckedCreateWithoutSupportInput> | Prisma.ChatCreateWithoutSupportInput[] | Prisma.ChatUncheckedCreateWithoutSupportInput[]
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutSupportInput | Prisma.ChatCreateOrConnectWithoutSupportInput[]
  upsert?: Prisma.ChatUpsertWithWhereUniqueWithoutSupportInput | Prisma.ChatUpsertWithWhereUniqueWithoutSupportInput[]
  createMany?: Prisma.ChatCreateManySupportInputEnvelope
  set?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  disconnect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  delete?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  connect?: Prisma.ChatWhereUniqueInput | Prisma.ChatWhereUniqueInput[]
  update?: Prisma.ChatUpdateWithWhereUniqueWithoutSupportInput | Prisma.ChatUpdateWithWhereUniqueWithoutSupportInput[]
  updateMany?: Prisma.ChatUpdateManyWithWhereWithoutSupportInput | Prisma.ChatUpdateManyWithWhereWithoutSupportInput[]
  deleteMany?: Prisma.ChatScalarWhereInput | Prisma.ChatScalarWhereInput[]
}

export type ChatCreateNestedOneWithoutChatRoomInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutChatRoomInput, Prisma.ChatUncheckedCreateWithoutChatRoomInput>
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutChatRoomInput
  connect?: Prisma.ChatWhereUniqueInput
}

export type ChatUpdateOneRequiredWithoutChatRoomNestedInput = {
  create?: Prisma.XOR<Prisma.ChatCreateWithoutChatRoomInput, Prisma.ChatUncheckedCreateWithoutChatRoomInput>
  connectOrCreate?: Prisma.ChatCreateOrConnectWithoutChatRoomInput
  upsert?: Prisma.ChatUpsertWithoutChatRoomInput
  connect?: Prisma.ChatWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ChatUpdateToOneWithWhereWithoutChatRoomInput, Prisma.ChatUpdateWithoutChatRoomInput>, Prisma.ChatUncheckedUpdateWithoutChatRoomInput>
}

export type ChatCreateWithoutHotelInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  createdAt: Date | string
  updatedAt: Date | string
  support?: Prisma.SupportCreateNestedOneWithoutChatRoomInput
  token?: Prisma.GuestTokenCreateNestedOneWithoutChatsInput
  chatRoom?: Prisma.ChatMessageCreateNestedManyWithoutChatInput
}

export type ChatUncheckedCreateWithoutHotelInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  supportId?: string | null
  guestTokenId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
  chatRoom?: Prisma.ChatMessageUncheckedCreateNestedManyWithoutChatInput
}

export type ChatCreateOrConnectWithoutHotelInput = {
  where: Prisma.ChatWhereUniqueInput
  create: Prisma.XOR<Prisma.ChatCreateWithoutHotelInput, Prisma.ChatUncheckedCreateWithoutHotelInput>
}

export type ChatCreateManyHotelInputEnvelope = {
  data: Prisma.ChatCreateManyHotelInput | Prisma.ChatCreateManyHotelInput[]
  skipDuplicates?: boolean
}

export type ChatUpsertWithWhereUniqueWithoutHotelInput = {
  where: Prisma.ChatWhereUniqueInput
  update: Prisma.XOR<Prisma.ChatUpdateWithoutHotelInput, Prisma.ChatUncheckedUpdateWithoutHotelInput>
  create: Prisma.XOR<Prisma.ChatCreateWithoutHotelInput, Prisma.ChatUncheckedCreateWithoutHotelInput>
}

export type ChatUpdateWithWhereUniqueWithoutHotelInput = {
  where: Prisma.ChatWhereUniqueInput
  data: Prisma.XOR<Prisma.ChatUpdateWithoutHotelInput, Prisma.ChatUncheckedUpdateWithoutHotelInput>
}

export type ChatUpdateManyWithWhereWithoutHotelInput = {
  where: Prisma.ChatScalarWhereInput
  data: Prisma.XOR<Prisma.ChatUpdateManyMutationInput, Prisma.ChatUncheckedUpdateManyWithoutHotelInput>
}

export type ChatScalarWhereInput = {
  AND?: Prisma.ChatScalarWhereInput | Prisma.ChatScalarWhereInput[]
  OR?: Prisma.ChatScalarWhereInput[]
  NOT?: Prisma.ChatScalarWhereInput | Prisma.ChatScalarWhereInput[]
  id?: Prisma.StringFilter<"Chat"> | string
  clientFullName?: Prisma.StringFilter<"Chat"> | string
  checkoutDate?: Prisma.StringFilter<"Chat"> | string
  guestLanguage?: Prisma.StringFilter<"Chat"> | string
  hotelResponding?: Prisma.BoolFilter<"Chat"> | boolean
  isChatting?: Prisma.BoolFilter<"Chat"> | boolean
  room?: Prisma.StringFilter<"Chat"> | string
  status?: Prisma.BoolFilter<"Chat"> | boolean
  userId?: Prisma.StringFilter<"Chat"> | string
  hotelId?: Prisma.StringNullableFilter<"Chat"> | string | null
  supportId?: Prisma.StringNullableFilter<"Chat"> | string | null
  guestTokenId?: Prisma.StringNullableFilter<"Chat"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Chat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Chat"> | Date | string
}

export type ChatCreateWithoutTokenInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  createdAt: Date | string
  updatedAt: Date | string
  hotel?: Prisma.HotelCreateNestedOneWithoutChatRoomInput
  support?: Prisma.SupportCreateNestedOneWithoutChatRoomInput
  chatRoom?: Prisma.ChatMessageCreateNestedManyWithoutChatInput
}

export type ChatUncheckedCreateWithoutTokenInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  hotelId?: string | null
  supportId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
  chatRoom?: Prisma.ChatMessageUncheckedCreateNestedManyWithoutChatInput
}

export type ChatCreateOrConnectWithoutTokenInput = {
  where: Prisma.ChatWhereUniqueInput
  create: Prisma.XOR<Prisma.ChatCreateWithoutTokenInput, Prisma.ChatUncheckedCreateWithoutTokenInput>
}

export type ChatCreateManyTokenInputEnvelope = {
  data: Prisma.ChatCreateManyTokenInput | Prisma.ChatCreateManyTokenInput[]
  skipDuplicates?: boolean
}

export type ChatUpsertWithWhereUniqueWithoutTokenInput = {
  where: Prisma.ChatWhereUniqueInput
  update: Prisma.XOR<Prisma.ChatUpdateWithoutTokenInput, Prisma.ChatUncheckedUpdateWithoutTokenInput>
  create: Prisma.XOR<Prisma.ChatCreateWithoutTokenInput, Prisma.ChatUncheckedCreateWithoutTokenInput>
}

export type ChatUpdateWithWhereUniqueWithoutTokenInput = {
  where: Prisma.ChatWhereUniqueInput
  data: Prisma.XOR<Prisma.ChatUpdateWithoutTokenInput, Prisma.ChatUncheckedUpdateWithoutTokenInput>
}

export type ChatUpdateManyWithWhereWithoutTokenInput = {
  where: Prisma.ChatScalarWhereInput
  data: Prisma.XOR<Prisma.ChatUpdateManyMutationInput, Prisma.ChatUncheckedUpdateManyWithoutTokenInput>
}

export type ChatCreateWithoutSupportInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  createdAt: Date | string
  updatedAt: Date | string
  hotel?: Prisma.HotelCreateNestedOneWithoutChatRoomInput
  token?: Prisma.GuestTokenCreateNestedOneWithoutChatsInput
  chatRoom?: Prisma.ChatMessageCreateNestedManyWithoutChatInput
}

export type ChatUncheckedCreateWithoutSupportInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  hotelId?: string | null
  guestTokenId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
  chatRoom?: Prisma.ChatMessageUncheckedCreateNestedManyWithoutChatInput
}

export type ChatCreateOrConnectWithoutSupportInput = {
  where: Prisma.ChatWhereUniqueInput
  create: Prisma.XOR<Prisma.ChatCreateWithoutSupportInput, Prisma.ChatUncheckedCreateWithoutSupportInput>
}

export type ChatCreateManySupportInputEnvelope = {
  data: Prisma.ChatCreateManySupportInput | Prisma.ChatCreateManySupportInput[]
  skipDuplicates?: boolean
}

export type ChatUpsertWithWhereUniqueWithoutSupportInput = {
  where: Prisma.ChatWhereUniqueInput
  update: Prisma.XOR<Prisma.ChatUpdateWithoutSupportInput, Prisma.ChatUncheckedUpdateWithoutSupportInput>
  create: Prisma.XOR<Prisma.ChatCreateWithoutSupportInput, Prisma.ChatUncheckedCreateWithoutSupportInput>
}

export type ChatUpdateWithWhereUniqueWithoutSupportInput = {
  where: Prisma.ChatWhereUniqueInput
  data: Prisma.XOR<Prisma.ChatUpdateWithoutSupportInput, Prisma.ChatUncheckedUpdateWithoutSupportInput>
}

export type ChatUpdateManyWithWhereWithoutSupportInput = {
  where: Prisma.ChatScalarWhereInput
  data: Prisma.XOR<Prisma.ChatUpdateManyMutationInput, Prisma.ChatUncheckedUpdateManyWithoutSupportInput>
}

export type ChatCreateWithoutChatRoomInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  createdAt: Date | string
  updatedAt: Date | string
  hotel?: Prisma.HotelCreateNestedOneWithoutChatRoomInput
  support?: Prisma.SupportCreateNestedOneWithoutChatRoomInput
  token?: Prisma.GuestTokenCreateNestedOneWithoutChatsInput
}

export type ChatUncheckedCreateWithoutChatRoomInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  hotelId?: string | null
  supportId?: string | null
  guestTokenId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type ChatCreateOrConnectWithoutChatRoomInput = {
  where: Prisma.ChatWhereUniqueInput
  create: Prisma.XOR<Prisma.ChatCreateWithoutChatRoomInput, Prisma.ChatUncheckedCreateWithoutChatRoomInput>
}

export type ChatUpsertWithoutChatRoomInput = {
  update: Prisma.XOR<Prisma.ChatUpdateWithoutChatRoomInput, Prisma.ChatUncheckedUpdateWithoutChatRoomInput>
  create: Prisma.XOR<Prisma.ChatCreateWithoutChatRoomInput, Prisma.ChatUncheckedCreateWithoutChatRoomInput>
  where?: Prisma.ChatWhereInput
}

export type ChatUpdateToOneWithWhereWithoutChatRoomInput = {
  where?: Prisma.ChatWhereInput
  data: Prisma.XOR<Prisma.ChatUpdateWithoutChatRoomInput, Prisma.ChatUncheckedUpdateWithoutChatRoomInput>
}

export type ChatUpdateWithoutChatRoomInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotel?: Prisma.HotelUpdateOneWithoutChatRoomNestedInput
  support?: Prisma.SupportUpdateOneWithoutChatRoomNestedInput
  token?: Prisma.GuestTokenUpdateOneWithoutChatsNestedInput
}

export type ChatUncheckedUpdateWithoutChatRoomInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  supportId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChatCreateManyHotelInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  supportId?: string | null
  guestTokenId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type ChatUpdateWithoutHotelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  support?: Prisma.SupportUpdateOneWithoutChatRoomNestedInput
  token?: Prisma.GuestTokenUpdateOneWithoutChatsNestedInput
  chatRoom?: Prisma.ChatMessageUpdateManyWithoutChatNestedInput
}

export type ChatUncheckedUpdateWithoutHotelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  supportId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatRoom?: Prisma.ChatMessageUncheckedUpdateManyWithoutChatNestedInput
}

export type ChatUncheckedUpdateManyWithoutHotelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  supportId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChatCreateManyTokenInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  hotelId?: string | null
  supportId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type ChatUpdateWithoutTokenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotel?: Prisma.HotelUpdateOneWithoutChatRoomNestedInput
  support?: Prisma.SupportUpdateOneWithoutChatRoomNestedInput
  chatRoom?: Prisma.ChatMessageUpdateManyWithoutChatNestedInput
}

export type ChatUncheckedUpdateWithoutTokenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  supportId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatRoom?: Prisma.ChatMessageUncheckedUpdateManyWithoutChatNestedInput
}

export type ChatUncheckedUpdateManyWithoutTokenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  supportId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChatCreateManySupportInput = {
  id?: string
  clientFullName: string
  checkoutDate: string
  guestLanguage: string
  hotelResponding: boolean
  isChatting: boolean
  room: string
  status: boolean
  userId: string
  hotelId?: string | null
  guestTokenId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type ChatUpdateWithoutSupportInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotel?: Prisma.HotelUpdateOneWithoutChatRoomNestedInput
  token?: Prisma.GuestTokenUpdateOneWithoutChatsNestedInput
  chatRoom?: Prisma.ChatMessageUpdateManyWithoutChatNestedInput
}

export type ChatUncheckedUpdateWithoutSupportInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatRoom?: Prisma.ChatMessageUncheckedUpdateManyWithoutChatNestedInput
}

export type ChatUncheckedUpdateManyWithoutSupportInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientFullName?: Prisma.StringFieldUpdateOperationsInput | string
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  guestLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  hotelResponding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  room?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ChatCountOutputType
 */

export type ChatCountOutputType = {
  chatRoom: number
}

export type ChatCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chatRoom?: boolean | ChatCountOutputTypeCountChatRoomArgs
}

/**
 * ChatCountOutputType without action
 */
export type ChatCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatCountOutputType
   */
  select?: Prisma.ChatCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ChatCountOutputType without action
 */
export type ChatCountOutputTypeCountChatRoomArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChatMessageWhereInput
}


export type ChatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clientFullName?: boolean
  checkoutDate?: boolean
  guestLanguage?: boolean
  hotelResponding?: boolean
  isChatting?: boolean
  room?: boolean
  status?: boolean
  userId?: boolean
  hotelId?: boolean
  supportId?: boolean
  guestTokenId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hotel?: boolean | Prisma.Chat$hotelArgs<ExtArgs>
  support?: boolean | Prisma.Chat$supportArgs<ExtArgs>
  token?: boolean | Prisma.Chat$tokenArgs<ExtArgs>
  chatRoom?: boolean | Prisma.Chat$chatRoomArgs<ExtArgs>
  _count?: boolean | Prisma.ChatCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["chat"]>

export type ChatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clientFullName?: boolean
  checkoutDate?: boolean
  guestLanguage?: boolean
  hotelResponding?: boolean
  isChatting?: boolean
  room?: boolean
  status?: boolean
  userId?: boolean
  hotelId?: boolean
  supportId?: boolean
  guestTokenId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hotel?: boolean | Prisma.Chat$hotelArgs<ExtArgs>
  support?: boolean | Prisma.Chat$supportArgs<ExtArgs>
  token?: boolean | Prisma.Chat$tokenArgs<ExtArgs>
}, ExtArgs["result"]["chat"]>

export type ChatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clientFullName?: boolean
  checkoutDate?: boolean
  guestLanguage?: boolean
  hotelResponding?: boolean
  isChatting?: boolean
  room?: boolean
  status?: boolean
  userId?: boolean
  hotelId?: boolean
  supportId?: boolean
  guestTokenId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hotel?: boolean | Prisma.Chat$hotelArgs<ExtArgs>
  support?: boolean | Prisma.Chat$supportArgs<ExtArgs>
  token?: boolean | Prisma.Chat$tokenArgs<ExtArgs>
}, ExtArgs["result"]["chat"]>

export type ChatSelectScalar = {
  id?: boolean
  clientFullName?: boolean
  checkoutDate?: boolean
  guestLanguage?: boolean
  hotelResponding?: boolean
  isChatting?: boolean
  room?: boolean
  status?: boolean
  userId?: boolean
  hotelId?: boolean
  supportId?: boolean
  guestTokenId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ChatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "clientFullName" | "checkoutDate" | "guestLanguage" | "hotelResponding" | "isChatting" | "room" | "status" | "userId" | "hotelId" | "supportId" | "guestTokenId" | "createdAt" | "updatedAt", ExtArgs["result"]["chat"]>
export type ChatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hotel?: boolean | Prisma.Chat$hotelArgs<ExtArgs>
  support?: boolean | Prisma.Chat$supportArgs<ExtArgs>
  token?: boolean | Prisma.Chat$tokenArgs<ExtArgs>
  chatRoom?: boolean | Prisma.Chat$chatRoomArgs<ExtArgs>
  _count?: boolean | Prisma.ChatCountOutputTypeDefaultArgs<ExtArgs>
}
export type ChatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hotel?: boolean | Prisma.Chat$hotelArgs<ExtArgs>
  support?: boolean | Prisma.Chat$supportArgs<ExtArgs>
  token?: boolean | Prisma.Chat$tokenArgs<ExtArgs>
}
export type ChatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hotel?: boolean | Prisma.Chat$hotelArgs<ExtArgs>
  support?: boolean | Prisma.Chat$supportArgs<ExtArgs>
  token?: boolean | Prisma.Chat$tokenArgs<ExtArgs>
}

export type $ChatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Chat"
  objects: {
    hotel: Prisma.$HotelPayload<ExtArgs> | null
    support: Prisma.$SupportPayload<ExtArgs> | null
    token: Prisma.$GuestTokenPayload<ExtArgs> | null
    chatRoom: Prisma.$ChatMessagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    clientFullName: string
    checkoutDate: string
    guestLanguage: string
    hotelResponding: boolean
    isChatting: boolean
    room: string
    status: boolean
    userId: string
    hotelId: string | null
    supportId: string | null
    guestTokenId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["chat"]>
  composites: {}
}

export type ChatGetPayload<S extends boolean | null | undefined | ChatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChatPayload, S>

export type ChatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ChatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ChatCountAggregateInputType | true
  }

export interface ChatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Chat'], meta: { name: 'Chat' } }
  /**
   * Find zero or one Chat that matches the filter.
   * @param {ChatFindUniqueArgs} args - Arguments to find a Chat
   * @example
   * // Get one Chat
   * const chat = await prisma.chat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ChatFindUniqueArgs>(args: Prisma.SelectSubset<T, ChatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Chat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ChatFindUniqueOrThrowArgs} args - Arguments to find a Chat
   * @example
   * // Get one Chat
   * const chat = await prisma.chat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ChatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ChatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Chat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatFindFirstArgs} args - Arguments to find a Chat
   * @example
   * // Get one Chat
   * const chat = await prisma.chat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ChatFindFirstArgs>(args?: Prisma.SelectSubset<T, ChatFindFirstArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Chat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatFindFirstOrThrowArgs} args - Arguments to find a Chat
   * @example
   * // Get one Chat
   * const chat = await prisma.chat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ChatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ChatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Chats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Chats
   * const chats = await prisma.chat.findMany()
   * 
   * // Get first 10 Chats
   * const chats = await prisma.chat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const chatWithIdOnly = await prisma.chat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ChatFindManyArgs>(args?: Prisma.SelectSubset<T, ChatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Chat.
   * @param {ChatCreateArgs} args - Arguments to create a Chat.
   * @example
   * // Create one Chat
   * const Chat = await prisma.chat.create({
   *   data: {
   *     // ... data to create a Chat
   *   }
   * })
   * 
   */
  create<T extends ChatCreateArgs>(args: Prisma.SelectSubset<T, ChatCreateArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Chats.
   * @param {ChatCreateManyArgs} args - Arguments to create many Chats.
   * @example
   * // Create many Chats
   * const chat = await prisma.chat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ChatCreateManyArgs>(args?: Prisma.SelectSubset<T, ChatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Chats and returns the data saved in the database.
   * @param {ChatCreateManyAndReturnArgs} args - Arguments to create many Chats.
   * @example
   * // Create many Chats
   * const chat = await prisma.chat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Chats and only return the `id`
   * const chatWithIdOnly = await prisma.chat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ChatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ChatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Chat.
   * @param {ChatDeleteArgs} args - Arguments to delete one Chat.
   * @example
   * // Delete one Chat
   * const Chat = await prisma.chat.delete({
   *   where: {
   *     // ... filter to delete one Chat
   *   }
   * })
   * 
   */
  delete<T extends ChatDeleteArgs>(args: Prisma.SelectSubset<T, ChatDeleteArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Chat.
   * @param {ChatUpdateArgs} args - Arguments to update one Chat.
   * @example
   * // Update one Chat
   * const chat = await prisma.chat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ChatUpdateArgs>(args: Prisma.SelectSubset<T, ChatUpdateArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Chats.
   * @param {ChatDeleteManyArgs} args - Arguments to filter Chats to delete.
   * @example
   * // Delete a few Chats
   * const { count } = await prisma.chat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ChatDeleteManyArgs>(args?: Prisma.SelectSubset<T, ChatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Chats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Chats
   * const chat = await prisma.chat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ChatUpdateManyArgs>(args: Prisma.SelectSubset<T, ChatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Chats and returns the data updated in the database.
   * @param {ChatUpdateManyAndReturnArgs} args - Arguments to update many Chats.
   * @example
   * // Update many Chats
   * const chat = await prisma.chat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Chats and only return the `id`
   * const chatWithIdOnly = await prisma.chat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ChatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ChatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Chat.
   * @param {ChatUpsertArgs} args - Arguments to update or create a Chat.
   * @example
   * // Update or create a Chat
   * const chat = await prisma.chat.upsert({
   *   create: {
   *     // ... data to create a Chat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Chat we want to update
   *   }
   * })
   */
  upsert<T extends ChatUpsertArgs>(args: Prisma.SelectSubset<T, ChatUpsertArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Chats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatCountArgs} args - Arguments to filter Chats to count.
   * @example
   * // Count the number of Chats
   * const count = await prisma.chat.count({
   *   where: {
   *     // ... the filter for the Chats we want to count
   *   }
   * })
  **/
  count<T extends ChatCountArgs>(
    args?: Prisma.Subset<T, ChatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ChatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Chat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ChatAggregateArgs>(args: Prisma.Subset<T, ChatAggregateArgs>): Prisma.PrismaPromise<GetChatAggregateType<T>>

  /**
   * Group by Chat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ChatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ChatGroupByArgs['orderBy'] }
      : { orderBy?: ChatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ChatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetChatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Chat model
 */
readonly fields: ChatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Chat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ChatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  hotel<T extends Prisma.Chat$hotelArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Chat$hotelArgs<ExtArgs>>): Prisma.Prisma__HotelClient<runtime.Types.Result.GetResult<Prisma.$HotelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  support<T extends Prisma.Chat$supportArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Chat$supportArgs<ExtArgs>>): Prisma.Prisma__SupportClient<runtime.Types.Result.GetResult<Prisma.$SupportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  token<T extends Prisma.Chat$tokenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Chat$tokenArgs<ExtArgs>>): Prisma.Prisma__GuestTokenClient<runtime.Types.Result.GetResult<Prisma.$GuestTokenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  chatRoom<T extends Prisma.Chat$chatRoomArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Chat$chatRoomArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Chat model
 */
export interface ChatFieldRefs {
  readonly id: Prisma.FieldRef<"Chat", 'String'>
  readonly clientFullName: Prisma.FieldRef<"Chat", 'String'>
  readonly checkoutDate: Prisma.FieldRef<"Chat", 'String'>
  readonly guestLanguage: Prisma.FieldRef<"Chat", 'String'>
  readonly hotelResponding: Prisma.FieldRef<"Chat", 'Boolean'>
  readonly isChatting: Prisma.FieldRef<"Chat", 'Boolean'>
  readonly room: Prisma.FieldRef<"Chat", 'String'>
  readonly status: Prisma.FieldRef<"Chat", 'Boolean'>
  readonly userId: Prisma.FieldRef<"Chat", 'String'>
  readonly hotelId: Prisma.FieldRef<"Chat", 'String'>
  readonly supportId: Prisma.FieldRef<"Chat", 'String'>
  readonly guestTokenId: Prisma.FieldRef<"Chat", 'String'>
  readonly createdAt: Prisma.FieldRef<"Chat", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Chat", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Chat findUnique
 */
export type ChatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
  /**
   * Filter, which Chat to fetch.
   */
  where: Prisma.ChatWhereUniqueInput
}

/**
 * Chat findUniqueOrThrow
 */
export type ChatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
  /**
   * Filter, which Chat to fetch.
   */
  where: Prisma.ChatWhereUniqueInput
}

/**
 * Chat findFirst
 */
export type ChatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
  /**
   * Filter, which Chat to fetch.
   */
  where?: Prisma.ChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Chats to fetch.
   */
  orderBy?: Prisma.ChatOrderByWithRelationInput | Prisma.ChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Chats.
   */
  cursor?: Prisma.ChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Chats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Chats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Chats.
   */
  distinct?: Prisma.ChatScalarFieldEnum | Prisma.ChatScalarFieldEnum[]
}

/**
 * Chat findFirstOrThrow
 */
export type ChatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
  /**
   * Filter, which Chat to fetch.
   */
  where?: Prisma.ChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Chats to fetch.
   */
  orderBy?: Prisma.ChatOrderByWithRelationInput | Prisma.ChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Chats.
   */
  cursor?: Prisma.ChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Chats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Chats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Chats.
   */
  distinct?: Prisma.ChatScalarFieldEnum | Prisma.ChatScalarFieldEnum[]
}

/**
 * Chat findMany
 */
export type ChatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
  /**
   * Filter, which Chats to fetch.
   */
  where?: Prisma.ChatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Chats to fetch.
   */
  orderBy?: Prisma.ChatOrderByWithRelationInput | Prisma.ChatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Chats.
   */
  cursor?: Prisma.ChatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Chats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Chats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Chats.
   */
  distinct?: Prisma.ChatScalarFieldEnum | Prisma.ChatScalarFieldEnum[]
}

/**
 * Chat create
 */
export type ChatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
  /**
   * The data needed to create a Chat.
   */
  data: Prisma.XOR<Prisma.ChatCreateInput, Prisma.ChatUncheckedCreateInput>
}

/**
 * Chat createMany
 */
export type ChatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Chats.
   */
  data: Prisma.ChatCreateManyInput | Prisma.ChatCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Chat createManyAndReturn
 */
export type ChatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * The data used to create many Chats.
   */
  data: Prisma.ChatCreateManyInput | Prisma.ChatCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Chat update
 */
export type ChatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
  /**
   * The data needed to update a Chat.
   */
  data: Prisma.XOR<Prisma.ChatUpdateInput, Prisma.ChatUncheckedUpdateInput>
  /**
   * Choose, which Chat to update.
   */
  where: Prisma.ChatWhereUniqueInput
}

/**
 * Chat updateMany
 */
export type ChatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Chats.
   */
  data: Prisma.XOR<Prisma.ChatUpdateManyMutationInput, Prisma.ChatUncheckedUpdateManyInput>
  /**
   * Filter which Chats to update
   */
  where?: Prisma.ChatWhereInput
  /**
   * Limit how many Chats to update.
   */
  limit?: number
}

/**
 * Chat updateManyAndReturn
 */
export type ChatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * The data used to update Chats.
   */
  data: Prisma.XOR<Prisma.ChatUpdateManyMutationInput, Prisma.ChatUncheckedUpdateManyInput>
  /**
   * Filter which Chats to update
   */
  where?: Prisma.ChatWhereInput
  /**
   * Limit how many Chats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Chat upsert
 */
export type ChatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
  /**
   * The filter to search for the Chat to update in case it exists.
   */
  where: Prisma.ChatWhereUniqueInput
  /**
   * In case the Chat found by the `where` argument doesn't exist, create a new Chat with this data.
   */
  create: Prisma.XOR<Prisma.ChatCreateInput, Prisma.ChatUncheckedCreateInput>
  /**
   * In case the Chat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ChatUpdateInput, Prisma.ChatUncheckedUpdateInput>
}

/**
 * Chat delete
 */
export type ChatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
  /**
   * Filter which Chat to delete.
   */
  where: Prisma.ChatWhereUniqueInput
}

/**
 * Chat deleteMany
 */
export type ChatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Chats to delete
   */
  where?: Prisma.ChatWhereInput
  /**
   * Limit how many Chats to delete.
   */
  limit?: number
}

/**
 * Chat.hotel
 */
export type Chat$hotelArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hotel
   */
  select?: Prisma.HotelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hotel
   */
  omit?: Prisma.HotelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HotelInclude<ExtArgs> | null
  where?: Prisma.HotelWhereInput
}

/**
 * Chat.support
 */
export type Chat$supportArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Support
   */
  select?: Prisma.SupportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Support
   */
  omit?: Prisma.SupportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SupportInclude<ExtArgs> | null
  where?: Prisma.SupportWhereInput
}

/**
 * Chat.token
 */
export type Chat$tokenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestToken
   */
  select?: Prisma.GuestTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestToken
   */
  omit?: Prisma.GuestTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestTokenInclude<ExtArgs> | null
  where?: Prisma.GuestTokenWhereInput
}

/**
 * Chat.chatRoom
 */
export type Chat$chatRoomArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatMessage
   */
  select?: Prisma.ChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatMessage
   */
  omit?: Prisma.ChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatMessageInclude<ExtArgs> | null
  where?: Prisma.ChatMessageWhereInput
  orderBy?: Prisma.ChatMessageOrderByWithRelationInput | Prisma.ChatMessageOrderByWithRelationInput[]
  cursor?: Prisma.ChatMessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ChatMessageScalarFieldEnum | Prisma.ChatMessageScalarFieldEnum[]
}

/**
 * Chat without action
 */
export type ChatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chat
   */
  select?: Prisma.ChatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chat
   */
  omit?: Prisma.ChatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatInclude<ExtArgs> | null
}
