
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Hotel: 'Hotel',
  CheckList: 'CheckList',
  CheckListItem: 'CheckListItem',
  BusinessUser: 'BusinessUser',
  GuestUser: 'GuestUser',
  RoomAmeneties: 'RoomAmeneties',
  Amenety: 'Amenety',
  GuestToken: 'GuestToken',
  Feedback: 'Feedback',
  FeedbackItem: 'FeedbackItem',
  Support: 'Support',
  Chat: 'Chat',
  ChatMessage: 'ChatMessage'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const HotelScalarFieldEnum = {
  id: 'id',
  hotelName: 'hotelName',
  adresse: 'adresse',
  city: 'city',
  classement: 'classement',
  code_postal: 'code_postal',
  country: 'country',
  departement: 'departement',
  region: 'region',
  lat: 'lat',
  lng: 'lng',
  mail: 'mail',
  partnership: 'partnership',
  phone: 'phone',
  room: 'room',
  website: 'website',
  appLink: 'appLink',
  base64Url: 'base64Url',
  logo: 'logo',
  pricingModel: 'pricingModel',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type HotelScalarFieldEnum = (typeof HotelScalarFieldEnum)[keyof typeof HotelScalarFieldEnum]


export const CheckListScalarFieldEnum = {
  id: 'id',
  hotelId: 'hotelId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CheckListScalarFieldEnum = (typeof CheckListScalarFieldEnum)[keyof typeof CheckListScalarFieldEnum]


export const CheckListItemScalarFieldEnum = {
  id: 'id',
  task: 'task',
  status: 'status',
  checkListId: 'checkListId',
  morningId: 'morningId',
  eveningId: 'eveningId',
  nightId: 'nightId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CheckListItemScalarFieldEnum = (typeof CheckListItemScalarFieldEnum)[keyof typeof CheckListItemScalarFieldEnum]


export const BusinessUserScalarFieldEnum = {
  id: 'id',
  adminStatus: 'adminStatus',
  email: 'email',
  hotelId: 'hotelId',
  password: 'password',
  username: 'username',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BusinessUserScalarFieldEnum = (typeof BusinessUserScalarFieldEnum)[keyof typeof BusinessUserScalarFieldEnum]


export const GuestUserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  phone: 'phone',
  gender: 'gender',
  photo: 'photo',
  language: 'language',
  localLanguage: 'localLanguage',
  room: 'room',
  hotelId: 'hotelId',
  journeyId: 'journeyId',
  guestCategory: 'guestCategory',
  guestCategoryClone: 'guestCategoryClone',
  checkoutDate: 'checkoutDate',
  notificationStatus: 'notificationStatus',
  lastTimeConnected: 'lastTimeConnected',
  newConnection: 'newConnection',
  isChatting: 'isChatting',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  hotelVisitedArray: 'hotelVisitedArray'
} as const

export type GuestUserScalarFieldEnum = (typeof GuestUserScalarFieldEnum)[keyof typeof GuestUserScalarFieldEnum]


export const RoomAmenetiesScalarFieldEnum = {
  id: 'id',
  guestUserId: 'guestUserId',
  hotelId: 'hotelId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RoomAmenetiesScalarFieldEnum = (typeof RoomAmenetiesScalarFieldEnum)[keyof typeof RoomAmenetiesScalarFieldEnum]


export const AmenetyScalarFieldEnum = {
  id: 'id',
  checkoutDate: 'checkoutDate',
  clientName: 'clientName',
  room: 'room',
  babyBedId: 'babyBedId',
  blanketId: 'blanketId',
  hairDryerId: 'hairDryerId',
  ironId: 'ironId',
  pillowId: 'pillowId',
  soapId: 'soapId',
  toiletPaperId: 'toiletPaperId',
  towelId: 'towelId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AmenetyScalarFieldEnum = (typeof AmenetyScalarFieldEnum)[keyof typeof AmenetyScalarFieldEnum]


export const GuestTokenScalarFieldEnum = {
  id: 'id',
  guestUserId: 'guestUserId',
  endpoint: 'endpoint',
  expirationTime: 'expirationTime',
  auth: 'auth',
  p256dh: 'p256dh',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GuestTokenScalarFieldEnum = (typeof GuestTokenScalarFieldEnum)[keyof typeof GuestTokenScalarFieldEnum]


export const FeedbackScalarFieldEnum = {
  id: 'id',
  hotelId: 'hotelId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FeedbackScalarFieldEnum = (typeof FeedbackScalarFieldEnum)[keyof typeof FeedbackScalarFieldEnum]


export const FeedbackItemScalarFieldEnum = {
  id: 'id',
  author: 'author',
  text: 'text',
  hotelDept: 'hotelDept',
  hotelName: 'hotelName',
  hotelRegion: 'hotelRegion',
  satisfactionFeedbackId: 'satisfactionFeedbackId',
  improvementFeedbackId: 'improvementFeedbackId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FeedbackItemScalarFieldEnum = (typeof FeedbackItemScalarFieldEnum)[keyof typeof FeedbackItemScalarFieldEnum]


export const SupportScalarFieldEnum = {
  id: 'id',
  hotelId: 'hotelId',
  hotelName: 'hotelName',
  pricingModel: 'pricingModel',
  checkoutDate: 'checkoutDate',
  adminSpeak: 'adminSpeak',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SupportScalarFieldEnum = (typeof SupportScalarFieldEnum)[keyof typeof SupportScalarFieldEnum]


export const ChatScalarFieldEnum = {
  id: 'id',
  clientFullName: 'clientFullName',
  checkoutDate: 'checkoutDate',
  guestLanguage: 'guestLanguage',
  hotelResponding: 'hotelResponding',
  isChatting: 'isChatting',
  room: 'room',
  status: 'status',
  userId: 'userId',
  hotelId: 'hotelId',
  supportId: 'supportId',
  guestTokenId: 'guestTokenId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChatScalarFieldEnum = (typeof ChatScalarFieldEnum)[keyof typeof ChatScalarFieldEnum]


export const ChatMessageScalarFieldEnum = {
  id: 'id',
  author: 'author',
  email: 'email',
  title: 'title',
  text: 'text',
  photo: 'photo',
  date: 'date',
  room: 'room',
  userId: 'userId',
  chatId: 'chatId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChatMessageScalarFieldEnum = (typeof ChatMessageScalarFieldEnum)[keyof typeof ChatMessageScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

