
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Hotel
 * 
 */
export type Hotel = Prisma.HotelModel
/**
 * Model CheckList
 * 
 */
export type CheckList = Prisma.CheckListModel
/**
 * Model CheckListItem
 * 
 */
export type CheckListItem = Prisma.CheckListItemModel
/**
 * Model BusinessUser
 * 
 */
export type BusinessUser = Prisma.BusinessUserModel
/**
 * Model GuestUser
 * 
 */
export type GuestUser = Prisma.GuestUserModel
/**
 * Model RoomAmeneties
 * 
 */
export type RoomAmeneties = Prisma.RoomAmenetiesModel
/**
 * Model Amenety
 * 
 */
export type Amenety = Prisma.AmenetyModel
/**
 * Model GuestToken
 * 
 */
export type GuestToken = Prisma.GuestTokenModel
/**
 * Model Feedback
 * 
 */
export type Feedback = Prisma.FeedbackModel
/**
 * Model FeedbackItem
 * 
 */
export type FeedbackItem = Prisma.FeedbackItemModel
/**
 * Model Support
 * 
 */
export type Support = Prisma.SupportModel
/**
 * Model Chat
 * 
 */
export type Chat = Prisma.ChatModel
/**
 * Model ChatMessage
 * 
 */
export type ChatMessage = Prisma.ChatMessageModel
