
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Hotels
 * const hotels = await prisma.hotel.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Hotel
 * 
 */
export type Hotel = Prisma.HotelModel
/**
 * Model CheckList
 * 
 */
export type CheckList = Prisma.CheckListModel
/**
 * Model CheckListItem
 * 
 */
export type CheckListItem = Prisma.CheckListItemModel
/**
 * Model BusinessUser
 * 
 */
export type BusinessUser = Prisma.BusinessUserModel
/**
 * Model GuestUser
 * 
 */
export type GuestUser = Prisma.GuestUserModel
/**
 * Model RoomAmeneties
 * 
 */
export type RoomAmeneties = Prisma.RoomAmenetiesModel
/**
 * Model Amenety
 * 
 */
export type Amenety = Prisma.AmenetyModel
/**
 * Model GuestToken
 * 
 */
export type GuestToken = Prisma.GuestTokenModel
/**
 * Model Feedback
 * 
 */
export type Feedback = Prisma.FeedbackModel
/**
 * Model FeedbackItem
 * 
 */
export type FeedbackItem = Prisma.FeedbackItemModel
/**
 * Model Support
 * 
 */
export type Support = Prisma.SupportModel
/**
 * Model Chat
 * 
 */
export type Chat = Prisma.ChatModel
/**
 * Model ChatMessage
 * 
 */
export type ChatMessage = Prisma.ChatMessageModel
