
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CheckListItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CheckListItem
 * 
 */
export type CheckListItemModel = runtime.Types.Result.DefaultSelection<Prisma.$CheckListItemPayload>

export type AggregateCheckListItem = {
  _count: CheckListItemCountAggregateOutputType | null
  _min: CheckListItemMinAggregateOutputType | null
  _max: CheckListItemMaxAggregateOutputType | null
}

export type CheckListItemMinAggregateOutputType = {
  id: string | null
  task: string | null
  status: boolean | null
  checkListId: string | null
  morningId: string | null
  eveningId: string | null
  nightId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CheckListItemMaxAggregateOutputType = {
  id: string | null
  task: string | null
  status: boolean | null
  checkListId: string | null
  morningId: string | null
  eveningId: string | null
  nightId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CheckListItemCountAggregateOutputType = {
  id: number
  task: number
  status: number
  checkListId: number
  morningId: number
  eveningId: number
  nightId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CheckListItemMinAggregateInputType = {
  id?: true
  task?: true
  status?: true
  checkListId?: true
  morningId?: true
  eveningId?: true
  nightId?: true
  createdAt?: true
  updatedAt?: true
}

export type CheckListItemMaxAggregateInputType = {
  id?: true
  task?: true
  status?: true
  checkListId?: true
  morningId?: true
  eveningId?: true
  nightId?: true
  createdAt?: true
  updatedAt?: true
}

export type CheckListItemCountAggregateInputType = {
  id?: true
  task?: true
  status?: true
  checkListId?: true
  morningId?: true
  eveningId?: true
  nightId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CheckListItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CheckListItem to aggregate.
   */
  where?: Prisma.CheckListItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckListItems to fetch.
   */
  orderBy?: Prisma.CheckListItemOrderByWithRelationInput | Prisma.CheckListItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CheckListItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckListItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckListItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CheckListItems
  **/
  _count?: true | CheckListItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CheckListItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CheckListItemMaxAggregateInputType
}

export type GetCheckListItemAggregateType<T extends CheckListItemAggregateArgs> = {
      [P in keyof T & keyof AggregateCheckListItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCheckListItem[P]>
    : Prisma.GetScalarType<T[P], AggregateCheckListItem[P]>
}




export type CheckListItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckListItemWhereInput
  orderBy?: Prisma.CheckListItemOrderByWithAggregationInput | Prisma.CheckListItemOrderByWithAggregationInput[]
  by: Prisma.CheckListItemScalarFieldEnum[] | Prisma.CheckListItemScalarFieldEnum
  having?: Prisma.CheckListItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CheckListItemCountAggregateInputType | true
  _min?: CheckListItemMinAggregateInputType
  _max?: CheckListItemMaxAggregateInputType
}

export type CheckListItemGroupByOutputType = {
  id: string
  task: string
  status: boolean
  checkListId: string
  morningId: string | null
  eveningId: string | null
  nightId: string | null
  createdAt: Date
  updatedAt: Date
  _count: CheckListItemCountAggregateOutputType | null
  _min: CheckListItemMinAggregateOutputType | null
  _max: CheckListItemMaxAggregateOutputType | null
}

export type GetCheckListItemGroupByPayload<T extends CheckListItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CheckListItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CheckListItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CheckListItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CheckListItemGroupByOutputType[P]>
      }
    >
  >



export type CheckListItemWhereInput = {
  AND?: Prisma.CheckListItemWhereInput | Prisma.CheckListItemWhereInput[]
  OR?: Prisma.CheckListItemWhereInput[]
  NOT?: Prisma.CheckListItemWhereInput | Prisma.CheckListItemWhereInput[]
  id?: Prisma.StringFilter<"CheckListItem"> | string
  task?: Prisma.StringFilter<"CheckListItem"> | string
  status?: Prisma.BoolFilter<"CheckListItem"> | boolean
  checkListId?: Prisma.StringFilter<"CheckListItem"> | string
  morningId?: Prisma.StringNullableFilter<"CheckListItem"> | string | null
  eveningId?: Prisma.StringNullableFilter<"CheckListItem"> | string | null
  nightId?: Prisma.StringNullableFilter<"CheckListItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CheckListItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CheckListItem"> | Date | string
  morning?: Prisma.XOR<Prisma.CheckListNullableScalarRelationFilter, Prisma.CheckListWhereInput> | null
  evening?: Prisma.XOR<Prisma.CheckListNullableScalarRelationFilter, Prisma.CheckListWhereInput> | null
  night?: Prisma.XOR<Prisma.CheckListNullableScalarRelationFilter, Prisma.CheckListWhereInput> | null
}

export type CheckListItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  task?: Prisma.SortOrder
  status?: Prisma.SortOrder
  checkListId?: Prisma.SortOrder
  morningId?: Prisma.SortOrderInput | Prisma.SortOrder
  eveningId?: Prisma.SortOrderInput | Prisma.SortOrder
  nightId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  morning?: Prisma.CheckListOrderByWithRelationInput
  evening?: Prisma.CheckListOrderByWithRelationInput
  night?: Prisma.CheckListOrderByWithRelationInput
}

export type CheckListItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  morningId?: string
  eveningId?: string
  nightId?: string
  AND?: Prisma.CheckListItemWhereInput | Prisma.CheckListItemWhereInput[]
  OR?: Prisma.CheckListItemWhereInput[]
  NOT?: Prisma.CheckListItemWhereInput | Prisma.CheckListItemWhereInput[]
  task?: Prisma.StringFilter<"CheckListItem"> | string
  status?: Prisma.BoolFilter<"CheckListItem"> | boolean
  checkListId?: Prisma.StringFilter<"CheckListItem"> | string
  createdAt?: Prisma.DateTimeFilter<"CheckListItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CheckListItem"> | Date | string
  morning?: Prisma.XOR<Prisma.CheckListNullableScalarRelationFilter, Prisma.CheckListWhereInput> | null
  evening?: Prisma.XOR<Prisma.CheckListNullableScalarRelationFilter, Prisma.CheckListWhereInput> | null
  night?: Prisma.XOR<Prisma.CheckListNullableScalarRelationFilter, Prisma.CheckListWhereInput> | null
}, "id" | "morningId" | "eveningId" | "nightId">

export type CheckListItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  task?: Prisma.SortOrder
  status?: Prisma.SortOrder
  checkListId?: Prisma.SortOrder
  morningId?: Prisma.SortOrderInput | Prisma.SortOrder
  eveningId?: Prisma.SortOrderInput | Prisma.SortOrder
  nightId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CheckListItemCountOrderByAggregateInput
  _max?: Prisma.CheckListItemMaxOrderByAggregateInput
  _min?: Prisma.CheckListItemMinOrderByAggregateInput
}

export type CheckListItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.CheckListItemScalarWhereWithAggregatesInput | Prisma.CheckListItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.CheckListItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CheckListItemScalarWhereWithAggregatesInput | Prisma.CheckListItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CheckListItem"> | string
  task?: Prisma.StringWithAggregatesFilter<"CheckListItem"> | string
  status?: Prisma.BoolWithAggregatesFilter<"CheckListItem"> | boolean
  checkListId?: Prisma.StringWithAggregatesFilter<"CheckListItem"> | string
  morningId?: Prisma.StringNullableWithAggregatesFilter<"CheckListItem"> | string | null
  eveningId?: Prisma.StringNullableWithAggregatesFilter<"CheckListItem"> | string | null
  nightId?: Prisma.StringNullableWithAggregatesFilter<"CheckListItem"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CheckListItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CheckListItem"> | Date | string
}

export type CheckListItemCreateInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListCreateNestedOneWithoutMorningInput
  evening?: Prisma.CheckListCreateNestedOneWithoutEveningInput
  night?: Prisma.CheckListCreateNestedOneWithoutNightInput
}

export type CheckListItemUncheckedCreateInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  morningId?: string | null
  eveningId?: string | null
  nightId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListUpdateOneWithoutMorningNestedInput
  evening?: Prisma.CheckListUpdateOneWithoutEveningNestedInput
  night?: Prisma.CheckListUpdateOneWithoutNightNestedInput
}

export type CheckListItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  morningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eveningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListItemCreateManyInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  morningId?: string | null
  eveningId?: string | null
  nightId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  morningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eveningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListItemListRelationFilter = {
  every?: Prisma.CheckListItemWhereInput
  some?: Prisma.CheckListItemWhereInput
  none?: Prisma.CheckListItemWhereInput
}

export type CheckListItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CheckListItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  task?: Prisma.SortOrder
  status?: Prisma.SortOrder
  checkListId?: Prisma.SortOrder
  morningId?: Prisma.SortOrder
  eveningId?: Prisma.SortOrder
  nightId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CheckListItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  task?: Prisma.SortOrder
  status?: Prisma.SortOrder
  checkListId?: Prisma.SortOrder
  morningId?: Prisma.SortOrder
  eveningId?: Prisma.SortOrder
  nightId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CheckListItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  task?: Prisma.SortOrder
  status?: Prisma.SortOrder
  checkListId?: Prisma.SortOrder
  morningId?: Prisma.SortOrder
  eveningId?: Prisma.SortOrder
  nightId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CheckListItemCreateNestedManyWithoutMorningInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutMorningInput, Prisma.CheckListItemUncheckedCreateWithoutMorningInput> | Prisma.CheckListItemCreateWithoutMorningInput[] | Prisma.CheckListItemUncheckedCreateWithoutMorningInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutMorningInput | Prisma.CheckListItemCreateOrConnectWithoutMorningInput[]
  createMany?: Prisma.CheckListItemCreateManyMorningInputEnvelope
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
}

export type CheckListItemCreateNestedManyWithoutEveningInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutEveningInput, Prisma.CheckListItemUncheckedCreateWithoutEveningInput> | Prisma.CheckListItemCreateWithoutEveningInput[] | Prisma.CheckListItemUncheckedCreateWithoutEveningInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutEveningInput | Prisma.CheckListItemCreateOrConnectWithoutEveningInput[]
  createMany?: Prisma.CheckListItemCreateManyEveningInputEnvelope
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
}

export type CheckListItemCreateNestedManyWithoutNightInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutNightInput, Prisma.CheckListItemUncheckedCreateWithoutNightInput> | Prisma.CheckListItemCreateWithoutNightInput[] | Prisma.CheckListItemUncheckedCreateWithoutNightInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutNightInput | Prisma.CheckListItemCreateOrConnectWithoutNightInput[]
  createMany?: Prisma.CheckListItemCreateManyNightInputEnvelope
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
}

export type CheckListItemUncheckedCreateNestedManyWithoutMorningInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutMorningInput, Prisma.CheckListItemUncheckedCreateWithoutMorningInput> | Prisma.CheckListItemCreateWithoutMorningInput[] | Prisma.CheckListItemUncheckedCreateWithoutMorningInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutMorningInput | Prisma.CheckListItemCreateOrConnectWithoutMorningInput[]
  createMany?: Prisma.CheckListItemCreateManyMorningInputEnvelope
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
}

export type CheckListItemUncheckedCreateNestedManyWithoutEveningInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutEveningInput, Prisma.CheckListItemUncheckedCreateWithoutEveningInput> | Prisma.CheckListItemCreateWithoutEveningInput[] | Prisma.CheckListItemUncheckedCreateWithoutEveningInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutEveningInput | Prisma.CheckListItemCreateOrConnectWithoutEveningInput[]
  createMany?: Prisma.CheckListItemCreateManyEveningInputEnvelope
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
}

export type CheckListItemUncheckedCreateNestedManyWithoutNightInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutNightInput, Prisma.CheckListItemUncheckedCreateWithoutNightInput> | Prisma.CheckListItemCreateWithoutNightInput[] | Prisma.CheckListItemUncheckedCreateWithoutNightInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutNightInput | Prisma.CheckListItemCreateOrConnectWithoutNightInput[]
  createMany?: Prisma.CheckListItemCreateManyNightInputEnvelope
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
}

export type CheckListItemUpdateManyWithoutMorningNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutMorningInput, Prisma.CheckListItemUncheckedCreateWithoutMorningInput> | Prisma.CheckListItemCreateWithoutMorningInput[] | Prisma.CheckListItemUncheckedCreateWithoutMorningInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutMorningInput | Prisma.CheckListItemCreateOrConnectWithoutMorningInput[]
  upsert?: Prisma.CheckListItemUpsertWithWhereUniqueWithoutMorningInput | Prisma.CheckListItemUpsertWithWhereUniqueWithoutMorningInput[]
  createMany?: Prisma.CheckListItemCreateManyMorningInputEnvelope
  set?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  disconnect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  delete?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  update?: Prisma.CheckListItemUpdateWithWhereUniqueWithoutMorningInput | Prisma.CheckListItemUpdateWithWhereUniqueWithoutMorningInput[]
  updateMany?: Prisma.CheckListItemUpdateManyWithWhereWithoutMorningInput | Prisma.CheckListItemUpdateManyWithWhereWithoutMorningInput[]
  deleteMany?: Prisma.CheckListItemScalarWhereInput | Prisma.CheckListItemScalarWhereInput[]
}

export type CheckListItemUpdateManyWithoutEveningNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutEveningInput, Prisma.CheckListItemUncheckedCreateWithoutEveningInput> | Prisma.CheckListItemCreateWithoutEveningInput[] | Prisma.CheckListItemUncheckedCreateWithoutEveningInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutEveningInput | Prisma.CheckListItemCreateOrConnectWithoutEveningInput[]
  upsert?: Prisma.CheckListItemUpsertWithWhereUniqueWithoutEveningInput | Prisma.CheckListItemUpsertWithWhereUniqueWithoutEveningInput[]
  createMany?: Prisma.CheckListItemCreateManyEveningInputEnvelope
  set?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  disconnect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  delete?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  update?: Prisma.CheckListItemUpdateWithWhereUniqueWithoutEveningInput | Prisma.CheckListItemUpdateWithWhereUniqueWithoutEveningInput[]
  updateMany?: Prisma.CheckListItemUpdateManyWithWhereWithoutEveningInput | Prisma.CheckListItemUpdateManyWithWhereWithoutEveningInput[]
  deleteMany?: Prisma.CheckListItemScalarWhereInput | Prisma.CheckListItemScalarWhereInput[]
}

export type CheckListItemUpdateManyWithoutNightNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutNightInput, Prisma.CheckListItemUncheckedCreateWithoutNightInput> | Prisma.CheckListItemCreateWithoutNightInput[] | Prisma.CheckListItemUncheckedCreateWithoutNightInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutNightInput | Prisma.CheckListItemCreateOrConnectWithoutNightInput[]
  upsert?: Prisma.CheckListItemUpsertWithWhereUniqueWithoutNightInput | Prisma.CheckListItemUpsertWithWhereUniqueWithoutNightInput[]
  createMany?: Prisma.CheckListItemCreateManyNightInputEnvelope
  set?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  disconnect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  delete?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  update?: Prisma.CheckListItemUpdateWithWhereUniqueWithoutNightInput | Prisma.CheckListItemUpdateWithWhereUniqueWithoutNightInput[]
  updateMany?: Prisma.CheckListItemUpdateManyWithWhereWithoutNightInput | Prisma.CheckListItemUpdateManyWithWhereWithoutNightInput[]
  deleteMany?: Prisma.CheckListItemScalarWhereInput | Prisma.CheckListItemScalarWhereInput[]
}

export type CheckListItemUncheckedUpdateManyWithoutMorningNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutMorningInput, Prisma.CheckListItemUncheckedCreateWithoutMorningInput> | Prisma.CheckListItemCreateWithoutMorningInput[] | Prisma.CheckListItemUncheckedCreateWithoutMorningInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutMorningInput | Prisma.CheckListItemCreateOrConnectWithoutMorningInput[]
  upsert?: Prisma.CheckListItemUpsertWithWhereUniqueWithoutMorningInput | Prisma.CheckListItemUpsertWithWhereUniqueWithoutMorningInput[]
  createMany?: Prisma.CheckListItemCreateManyMorningInputEnvelope
  set?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  disconnect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  delete?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  update?: Prisma.CheckListItemUpdateWithWhereUniqueWithoutMorningInput | Prisma.CheckListItemUpdateWithWhereUniqueWithoutMorningInput[]
  updateMany?: Prisma.CheckListItemUpdateManyWithWhereWithoutMorningInput | Prisma.CheckListItemUpdateManyWithWhereWithoutMorningInput[]
  deleteMany?: Prisma.CheckListItemScalarWhereInput | Prisma.CheckListItemScalarWhereInput[]
}

export type CheckListItemUncheckedUpdateManyWithoutEveningNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutEveningInput, Prisma.CheckListItemUncheckedCreateWithoutEveningInput> | Prisma.CheckListItemCreateWithoutEveningInput[] | Prisma.CheckListItemUncheckedCreateWithoutEveningInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutEveningInput | Prisma.CheckListItemCreateOrConnectWithoutEveningInput[]
  upsert?: Prisma.CheckListItemUpsertWithWhereUniqueWithoutEveningInput | Prisma.CheckListItemUpsertWithWhereUniqueWithoutEveningInput[]
  createMany?: Prisma.CheckListItemCreateManyEveningInputEnvelope
  set?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  disconnect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  delete?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  update?: Prisma.CheckListItemUpdateWithWhereUniqueWithoutEveningInput | Prisma.CheckListItemUpdateWithWhereUniqueWithoutEveningInput[]
  updateMany?: Prisma.CheckListItemUpdateManyWithWhereWithoutEveningInput | Prisma.CheckListItemUpdateManyWithWhereWithoutEveningInput[]
  deleteMany?: Prisma.CheckListItemScalarWhereInput | Prisma.CheckListItemScalarWhereInput[]
}

export type CheckListItemUncheckedUpdateManyWithoutNightNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListItemCreateWithoutNightInput, Prisma.CheckListItemUncheckedCreateWithoutNightInput> | Prisma.CheckListItemCreateWithoutNightInput[] | Prisma.CheckListItemUncheckedCreateWithoutNightInput[]
  connectOrCreate?: Prisma.CheckListItemCreateOrConnectWithoutNightInput | Prisma.CheckListItemCreateOrConnectWithoutNightInput[]
  upsert?: Prisma.CheckListItemUpsertWithWhereUniqueWithoutNightInput | Prisma.CheckListItemUpsertWithWhereUniqueWithoutNightInput[]
  createMany?: Prisma.CheckListItemCreateManyNightInputEnvelope
  set?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  disconnect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  delete?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  connect?: Prisma.CheckListItemWhereUniqueInput | Prisma.CheckListItemWhereUniqueInput[]
  update?: Prisma.CheckListItemUpdateWithWhereUniqueWithoutNightInput | Prisma.CheckListItemUpdateWithWhereUniqueWithoutNightInput[]
  updateMany?: Prisma.CheckListItemUpdateManyWithWhereWithoutNightInput | Prisma.CheckListItemUpdateManyWithWhereWithoutNightInput[]
  deleteMany?: Prisma.CheckListItemScalarWhereInput | Prisma.CheckListItemScalarWhereInput[]
}

export type CheckListItemCreateWithoutMorningInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  createdAt: Date | string
  updatedAt: Date | string
  evening?: Prisma.CheckListCreateNestedOneWithoutEveningInput
  night?: Prisma.CheckListCreateNestedOneWithoutNightInput
}

export type CheckListItemUncheckedCreateWithoutMorningInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  eveningId?: string | null
  nightId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListItemCreateOrConnectWithoutMorningInput = {
  where: Prisma.CheckListItemWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckListItemCreateWithoutMorningInput, Prisma.CheckListItemUncheckedCreateWithoutMorningInput>
}

export type CheckListItemCreateManyMorningInputEnvelope = {
  data: Prisma.CheckListItemCreateManyMorningInput | Prisma.CheckListItemCreateManyMorningInput[]
  skipDuplicates?: boolean
}

export type CheckListItemCreateWithoutEveningInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListCreateNestedOneWithoutMorningInput
  night?: Prisma.CheckListCreateNestedOneWithoutNightInput
}

export type CheckListItemUncheckedCreateWithoutEveningInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  morningId?: string | null
  nightId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListItemCreateOrConnectWithoutEveningInput = {
  where: Prisma.CheckListItemWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckListItemCreateWithoutEveningInput, Prisma.CheckListItemUncheckedCreateWithoutEveningInput>
}

export type CheckListItemCreateManyEveningInputEnvelope = {
  data: Prisma.CheckListItemCreateManyEveningInput | Prisma.CheckListItemCreateManyEveningInput[]
  skipDuplicates?: boolean
}

export type CheckListItemCreateWithoutNightInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListCreateNestedOneWithoutMorningInput
  evening?: Prisma.CheckListCreateNestedOneWithoutEveningInput
}

export type CheckListItemUncheckedCreateWithoutNightInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  morningId?: string | null
  eveningId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListItemCreateOrConnectWithoutNightInput = {
  where: Prisma.CheckListItemWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckListItemCreateWithoutNightInput, Prisma.CheckListItemUncheckedCreateWithoutNightInput>
}

export type CheckListItemCreateManyNightInputEnvelope = {
  data: Prisma.CheckListItemCreateManyNightInput | Prisma.CheckListItemCreateManyNightInput[]
  skipDuplicates?: boolean
}

export type CheckListItemUpsertWithWhereUniqueWithoutMorningInput = {
  where: Prisma.CheckListItemWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckListItemUpdateWithoutMorningInput, Prisma.CheckListItemUncheckedUpdateWithoutMorningInput>
  create: Prisma.XOR<Prisma.CheckListItemCreateWithoutMorningInput, Prisma.CheckListItemUncheckedCreateWithoutMorningInput>
}

export type CheckListItemUpdateWithWhereUniqueWithoutMorningInput = {
  where: Prisma.CheckListItemWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckListItemUpdateWithoutMorningInput, Prisma.CheckListItemUncheckedUpdateWithoutMorningInput>
}

export type CheckListItemUpdateManyWithWhereWithoutMorningInput = {
  where: Prisma.CheckListItemScalarWhereInput
  data: Prisma.XOR<Prisma.CheckListItemUpdateManyMutationInput, Prisma.CheckListItemUncheckedUpdateManyWithoutMorningInput>
}

export type CheckListItemScalarWhereInput = {
  AND?: Prisma.CheckListItemScalarWhereInput | Prisma.CheckListItemScalarWhereInput[]
  OR?: Prisma.CheckListItemScalarWhereInput[]
  NOT?: Prisma.CheckListItemScalarWhereInput | Prisma.CheckListItemScalarWhereInput[]
  id?: Prisma.StringFilter<"CheckListItem"> | string
  task?: Prisma.StringFilter<"CheckListItem"> | string
  status?: Prisma.BoolFilter<"CheckListItem"> | boolean
  checkListId?: Prisma.StringFilter<"CheckListItem"> | string
  morningId?: Prisma.StringNullableFilter<"CheckListItem"> | string | null
  eveningId?: Prisma.StringNullableFilter<"CheckListItem"> | string | null
  nightId?: Prisma.StringNullableFilter<"CheckListItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CheckListItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CheckListItem"> | Date | string
}

export type CheckListItemUpsertWithWhereUniqueWithoutEveningInput = {
  where: Prisma.CheckListItemWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckListItemUpdateWithoutEveningInput, Prisma.CheckListItemUncheckedUpdateWithoutEveningInput>
  create: Prisma.XOR<Prisma.CheckListItemCreateWithoutEveningInput, Prisma.CheckListItemUncheckedCreateWithoutEveningInput>
}

export type CheckListItemUpdateWithWhereUniqueWithoutEveningInput = {
  where: Prisma.CheckListItemWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckListItemUpdateWithoutEveningInput, Prisma.CheckListItemUncheckedUpdateWithoutEveningInput>
}

export type CheckListItemUpdateManyWithWhereWithoutEveningInput = {
  where: Prisma.CheckListItemScalarWhereInput
  data: Prisma.XOR<Prisma.CheckListItemUpdateManyMutationInput, Prisma.CheckListItemUncheckedUpdateManyWithoutEveningInput>
}

export type CheckListItemUpsertWithWhereUniqueWithoutNightInput = {
  where: Prisma.CheckListItemWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckListItemUpdateWithoutNightInput, Prisma.CheckListItemUncheckedUpdateWithoutNightInput>
  create: Prisma.XOR<Prisma.CheckListItemCreateWithoutNightInput, Prisma.CheckListItemUncheckedCreateWithoutNightInput>
}

export type CheckListItemUpdateWithWhereUniqueWithoutNightInput = {
  where: Prisma.CheckListItemWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckListItemUpdateWithoutNightInput, Prisma.CheckListItemUncheckedUpdateWithoutNightInput>
}

export type CheckListItemUpdateManyWithWhereWithoutNightInput = {
  where: Prisma.CheckListItemScalarWhereInput
  data: Prisma.XOR<Prisma.CheckListItemUpdateManyMutationInput, Prisma.CheckListItemUncheckedUpdateManyWithoutNightInput>
}

export type CheckListItemCreateManyMorningInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  eveningId?: string | null
  nightId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListItemCreateManyEveningInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  morningId?: string | null
  nightId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListItemCreateManyNightInput = {
  id?: string
  task: string
  status: boolean
  checkListId: string
  morningId?: string | null
  eveningId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListItemUpdateWithoutMorningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  evening?: Prisma.CheckListUpdateOneWithoutEveningNestedInput
  night?: Prisma.CheckListUpdateOneWithoutNightNestedInput
}

export type CheckListItemUncheckedUpdateWithoutMorningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  eveningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListItemUncheckedUpdateManyWithoutMorningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  eveningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListItemUpdateWithoutEveningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListUpdateOneWithoutMorningNestedInput
  night?: Prisma.CheckListUpdateOneWithoutNightNestedInput
}

export type CheckListItemUncheckedUpdateWithoutEveningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  morningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListItemUncheckedUpdateManyWithoutEveningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  morningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListItemUpdateWithoutNightInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListUpdateOneWithoutMorningNestedInput
  evening?: Prisma.CheckListUpdateOneWithoutEveningNestedInput
}

export type CheckListItemUncheckedUpdateWithoutNightInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  morningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eveningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListItemUncheckedUpdateManyWithoutNightInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checkListId?: Prisma.StringFieldUpdateOperationsInput | string
  morningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eveningId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CheckListItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  task?: boolean
  status?: boolean
  checkListId?: boolean
  morningId?: boolean
  eveningId?: boolean
  nightId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  morning?: boolean | Prisma.CheckListItem$morningArgs<ExtArgs>
  evening?: boolean | Prisma.CheckListItem$eveningArgs<ExtArgs>
  night?: boolean | Prisma.CheckListItem$nightArgs<ExtArgs>
}, ExtArgs["result"]["checkListItem"]>

export type CheckListItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  task?: boolean
  status?: boolean
  checkListId?: boolean
  morningId?: boolean
  eveningId?: boolean
  nightId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  morning?: boolean | Prisma.CheckListItem$morningArgs<ExtArgs>
  evening?: boolean | Prisma.CheckListItem$eveningArgs<ExtArgs>
  night?: boolean | Prisma.CheckListItem$nightArgs<ExtArgs>
}, ExtArgs["result"]["checkListItem"]>

export type CheckListItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  task?: boolean
  status?: boolean
  checkListId?: boolean
  morningId?: boolean
  eveningId?: boolean
  nightId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  morning?: boolean | Prisma.CheckListItem$morningArgs<ExtArgs>
  evening?: boolean | Prisma.CheckListItem$eveningArgs<ExtArgs>
  night?: boolean | Prisma.CheckListItem$nightArgs<ExtArgs>
}, ExtArgs["result"]["checkListItem"]>

export type CheckListItemSelectScalar = {
  id?: boolean
  task?: boolean
  status?: boolean
  checkListId?: boolean
  morningId?: boolean
  eveningId?: boolean
  nightId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CheckListItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "task" | "status" | "checkListId" | "morningId" | "eveningId" | "nightId" | "createdAt" | "updatedAt", ExtArgs["result"]["checkListItem"]>
export type CheckListItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  morning?: boolean | Prisma.CheckListItem$morningArgs<ExtArgs>
  evening?: boolean | Prisma.CheckListItem$eveningArgs<ExtArgs>
  night?: boolean | Prisma.CheckListItem$nightArgs<ExtArgs>
}
export type CheckListItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  morning?: boolean | Prisma.CheckListItem$morningArgs<ExtArgs>
  evening?: boolean | Prisma.CheckListItem$eveningArgs<ExtArgs>
  night?: boolean | Prisma.CheckListItem$nightArgs<ExtArgs>
}
export type CheckListItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  morning?: boolean | Prisma.CheckListItem$morningArgs<ExtArgs>
  evening?: boolean | Prisma.CheckListItem$eveningArgs<ExtArgs>
  night?: boolean | Prisma.CheckListItem$nightArgs<ExtArgs>
}

export type $CheckListItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CheckListItem"
  objects: {
    morning: Prisma.$CheckListPayload<ExtArgs> | null
    evening: Prisma.$CheckListPayload<ExtArgs> | null
    night: Prisma.$CheckListPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    task: string
    status: boolean
    checkListId: string
    morningId: string | null
    eveningId: string | null
    nightId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["checkListItem"]>
  composites: {}
}

export type CheckListItemGetPayload<S extends boolean | null | undefined | CheckListItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload, S>

export type CheckListItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CheckListItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CheckListItemCountAggregateInputType | true
  }

export interface CheckListItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CheckListItem'], meta: { name: 'CheckListItem' } }
  /**
   * Find zero or one CheckListItem that matches the filter.
   * @param {CheckListItemFindUniqueArgs} args - Arguments to find a CheckListItem
   * @example
   * // Get one CheckListItem
   * const checkListItem = await prisma.checkListItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CheckListItemFindUniqueArgs>(args: Prisma.SelectSubset<T, CheckListItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CheckListItemClient<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CheckListItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CheckListItemFindUniqueOrThrowArgs} args - Arguments to find a CheckListItem
   * @example
   * // Get one CheckListItem
   * const checkListItem = await prisma.checkListItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CheckListItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CheckListItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckListItemClient<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CheckListItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListItemFindFirstArgs} args - Arguments to find a CheckListItem
   * @example
   * // Get one CheckListItem
   * const checkListItem = await prisma.checkListItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CheckListItemFindFirstArgs>(args?: Prisma.SelectSubset<T, CheckListItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__CheckListItemClient<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CheckListItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListItemFindFirstOrThrowArgs} args - Arguments to find a CheckListItem
   * @example
   * // Get one CheckListItem
   * const checkListItem = await prisma.checkListItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CheckListItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CheckListItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckListItemClient<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CheckListItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CheckListItems
   * const checkListItems = await prisma.checkListItem.findMany()
   * 
   * // Get first 10 CheckListItems
   * const checkListItems = await prisma.checkListItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const checkListItemWithIdOnly = await prisma.checkListItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CheckListItemFindManyArgs>(args?: Prisma.SelectSubset<T, CheckListItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CheckListItem.
   * @param {CheckListItemCreateArgs} args - Arguments to create a CheckListItem.
   * @example
   * // Create one CheckListItem
   * const CheckListItem = await prisma.checkListItem.create({
   *   data: {
   *     // ... data to create a CheckListItem
   *   }
   * })
   * 
   */
  create<T extends CheckListItemCreateArgs>(args: Prisma.SelectSubset<T, CheckListItemCreateArgs<ExtArgs>>): Prisma.Prisma__CheckListItemClient<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CheckListItems.
   * @param {CheckListItemCreateManyArgs} args - Arguments to create many CheckListItems.
   * @example
   * // Create many CheckListItems
   * const checkListItem = await prisma.checkListItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CheckListItemCreateManyArgs>(args?: Prisma.SelectSubset<T, CheckListItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CheckListItems and returns the data saved in the database.
   * @param {CheckListItemCreateManyAndReturnArgs} args - Arguments to create many CheckListItems.
   * @example
   * // Create many CheckListItems
   * const checkListItem = await prisma.checkListItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CheckListItems and only return the `id`
   * const checkListItemWithIdOnly = await prisma.checkListItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CheckListItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CheckListItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CheckListItem.
   * @param {CheckListItemDeleteArgs} args - Arguments to delete one CheckListItem.
   * @example
   * // Delete one CheckListItem
   * const CheckListItem = await prisma.checkListItem.delete({
   *   where: {
   *     // ... filter to delete one CheckListItem
   *   }
   * })
   * 
   */
  delete<T extends CheckListItemDeleteArgs>(args: Prisma.SelectSubset<T, CheckListItemDeleteArgs<ExtArgs>>): Prisma.Prisma__CheckListItemClient<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CheckListItem.
   * @param {CheckListItemUpdateArgs} args - Arguments to update one CheckListItem.
   * @example
   * // Update one CheckListItem
   * const checkListItem = await prisma.checkListItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CheckListItemUpdateArgs>(args: Prisma.SelectSubset<T, CheckListItemUpdateArgs<ExtArgs>>): Prisma.Prisma__CheckListItemClient<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CheckListItems.
   * @param {CheckListItemDeleteManyArgs} args - Arguments to filter CheckListItems to delete.
   * @example
   * // Delete a few CheckListItems
   * const { count } = await prisma.checkListItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CheckListItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, CheckListItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CheckListItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CheckListItems
   * const checkListItem = await prisma.checkListItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CheckListItemUpdateManyArgs>(args: Prisma.SelectSubset<T, CheckListItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CheckListItems and returns the data updated in the database.
   * @param {CheckListItemUpdateManyAndReturnArgs} args - Arguments to update many CheckListItems.
   * @example
   * // Update many CheckListItems
   * const checkListItem = await prisma.checkListItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CheckListItems and only return the `id`
   * const checkListItemWithIdOnly = await prisma.checkListItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CheckListItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CheckListItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CheckListItem.
   * @param {CheckListItemUpsertArgs} args - Arguments to update or create a CheckListItem.
   * @example
   * // Update or create a CheckListItem
   * const checkListItem = await prisma.checkListItem.upsert({
   *   create: {
   *     // ... data to create a CheckListItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CheckListItem we want to update
   *   }
   * })
   */
  upsert<T extends CheckListItemUpsertArgs>(args: Prisma.SelectSubset<T, CheckListItemUpsertArgs<ExtArgs>>): Prisma.Prisma__CheckListItemClient<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CheckListItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListItemCountArgs} args - Arguments to filter CheckListItems to count.
   * @example
   * // Count the number of CheckListItems
   * const count = await prisma.checkListItem.count({
   *   where: {
   *     // ... the filter for the CheckListItems we want to count
   *   }
   * })
  **/
  count<T extends CheckListItemCountArgs>(
    args?: Prisma.Subset<T, CheckListItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CheckListItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CheckListItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CheckListItemAggregateArgs>(args: Prisma.Subset<T, CheckListItemAggregateArgs>): Prisma.PrismaPromise<GetCheckListItemAggregateType<T>>

  /**
   * Group by CheckListItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CheckListItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CheckListItemGroupByArgs['orderBy'] }
      : { orderBy?: CheckListItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CheckListItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCheckListItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CheckListItem model
 */
readonly fields: CheckListItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CheckListItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CheckListItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  morning<T extends Prisma.CheckListItem$morningArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CheckListItem$morningArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  evening<T extends Prisma.CheckListItem$eveningArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CheckListItem$eveningArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  night<T extends Prisma.CheckListItem$nightArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CheckListItem$nightArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CheckListItem model
 */
export interface CheckListItemFieldRefs {
  readonly id: Prisma.FieldRef<"CheckListItem", 'String'>
  readonly task: Prisma.FieldRef<"CheckListItem", 'String'>
  readonly status: Prisma.FieldRef<"CheckListItem", 'Boolean'>
  readonly checkListId: Prisma.FieldRef<"CheckListItem", 'String'>
  readonly morningId: Prisma.FieldRef<"CheckListItem", 'String'>
  readonly eveningId: Prisma.FieldRef<"CheckListItem", 'String'>
  readonly nightId: Prisma.FieldRef<"CheckListItem", 'String'>
  readonly createdAt: Prisma.FieldRef<"CheckListItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CheckListItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CheckListItem findUnique
 */
export type CheckListItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  /**
   * Filter, which CheckListItem to fetch.
   */
  where: Prisma.CheckListItemWhereUniqueInput
}

/**
 * CheckListItem findUniqueOrThrow
 */
export type CheckListItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  /**
   * Filter, which CheckListItem to fetch.
   */
  where: Prisma.CheckListItemWhereUniqueInput
}

/**
 * CheckListItem findFirst
 */
export type CheckListItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  /**
   * Filter, which CheckListItem to fetch.
   */
  where?: Prisma.CheckListItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckListItems to fetch.
   */
  orderBy?: Prisma.CheckListItemOrderByWithRelationInput | Prisma.CheckListItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CheckListItems.
   */
  cursor?: Prisma.CheckListItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckListItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckListItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CheckListItems.
   */
  distinct?: Prisma.CheckListItemScalarFieldEnum | Prisma.CheckListItemScalarFieldEnum[]
}

/**
 * CheckListItem findFirstOrThrow
 */
export type CheckListItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  /**
   * Filter, which CheckListItem to fetch.
   */
  where?: Prisma.CheckListItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckListItems to fetch.
   */
  orderBy?: Prisma.CheckListItemOrderByWithRelationInput | Prisma.CheckListItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CheckListItems.
   */
  cursor?: Prisma.CheckListItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckListItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckListItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CheckListItems.
   */
  distinct?: Prisma.CheckListItemScalarFieldEnum | Prisma.CheckListItemScalarFieldEnum[]
}

/**
 * CheckListItem findMany
 */
export type CheckListItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  /**
   * Filter, which CheckListItems to fetch.
   */
  where?: Prisma.CheckListItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckListItems to fetch.
   */
  orderBy?: Prisma.CheckListItemOrderByWithRelationInput | Prisma.CheckListItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CheckListItems.
   */
  cursor?: Prisma.CheckListItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckListItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckListItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CheckListItems.
   */
  distinct?: Prisma.CheckListItemScalarFieldEnum | Prisma.CheckListItemScalarFieldEnum[]
}

/**
 * CheckListItem create
 */
export type CheckListItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  /**
   * The data needed to create a CheckListItem.
   */
  data: Prisma.XOR<Prisma.CheckListItemCreateInput, Prisma.CheckListItemUncheckedCreateInput>
}

/**
 * CheckListItem createMany
 */
export type CheckListItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CheckListItems.
   */
  data: Prisma.CheckListItemCreateManyInput | Prisma.CheckListItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CheckListItem createManyAndReturn
 */
export type CheckListItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * The data used to create many CheckListItems.
   */
  data: Prisma.CheckListItemCreateManyInput | Prisma.CheckListItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CheckListItem update
 */
export type CheckListItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  /**
   * The data needed to update a CheckListItem.
   */
  data: Prisma.XOR<Prisma.CheckListItemUpdateInput, Prisma.CheckListItemUncheckedUpdateInput>
  /**
   * Choose, which CheckListItem to update.
   */
  where: Prisma.CheckListItemWhereUniqueInput
}

/**
 * CheckListItem updateMany
 */
export type CheckListItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CheckListItems.
   */
  data: Prisma.XOR<Prisma.CheckListItemUpdateManyMutationInput, Prisma.CheckListItemUncheckedUpdateManyInput>
  /**
   * Filter which CheckListItems to update
   */
  where?: Prisma.CheckListItemWhereInput
  /**
   * Limit how many CheckListItems to update.
   */
  limit?: number
}

/**
 * CheckListItem updateManyAndReturn
 */
export type CheckListItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * The data used to update CheckListItems.
   */
  data: Prisma.XOR<Prisma.CheckListItemUpdateManyMutationInput, Prisma.CheckListItemUncheckedUpdateManyInput>
  /**
   * Filter which CheckListItems to update
   */
  where?: Prisma.CheckListItemWhereInput
  /**
   * Limit how many CheckListItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CheckListItem upsert
 */
export type CheckListItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  /**
   * The filter to search for the CheckListItem to update in case it exists.
   */
  where: Prisma.CheckListItemWhereUniqueInput
  /**
   * In case the CheckListItem found by the `where` argument doesn't exist, create a new CheckListItem with this data.
   */
  create: Prisma.XOR<Prisma.CheckListItemCreateInput, Prisma.CheckListItemUncheckedCreateInput>
  /**
   * In case the CheckListItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CheckListItemUpdateInput, Prisma.CheckListItemUncheckedUpdateInput>
}

/**
 * CheckListItem delete
 */
export type CheckListItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  /**
   * Filter which CheckListItem to delete.
   */
  where: Prisma.CheckListItemWhereUniqueInput
}

/**
 * CheckListItem deleteMany
 */
export type CheckListItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CheckListItems to delete
   */
  where?: Prisma.CheckListItemWhereInput
  /**
   * Limit how many CheckListItems to delete.
   */
  limit?: number
}

/**
 * CheckListItem.morning
 */
export type CheckListItem$morningArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  where?: Prisma.CheckListWhereInput
}

/**
 * CheckListItem.evening
 */
export type CheckListItem$eveningArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  where?: Prisma.CheckListWhereInput
}

/**
 * CheckListItem.night
 */
export type CheckListItem$nightArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  where?: Prisma.CheckListWhereInput
}

/**
 * CheckListItem without action
 */
export type CheckListItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
}
