
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CheckList` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CheckList
 * 
 */
export type CheckListModel = runtime.Types.Result.DefaultSelection<Prisma.$CheckListPayload>

export type AggregateCheckList = {
  _count: CheckListCountAggregateOutputType | null
  _min: CheckListMinAggregateOutputType | null
  _max: CheckListMaxAggregateOutputType | null
}

export type CheckListMinAggregateOutputType = {
  id: string | null
  hotelId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CheckListMaxAggregateOutputType = {
  id: string | null
  hotelId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CheckListCountAggregateOutputType = {
  id: number
  hotelId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CheckListMinAggregateInputType = {
  id?: true
  hotelId?: true
  createdAt?: true
  updatedAt?: true
}

export type CheckListMaxAggregateInputType = {
  id?: true
  hotelId?: true
  createdAt?: true
  updatedAt?: true
}

export type CheckListCountAggregateInputType = {
  id?: true
  hotelId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CheckListAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CheckList to aggregate.
   */
  where?: Prisma.CheckListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckLists to fetch.
   */
  orderBy?: Prisma.CheckListOrderByWithRelationInput | Prisma.CheckListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CheckListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CheckLists
  **/
  _count?: true | CheckListCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CheckListMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CheckListMaxAggregateInputType
}

export type GetCheckListAggregateType<T extends CheckListAggregateArgs> = {
      [P in keyof T & keyof AggregateCheckList]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCheckList[P]>
    : Prisma.GetScalarType<T[P], AggregateCheckList[P]>
}




export type CheckListGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckListWhereInput
  orderBy?: Prisma.CheckListOrderByWithAggregationInput | Prisma.CheckListOrderByWithAggregationInput[]
  by: Prisma.CheckListScalarFieldEnum[] | Prisma.CheckListScalarFieldEnum
  having?: Prisma.CheckListScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CheckListCountAggregateInputType | true
  _min?: CheckListMinAggregateInputType
  _max?: CheckListMaxAggregateInputType
}

export type CheckListGroupByOutputType = {
  id: string
  hotelId: string
  createdAt: Date
  updatedAt: Date
  _count: CheckListCountAggregateOutputType | null
  _min: CheckListMinAggregateOutputType | null
  _max: CheckListMaxAggregateOutputType | null
}

export type GetCheckListGroupByPayload<T extends CheckListGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CheckListGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CheckListGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CheckListGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CheckListGroupByOutputType[P]>
      }
    >
  >



export type CheckListWhereInput = {
  AND?: Prisma.CheckListWhereInput | Prisma.CheckListWhereInput[]
  OR?: Prisma.CheckListWhereInput[]
  NOT?: Prisma.CheckListWhereInput | Prisma.CheckListWhereInput[]
  id?: Prisma.StringFilter<"CheckList"> | string
  hotelId?: Prisma.StringFilter<"CheckList"> | string
  createdAt?: Prisma.DateTimeFilter<"CheckList"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CheckList"> | Date | string
  morning?: Prisma.CheckListItemListRelationFilter
  evening?: Prisma.CheckListItemListRelationFilter
  night?: Prisma.CheckListItemListRelationFilter
  hotel?: Prisma.XOR<Prisma.HotelScalarRelationFilter, Prisma.HotelWhereInput>
}

export type CheckListOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  morning?: Prisma.CheckListItemOrderByRelationAggregateInput
  evening?: Prisma.CheckListItemOrderByRelationAggregateInput
  night?: Prisma.CheckListItemOrderByRelationAggregateInput
  hotel?: Prisma.HotelOrderByWithRelationInput
}

export type CheckListWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CheckListWhereInput | Prisma.CheckListWhereInput[]
  OR?: Prisma.CheckListWhereInput[]
  NOT?: Prisma.CheckListWhereInput | Prisma.CheckListWhereInput[]
  hotelId?: Prisma.StringFilter<"CheckList"> | string
  createdAt?: Prisma.DateTimeFilter<"CheckList"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CheckList"> | Date | string
  morning?: Prisma.CheckListItemListRelationFilter
  evening?: Prisma.CheckListItemListRelationFilter
  night?: Prisma.CheckListItemListRelationFilter
  hotel?: Prisma.XOR<Prisma.HotelScalarRelationFilter, Prisma.HotelWhereInput>
}, "id">

export type CheckListOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CheckListCountOrderByAggregateInput
  _max?: Prisma.CheckListMaxOrderByAggregateInput
  _min?: Prisma.CheckListMinOrderByAggregateInput
}

export type CheckListScalarWhereWithAggregatesInput = {
  AND?: Prisma.CheckListScalarWhereWithAggregatesInput | Prisma.CheckListScalarWhereWithAggregatesInput[]
  OR?: Prisma.CheckListScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CheckListScalarWhereWithAggregatesInput | Prisma.CheckListScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CheckList"> | string
  hotelId?: Prisma.StringWithAggregatesFilter<"CheckList"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CheckList"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CheckList"> | Date | string
}

export type CheckListCreateInput = {
  id?: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListItemCreateNestedManyWithoutMorningInput
  evening?: Prisma.CheckListItemCreateNestedManyWithoutEveningInput
  night?: Prisma.CheckListItemCreateNestedManyWithoutNightInput
  hotel: Prisma.HotelCreateNestedOneWithoutCheckListsInput
}

export type CheckListUncheckedCreateInput = {
  id?: string
  hotelId: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutMorningInput
  evening?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutEveningInput
  night?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutNightInput
}

export type CheckListUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListItemUpdateManyWithoutMorningNestedInput
  evening?: Prisma.CheckListItemUpdateManyWithoutEveningNestedInput
  night?: Prisma.CheckListItemUpdateManyWithoutNightNestedInput
  hotel?: Prisma.HotelUpdateOneRequiredWithoutCheckListsNestedInput
}

export type CheckListUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListItemUncheckedUpdateManyWithoutMorningNestedInput
  evening?: Prisma.CheckListItemUncheckedUpdateManyWithoutEveningNestedInput
  night?: Prisma.CheckListItemUncheckedUpdateManyWithoutNightNestedInput
}

export type CheckListCreateManyInput = {
  id?: string
  hotelId: string
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckListListRelationFilter = {
  every?: Prisma.CheckListWhereInput
  some?: Prisma.CheckListWhereInput
  none?: Prisma.CheckListWhereInput
}

export type CheckListOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CheckListCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CheckListMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CheckListMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CheckListNullableScalarRelationFilter = {
  is?: Prisma.CheckListWhereInput | null
  isNot?: Prisma.CheckListWhereInput | null
}

export type CheckListCreateNestedManyWithoutHotelInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutHotelInput, Prisma.CheckListUncheckedCreateWithoutHotelInput> | Prisma.CheckListCreateWithoutHotelInput[] | Prisma.CheckListUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutHotelInput | Prisma.CheckListCreateOrConnectWithoutHotelInput[]
  createMany?: Prisma.CheckListCreateManyHotelInputEnvelope
  connect?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
}

export type CheckListUncheckedCreateNestedManyWithoutHotelInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutHotelInput, Prisma.CheckListUncheckedCreateWithoutHotelInput> | Prisma.CheckListCreateWithoutHotelInput[] | Prisma.CheckListUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutHotelInput | Prisma.CheckListCreateOrConnectWithoutHotelInput[]
  createMany?: Prisma.CheckListCreateManyHotelInputEnvelope
  connect?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
}

export type CheckListUpdateManyWithoutHotelNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutHotelInput, Prisma.CheckListUncheckedCreateWithoutHotelInput> | Prisma.CheckListCreateWithoutHotelInput[] | Prisma.CheckListUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutHotelInput | Prisma.CheckListCreateOrConnectWithoutHotelInput[]
  upsert?: Prisma.CheckListUpsertWithWhereUniqueWithoutHotelInput | Prisma.CheckListUpsertWithWhereUniqueWithoutHotelInput[]
  createMany?: Prisma.CheckListCreateManyHotelInputEnvelope
  set?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
  disconnect?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
  delete?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
  connect?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
  update?: Prisma.CheckListUpdateWithWhereUniqueWithoutHotelInput | Prisma.CheckListUpdateWithWhereUniqueWithoutHotelInput[]
  updateMany?: Prisma.CheckListUpdateManyWithWhereWithoutHotelInput | Prisma.CheckListUpdateManyWithWhereWithoutHotelInput[]
  deleteMany?: Prisma.CheckListScalarWhereInput | Prisma.CheckListScalarWhereInput[]
}

export type CheckListUncheckedUpdateManyWithoutHotelNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutHotelInput, Prisma.CheckListUncheckedCreateWithoutHotelInput> | Prisma.CheckListCreateWithoutHotelInput[] | Prisma.CheckListUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutHotelInput | Prisma.CheckListCreateOrConnectWithoutHotelInput[]
  upsert?: Prisma.CheckListUpsertWithWhereUniqueWithoutHotelInput | Prisma.CheckListUpsertWithWhereUniqueWithoutHotelInput[]
  createMany?: Prisma.CheckListCreateManyHotelInputEnvelope
  set?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
  disconnect?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
  delete?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
  connect?: Prisma.CheckListWhereUniqueInput | Prisma.CheckListWhereUniqueInput[]
  update?: Prisma.CheckListUpdateWithWhereUniqueWithoutHotelInput | Prisma.CheckListUpdateWithWhereUniqueWithoutHotelInput[]
  updateMany?: Prisma.CheckListUpdateManyWithWhereWithoutHotelInput | Prisma.CheckListUpdateManyWithWhereWithoutHotelInput[]
  deleteMany?: Prisma.CheckListScalarWhereInput | Prisma.CheckListScalarWhereInput[]
}

export type CheckListCreateNestedOneWithoutMorningInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutMorningInput, Prisma.CheckListUncheckedCreateWithoutMorningInput>
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutMorningInput
  connect?: Prisma.CheckListWhereUniqueInput
}

export type CheckListCreateNestedOneWithoutEveningInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutEveningInput, Prisma.CheckListUncheckedCreateWithoutEveningInput>
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutEveningInput
  connect?: Prisma.CheckListWhereUniqueInput
}

export type CheckListCreateNestedOneWithoutNightInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutNightInput, Prisma.CheckListUncheckedCreateWithoutNightInput>
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutNightInput
  connect?: Prisma.CheckListWhereUniqueInput
}

export type CheckListUpdateOneWithoutMorningNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutMorningInput, Prisma.CheckListUncheckedCreateWithoutMorningInput>
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutMorningInput
  upsert?: Prisma.CheckListUpsertWithoutMorningInput
  disconnect?: Prisma.CheckListWhereInput | boolean
  delete?: Prisma.CheckListWhereInput | boolean
  connect?: Prisma.CheckListWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CheckListUpdateToOneWithWhereWithoutMorningInput, Prisma.CheckListUpdateWithoutMorningInput>, Prisma.CheckListUncheckedUpdateWithoutMorningInput>
}

export type CheckListUpdateOneWithoutEveningNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutEveningInput, Prisma.CheckListUncheckedCreateWithoutEveningInput>
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutEveningInput
  upsert?: Prisma.CheckListUpsertWithoutEveningInput
  disconnect?: Prisma.CheckListWhereInput | boolean
  delete?: Prisma.CheckListWhereInput | boolean
  connect?: Prisma.CheckListWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CheckListUpdateToOneWithWhereWithoutEveningInput, Prisma.CheckListUpdateWithoutEveningInput>, Prisma.CheckListUncheckedUpdateWithoutEveningInput>
}

export type CheckListUpdateOneWithoutNightNestedInput = {
  create?: Prisma.XOR<Prisma.CheckListCreateWithoutNightInput, Prisma.CheckListUncheckedCreateWithoutNightInput>
  connectOrCreate?: Prisma.CheckListCreateOrConnectWithoutNightInput
  upsert?: Prisma.CheckListUpsertWithoutNightInput
  disconnect?: Prisma.CheckListWhereInput | boolean
  delete?: Prisma.CheckListWhereInput | boolean
  connect?: Prisma.CheckListWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CheckListUpdateToOneWithWhereWithoutNightInput, Prisma.CheckListUpdateWithoutNightInput>, Prisma.CheckListUncheckedUpdateWithoutNightInput>
}

export type CheckListCreateWithoutHotelInput = {
  id?: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListItemCreateNestedManyWithoutMorningInput
  evening?: Prisma.CheckListItemCreateNestedManyWithoutEveningInput
  night?: Prisma.CheckListItemCreateNestedManyWithoutNightInput
}

export type CheckListUncheckedCreateWithoutHotelInput = {
  id?: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutMorningInput
  evening?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutEveningInput
  night?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutNightInput
}

export type CheckListCreateOrConnectWithoutHotelInput = {
  where: Prisma.CheckListWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckListCreateWithoutHotelInput, Prisma.CheckListUncheckedCreateWithoutHotelInput>
}

export type CheckListCreateManyHotelInputEnvelope = {
  data: Prisma.CheckListCreateManyHotelInput | Prisma.CheckListCreateManyHotelInput[]
  skipDuplicates?: boolean
}

export type CheckListUpsertWithWhereUniqueWithoutHotelInput = {
  where: Prisma.CheckListWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckListUpdateWithoutHotelInput, Prisma.CheckListUncheckedUpdateWithoutHotelInput>
  create: Prisma.XOR<Prisma.CheckListCreateWithoutHotelInput, Prisma.CheckListUncheckedCreateWithoutHotelInput>
}

export type CheckListUpdateWithWhereUniqueWithoutHotelInput = {
  where: Prisma.CheckListWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckListUpdateWithoutHotelInput, Prisma.CheckListUncheckedUpdateWithoutHotelInput>
}

export type CheckListUpdateManyWithWhereWithoutHotelInput = {
  where: Prisma.CheckListScalarWhereInput
  data: Prisma.XOR<Prisma.CheckListUpdateManyMutationInput, Prisma.CheckListUncheckedUpdateManyWithoutHotelInput>
}

export type CheckListScalarWhereInput = {
  AND?: Prisma.CheckListScalarWhereInput | Prisma.CheckListScalarWhereInput[]
  OR?: Prisma.CheckListScalarWhereInput[]
  NOT?: Prisma.CheckListScalarWhereInput | Prisma.CheckListScalarWhereInput[]
  id?: Prisma.StringFilter<"CheckList"> | string
  hotelId?: Prisma.StringFilter<"CheckList"> | string
  createdAt?: Prisma.DateTimeFilter<"CheckList"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CheckList"> | Date | string
}

export type CheckListCreateWithoutMorningInput = {
  id?: string
  createdAt: Date | string
  updatedAt: Date | string
  evening?: Prisma.CheckListItemCreateNestedManyWithoutEveningInput
  night?: Prisma.CheckListItemCreateNestedManyWithoutNightInput
  hotel: Prisma.HotelCreateNestedOneWithoutCheckListsInput
}

export type CheckListUncheckedCreateWithoutMorningInput = {
  id?: string
  hotelId: string
  createdAt: Date | string
  updatedAt: Date | string
  evening?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutEveningInput
  night?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutNightInput
}

export type CheckListCreateOrConnectWithoutMorningInput = {
  where: Prisma.CheckListWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckListCreateWithoutMorningInput, Prisma.CheckListUncheckedCreateWithoutMorningInput>
}

export type CheckListCreateWithoutEveningInput = {
  id?: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListItemCreateNestedManyWithoutMorningInput
  night?: Prisma.CheckListItemCreateNestedManyWithoutNightInput
  hotel: Prisma.HotelCreateNestedOneWithoutCheckListsInput
}

export type CheckListUncheckedCreateWithoutEveningInput = {
  id?: string
  hotelId: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutMorningInput
  night?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutNightInput
}

export type CheckListCreateOrConnectWithoutEveningInput = {
  where: Prisma.CheckListWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckListCreateWithoutEveningInput, Prisma.CheckListUncheckedCreateWithoutEveningInput>
}

export type CheckListCreateWithoutNightInput = {
  id?: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListItemCreateNestedManyWithoutMorningInput
  evening?: Prisma.CheckListItemCreateNestedManyWithoutEveningInput
  hotel: Prisma.HotelCreateNestedOneWithoutCheckListsInput
}

export type CheckListUncheckedCreateWithoutNightInput = {
  id?: string
  hotelId: string
  createdAt: Date | string
  updatedAt: Date | string
  morning?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutMorningInput
  evening?: Prisma.CheckListItemUncheckedCreateNestedManyWithoutEveningInput
}

export type CheckListCreateOrConnectWithoutNightInput = {
  where: Prisma.CheckListWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckListCreateWithoutNightInput, Prisma.CheckListUncheckedCreateWithoutNightInput>
}

export type CheckListUpsertWithoutMorningInput = {
  update: Prisma.XOR<Prisma.CheckListUpdateWithoutMorningInput, Prisma.CheckListUncheckedUpdateWithoutMorningInput>
  create: Prisma.XOR<Prisma.CheckListCreateWithoutMorningInput, Prisma.CheckListUncheckedCreateWithoutMorningInput>
  where?: Prisma.CheckListWhereInput
}

export type CheckListUpdateToOneWithWhereWithoutMorningInput = {
  where?: Prisma.CheckListWhereInput
  data: Prisma.XOR<Prisma.CheckListUpdateWithoutMorningInput, Prisma.CheckListUncheckedUpdateWithoutMorningInput>
}

export type CheckListUpdateWithoutMorningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  evening?: Prisma.CheckListItemUpdateManyWithoutEveningNestedInput
  night?: Prisma.CheckListItemUpdateManyWithoutNightNestedInput
  hotel?: Prisma.HotelUpdateOneRequiredWithoutCheckListsNestedInput
}

export type CheckListUncheckedUpdateWithoutMorningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  evening?: Prisma.CheckListItemUncheckedUpdateManyWithoutEveningNestedInput
  night?: Prisma.CheckListItemUncheckedUpdateManyWithoutNightNestedInput
}

export type CheckListUpsertWithoutEveningInput = {
  update: Prisma.XOR<Prisma.CheckListUpdateWithoutEveningInput, Prisma.CheckListUncheckedUpdateWithoutEveningInput>
  create: Prisma.XOR<Prisma.CheckListCreateWithoutEveningInput, Prisma.CheckListUncheckedCreateWithoutEveningInput>
  where?: Prisma.CheckListWhereInput
}

export type CheckListUpdateToOneWithWhereWithoutEveningInput = {
  where?: Prisma.CheckListWhereInput
  data: Prisma.XOR<Prisma.CheckListUpdateWithoutEveningInput, Prisma.CheckListUncheckedUpdateWithoutEveningInput>
}

export type CheckListUpdateWithoutEveningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListItemUpdateManyWithoutMorningNestedInput
  night?: Prisma.CheckListItemUpdateManyWithoutNightNestedInput
  hotel?: Prisma.HotelUpdateOneRequiredWithoutCheckListsNestedInput
}

export type CheckListUncheckedUpdateWithoutEveningInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListItemUncheckedUpdateManyWithoutMorningNestedInput
  night?: Prisma.CheckListItemUncheckedUpdateManyWithoutNightNestedInput
}

export type CheckListUpsertWithoutNightInput = {
  update: Prisma.XOR<Prisma.CheckListUpdateWithoutNightInput, Prisma.CheckListUncheckedUpdateWithoutNightInput>
  create: Prisma.XOR<Prisma.CheckListCreateWithoutNightInput, Prisma.CheckListUncheckedCreateWithoutNightInput>
  where?: Prisma.CheckListWhereInput
}

export type CheckListUpdateToOneWithWhereWithoutNightInput = {
  where?: Prisma.CheckListWhereInput
  data: Prisma.XOR<Prisma.CheckListUpdateWithoutNightInput, Prisma.CheckListUncheckedUpdateWithoutNightInput>
}

export type CheckListUpdateWithoutNightInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListItemUpdateManyWithoutMorningNestedInput
  evening?: Prisma.CheckListItemUpdateManyWithoutEveningNestedInput
  hotel?: Prisma.HotelUpdateOneRequiredWithoutCheckListsNestedInput
}

export type CheckListUncheckedUpdateWithoutNightInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListItemUncheckedUpdateManyWithoutMorningNestedInput
  evening?: Prisma.CheckListItemUncheckedUpdateManyWithoutEveningNestedInput
}

export type CheckListCreateManyHotelInput = {
  id?: string
  createdAt: Date | string
  updatedAt: Date | string
}

export type CheckListUpdateWithoutHotelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListItemUpdateManyWithoutMorningNestedInput
  evening?: Prisma.CheckListItemUpdateManyWithoutEveningNestedInput
  night?: Prisma.CheckListItemUpdateManyWithoutNightNestedInput
}

export type CheckListUncheckedUpdateWithoutHotelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  morning?: Prisma.CheckListItemUncheckedUpdateManyWithoutMorningNestedInput
  evening?: Prisma.CheckListItemUncheckedUpdateManyWithoutEveningNestedInput
  night?: Prisma.CheckListItemUncheckedUpdateManyWithoutNightNestedInput
}

export type CheckListUncheckedUpdateManyWithoutHotelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CheckListCountOutputType
 */

export type CheckListCountOutputType = {
  morning: number
  evening: number
  night: number
}

export type CheckListCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  morning?: boolean | CheckListCountOutputTypeCountMorningArgs
  evening?: boolean | CheckListCountOutputTypeCountEveningArgs
  night?: boolean | CheckListCountOutputTypeCountNightArgs
}

/**
 * CheckListCountOutputType without action
 */
export type CheckListCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListCountOutputType
   */
  select?: Prisma.CheckListCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CheckListCountOutputType without action
 */
export type CheckListCountOutputTypeCountMorningArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckListItemWhereInput
}

/**
 * CheckListCountOutputType without action
 */
export type CheckListCountOutputTypeCountEveningArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckListItemWhereInput
}

/**
 * CheckListCountOutputType without action
 */
export type CheckListCountOutputTypeCountNightArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckListItemWhereInput
}


export type CheckListSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hotelId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  morning?: boolean | Prisma.CheckList$morningArgs<ExtArgs>
  evening?: boolean | Prisma.CheckList$eveningArgs<ExtArgs>
  night?: boolean | Prisma.CheckList$nightArgs<ExtArgs>
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.CheckListCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checkList"]>

export type CheckListSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hotelId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checkList"]>

export type CheckListSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hotelId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checkList"]>

export type CheckListSelectScalar = {
  id?: boolean
  hotelId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CheckListOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "hotelId" | "createdAt" | "updatedAt", ExtArgs["result"]["checkList"]>
export type CheckListInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  morning?: boolean | Prisma.CheckList$morningArgs<ExtArgs>
  evening?: boolean | Prisma.CheckList$eveningArgs<ExtArgs>
  night?: boolean | Prisma.CheckList$nightArgs<ExtArgs>
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.CheckListCountOutputTypeDefaultArgs<ExtArgs>
}
export type CheckListIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
}
export type CheckListIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
}

export type $CheckListPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CheckList"
  objects: {
    morning: Prisma.$CheckListItemPayload<ExtArgs>[]
    evening: Prisma.$CheckListItemPayload<ExtArgs>[]
    night: Prisma.$CheckListItemPayload<ExtArgs>[]
    hotel: Prisma.$HotelPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    hotelId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["checkList"]>
  composites: {}
}

export type CheckListGetPayload<S extends boolean | null | undefined | CheckListDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CheckListPayload, S>

export type CheckListCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CheckListFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CheckListCountAggregateInputType | true
  }

export interface CheckListDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CheckList'], meta: { name: 'CheckList' } }
  /**
   * Find zero or one CheckList that matches the filter.
   * @param {CheckListFindUniqueArgs} args - Arguments to find a CheckList
   * @example
   * // Get one CheckList
   * const checkList = await prisma.checkList.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CheckListFindUniqueArgs>(args: Prisma.SelectSubset<T, CheckListFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CheckList that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CheckListFindUniqueOrThrowArgs} args - Arguments to find a CheckList
   * @example
   * // Get one CheckList
   * const checkList = await prisma.checkList.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CheckListFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CheckListFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CheckList that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListFindFirstArgs} args - Arguments to find a CheckList
   * @example
   * // Get one CheckList
   * const checkList = await prisma.checkList.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CheckListFindFirstArgs>(args?: Prisma.SelectSubset<T, CheckListFindFirstArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CheckList that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListFindFirstOrThrowArgs} args - Arguments to find a CheckList
   * @example
   * // Get one CheckList
   * const checkList = await prisma.checkList.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CheckListFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CheckListFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CheckLists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CheckLists
   * const checkLists = await prisma.checkList.findMany()
   * 
   * // Get first 10 CheckLists
   * const checkLists = await prisma.checkList.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const checkListWithIdOnly = await prisma.checkList.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CheckListFindManyArgs>(args?: Prisma.SelectSubset<T, CheckListFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CheckList.
   * @param {CheckListCreateArgs} args - Arguments to create a CheckList.
   * @example
   * // Create one CheckList
   * const CheckList = await prisma.checkList.create({
   *   data: {
   *     // ... data to create a CheckList
   *   }
   * })
   * 
   */
  create<T extends CheckListCreateArgs>(args: Prisma.SelectSubset<T, CheckListCreateArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CheckLists.
   * @param {CheckListCreateManyArgs} args - Arguments to create many CheckLists.
   * @example
   * // Create many CheckLists
   * const checkList = await prisma.checkList.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CheckListCreateManyArgs>(args?: Prisma.SelectSubset<T, CheckListCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CheckLists and returns the data saved in the database.
   * @param {CheckListCreateManyAndReturnArgs} args - Arguments to create many CheckLists.
   * @example
   * // Create many CheckLists
   * const checkList = await prisma.checkList.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CheckLists and only return the `id`
   * const checkListWithIdOnly = await prisma.checkList.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CheckListCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CheckListCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CheckList.
   * @param {CheckListDeleteArgs} args - Arguments to delete one CheckList.
   * @example
   * // Delete one CheckList
   * const CheckList = await prisma.checkList.delete({
   *   where: {
   *     // ... filter to delete one CheckList
   *   }
   * })
   * 
   */
  delete<T extends CheckListDeleteArgs>(args: Prisma.SelectSubset<T, CheckListDeleteArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CheckList.
   * @param {CheckListUpdateArgs} args - Arguments to update one CheckList.
   * @example
   * // Update one CheckList
   * const checkList = await prisma.checkList.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CheckListUpdateArgs>(args: Prisma.SelectSubset<T, CheckListUpdateArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CheckLists.
   * @param {CheckListDeleteManyArgs} args - Arguments to filter CheckLists to delete.
   * @example
   * // Delete a few CheckLists
   * const { count } = await prisma.checkList.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CheckListDeleteManyArgs>(args?: Prisma.SelectSubset<T, CheckListDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CheckLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CheckLists
   * const checkList = await prisma.checkList.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CheckListUpdateManyArgs>(args: Prisma.SelectSubset<T, CheckListUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CheckLists and returns the data updated in the database.
   * @param {CheckListUpdateManyAndReturnArgs} args - Arguments to update many CheckLists.
   * @example
   * // Update many CheckLists
   * const checkList = await prisma.checkList.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CheckLists and only return the `id`
   * const checkListWithIdOnly = await prisma.checkList.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CheckListUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CheckListUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CheckList.
   * @param {CheckListUpsertArgs} args - Arguments to update or create a CheckList.
   * @example
   * // Update or create a CheckList
   * const checkList = await prisma.checkList.upsert({
   *   create: {
   *     // ... data to create a CheckList
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CheckList we want to update
   *   }
   * })
   */
  upsert<T extends CheckListUpsertArgs>(args: Prisma.SelectSubset<T, CheckListUpsertArgs<ExtArgs>>): Prisma.Prisma__CheckListClient<runtime.Types.Result.GetResult<Prisma.$CheckListPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CheckLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListCountArgs} args - Arguments to filter CheckLists to count.
   * @example
   * // Count the number of CheckLists
   * const count = await prisma.checkList.count({
   *   where: {
   *     // ... the filter for the CheckLists we want to count
   *   }
   * })
  **/
  count<T extends CheckListCountArgs>(
    args?: Prisma.Subset<T, CheckListCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CheckListCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CheckList.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CheckListAggregateArgs>(args: Prisma.Subset<T, CheckListAggregateArgs>): Prisma.PrismaPromise<GetCheckListAggregateType<T>>

  /**
   * Group by CheckList.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckListGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CheckListGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CheckListGroupByArgs['orderBy'] }
      : { orderBy?: CheckListGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CheckListGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCheckListGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CheckList model
 */
readonly fields: CheckListFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CheckList.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CheckListClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  morning<T extends Prisma.CheckList$morningArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CheckList$morningArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  evening<T extends Prisma.CheckList$eveningArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CheckList$eveningArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  night<T extends Prisma.CheckList$nightArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CheckList$nightArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckListItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  hotel<T extends Prisma.HotelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HotelDefaultArgs<ExtArgs>>): Prisma.Prisma__HotelClient<runtime.Types.Result.GetResult<Prisma.$HotelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CheckList model
 */
export interface CheckListFieldRefs {
  readonly id: Prisma.FieldRef<"CheckList", 'String'>
  readonly hotelId: Prisma.FieldRef<"CheckList", 'String'>
  readonly createdAt: Prisma.FieldRef<"CheckList", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CheckList", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CheckList findUnique
 */
export type CheckListFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  /**
   * Filter, which CheckList to fetch.
   */
  where: Prisma.CheckListWhereUniqueInput
}

/**
 * CheckList findUniqueOrThrow
 */
export type CheckListFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  /**
   * Filter, which CheckList to fetch.
   */
  where: Prisma.CheckListWhereUniqueInput
}

/**
 * CheckList findFirst
 */
export type CheckListFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  /**
   * Filter, which CheckList to fetch.
   */
  where?: Prisma.CheckListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckLists to fetch.
   */
  orderBy?: Prisma.CheckListOrderByWithRelationInput | Prisma.CheckListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CheckLists.
   */
  cursor?: Prisma.CheckListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CheckLists.
   */
  distinct?: Prisma.CheckListScalarFieldEnum | Prisma.CheckListScalarFieldEnum[]
}

/**
 * CheckList findFirstOrThrow
 */
export type CheckListFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  /**
   * Filter, which CheckList to fetch.
   */
  where?: Prisma.CheckListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckLists to fetch.
   */
  orderBy?: Prisma.CheckListOrderByWithRelationInput | Prisma.CheckListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CheckLists.
   */
  cursor?: Prisma.CheckListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CheckLists.
   */
  distinct?: Prisma.CheckListScalarFieldEnum | Prisma.CheckListScalarFieldEnum[]
}

/**
 * CheckList findMany
 */
export type CheckListFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  /**
   * Filter, which CheckLists to fetch.
   */
  where?: Prisma.CheckListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckLists to fetch.
   */
  orderBy?: Prisma.CheckListOrderByWithRelationInput | Prisma.CheckListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CheckLists.
   */
  cursor?: Prisma.CheckListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CheckLists.
   */
  distinct?: Prisma.CheckListScalarFieldEnum | Prisma.CheckListScalarFieldEnum[]
}

/**
 * CheckList create
 */
export type CheckListCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  /**
   * The data needed to create a CheckList.
   */
  data: Prisma.XOR<Prisma.CheckListCreateInput, Prisma.CheckListUncheckedCreateInput>
}

/**
 * CheckList createMany
 */
export type CheckListCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CheckLists.
   */
  data: Prisma.CheckListCreateManyInput | Prisma.CheckListCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CheckList createManyAndReturn
 */
export type CheckListCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * The data used to create many CheckLists.
   */
  data: Prisma.CheckListCreateManyInput | Prisma.CheckListCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CheckList update
 */
export type CheckListUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  /**
   * The data needed to update a CheckList.
   */
  data: Prisma.XOR<Prisma.CheckListUpdateInput, Prisma.CheckListUncheckedUpdateInput>
  /**
   * Choose, which CheckList to update.
   */
  where: Prisma.CheckListWhereUniqueInput
}

/**
 * CheckList updateMany
 */
export type CheckListUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CheckLists.
   */
  data: Prisma.XOR<Prisma.CheckListUpdateManyMutationInput, Prisma.CheckListUncheckedUpdateManyInput>
  /**
   * Filter which CheckLists to update
   */
  where?: Prisma.CheckListWhereInput
  /**
   * Limit how many CheckLists to update.
   */
  limit?: number
}

/**
 * CheckList updateManyAndReturn
 */
export type CheckListUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * The data used to update CheckLists.
   */
  data: Prisma.XOR<Prisma.CheckListUpdateManyMutationInput, Prisma.CheckListUncheckedUpdateManyInput>
  /**
   * Filter which CheckLists to update
   */
  where?: Prisma.CheckListWhereInput
  /**
   * Limit how many CheckLists to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CheckList upsert
 */
export type CheckListUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  /**
   * The filter to search for the CheckList to update in case it exists.
   */
  where: Prisma.CheckListWhereUniqueInput
  /**
   * In case the CheckList found by the `where` argument doesn't exist, create a new CheckList with this data.
   */
  create: Prisma.XOR<Prisma.CheckListCreateInput, Prisma.CheckListUncheckedCreateInput>
  /**
   * In case the CheckList was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CheckListUpdateInput, Prisma.CheckListUncheckedUpdateInput>
}

/**
 * CheckList delete
 */
export type CheckListDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
  /**
   * Filter which CheckList to delete.
   */
  where: Prisma.CheckListWhereUniqueInput
}

/**
 * CheckList deleteMany
 */
export type CheckListDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CheckLists to delete
   */
  where?: Prisma.CheckListWhereInput
  /**
   * Limit how many CheckLists to delete.
   */
  limit?: number
}

/**
 * CheckList.morning
 */
export type CheckList$morningArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  where?: Prisma.CheckListItemWhereInput
  orderBy?: Prisma.CheckListItemOrderByWithRelationInput | Prisma.CheckListItemOrderByWithRelationInput[]
  cursor?: Prisma.CheckListItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CheckListItemScalarFieldEnum | Prisma.CheckListItemScalarFieldEnum[]
}

/**
 * CheckList.evening
 */
export type CheckList$eveningArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  where?: Prisma.CheckListItemWhereInput
  orderBy?: Prisma.CheckListItemOrderByWithRelationInput | Prisma.CheckListItemOrderByWithRelationInput[]
  cursor?: Prisma.CheckListItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CheckListItemScalarFieldEnum | Prisma.CheckListItemScalarFieldEnum[]
}

/**
 * CheckList.night
 */
export type CheckList$nightArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckListItem
   */
  select?: Prisma.CheckListItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckListItem
   */
  omit?: Prisma.CheckListItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListItemInclude<ExtArgs> | null
  where?: Prisma.CheckListItemWhereInput
  orderBy?: Prisma.CheckListItemOrderByWithRelationInput | Prisma.CheckListItemOrderByWithRelationInput[]
  cursor?: Prisma.CheckListItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CheckListItemScalarFieldEnum | Prisma.CheckListItemScalarFieldEnum[]
}

/**
 * CheckList without action
 */
export type CheckListDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckList
   */
  select?: Prisma.CheckListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckList
   */
  omit?: Prisma.CheckListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckListInclude<ExtArgs> | null
}
