
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FeedbackItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model FeedbackItem
 * 
 */
export type FeedbackItemModel = runtime.Types.Result.DefaultSelection<Prisma.$FeedbackItemPayload>

export type AggregateFeedbackItem = {
  _count: FeedbackItemCountAggregateOutputType | null
  _min: FeedbackItemMinAggregateOutputType | null
  _max: FeedbackItemMaxAggregateOutputType | null
}

export type FeedbackItemMinAggregateOutputType = {
  id: string | null
  author: string | null
  text: string | null
  hotelDept: string | null
  hotelName: string | null
  hotelRegion: string | null
  satisfactionFeedbackId: string | null
  improvementFeedbackId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FeedbackItemMaxAggregateOutputType = {
  id: string | null
  author: string | null
  text: string | null
  hotelDept: string | null
  hotelName: string | null
  hotelRegion: string | null
  satisfactionFeedbackId: string | null
  improvementFeedbackId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FeedbackItemCountAggregateOutputType = {
  id: number
  author: number
  text: number
  hotelDept: number
  hotelName: number
  hotelRegion: number
  satisfactionFeedbackId: number
  improvementFeedbackId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FeedbackItemMinAggregateInputType = {
  id?: true
  author?: true
  text?: true
  hotelDept?: true
  hotelName?: true
  hotelRegion?: true
  satisfactionFeedbackId?: true
  improvementFeedbackId?: true
  createdAt?: true
  updatedAt?: true
}

export type FeedbackItemMaxAggregateInputType = {
  id?: true
  author?: true
  text?: true
  hotelDept?: true
  hotelName?: true
  hotelRegion?: true
  satisfactionFeedbackId?: true
  improvementFeedbackId?: true
  createdAt?: true
  updatedAt?: true
}

export type FeedbackItemCountAggregateInputType = {
  id?: true
  author?: true
  text?: true
  hotelDept?: true
  hotelName?: true
  hotelRegion?: true
  satisfactionFeedbackId?: true
  improvementFeedbackId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FeedbackItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeedbackItem to aggregate.
   */
  where?: Prisma.FeedbackItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedbackItems to fetch.
   */
  orderBy?: Prisma.FeedbackItemOrderByWithRelationInput | Prisma.FeedbackItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FeedbackItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedbackItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedbackItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FeedbackItems
  **/
  _count?: true | FeedbackItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FeedbackItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FeedbackItemMaxAggregateInputType
}

export type GetFeedbackItemAggregateType<T extends FeedbackItemAggregateArgs> = {
      [P in keyof T & keyof AggregateFeedbackItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFeedbackItem[P]>
    : Prisma.GetScalarType<T[P], AggregateFeedbackItem[P]>
}




export type FeedbackItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FeedbackItemWhereInput
  orderBy?: Prisma.FeedbackItemOrderByWithAggregationInput | Prisma.FeedbackItemOrderByWithAggregationInput[]
  by: Prisma.FeedbackItemScalarFieldEnum[] | Prisma.FeedbackItemScalarFieldEnum
  having?: Prisma.FeedbackItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FeedbackItemCountAggregateInputType | true
  _min?: FeedbackItemMinAggregateInputType
  _max?: FeedbackItemMaxAggregateInputType
}

export type FeedbackItemGroupByOutputType = {
  id: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  satisfactionFeedbackId: string | null
  improvementFeedbackId: string | null
  createdAt: Date
  updatedAt: Date
  _count: FeedbackItemCountAggregateOutputType | null
  _min: FeedbackItemMinAggregateOutputType | null
  _max: FeedbackItemMaxAggregateOutputType | null
}

export type GetFeedbackItemGroupByPayload<T extends FeedbackItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FeedbackItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FeedbackItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FeedbackItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FeedbackItemGroupByOutputType[P]>
      }
    >
  >



export type FeedbackItemWhereInput = {
  AND?: Prisma.FeedbackItemWhereInput | Prisma.FeedbackItemWhereInput[]
  OR?: Prisma.FeedbackItemWhereInput[]
  NOT?: Prisma.FeedbackItemWhereInput | Prisma.FeedbackItemWhereInput[]
  id?: Prisma.StringFilter<"FeedbackItem"> | string
  author?: Prisma.StringFilter<"FeedbackItem"> | string
  text?: Prisma.StringFilter<"FeedbackItem"> | string
  hotelDept?: Prisma.StringFilter<"FeedbackItem"> | string
  hotelName?: Prisma.StringFilter<"FeedbackItem"> | string
  hotelRegion?: Prisma.StringFilter<"FeedbackItem"> | string
  satisfactionFeedbackId?: Prisma.StringNullableFilter<"FeedbackItem"> | string | null
  improvementFeedbackId?: Prisma.StringNullableFilter<"FeedbackItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FeedbackItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FeedbackItem"> | Date | string
  satisfactionFeedback?: Prisma.XOR<Prisma.FeedbackNullableScalarRelationFilter, Prisma.FeedbackWhereInput> | null
  improvementFeedback?: Prisma.XOR<Prisma.FeedbackNullableScalarRelationFilter, Prisma.FeedbackWhereInput> | null
}

export type FeedbackItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  author?: Prisma.SortOrder
  text?: Prisma.SortOrder
  hotelDept?: Prisma.SortOrder
  hotelName?: Prisma.SortOrder
  hotelRegion?: Prisma.SortOrder
  satisfactionFeedbackId?: Prisma.SortOrderInput | Prisma.SortOrder
  improvementFeedbackId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  satisfactionFeedback?: Prisma.FeedbackOrderByWithRelationInput
  improvementFeedback?: Prisma.FeedbackOrderByWithRelationInput
}

export type FeedbackItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FeedbackItemWhereInput | Prisma.FeedbackItemWhereInput[]
  OR?: Prisma.FeedbackItemWhereInput[]
  NOT?: Prisma.FeedbackItemWhereInput | Prisma.FeedbackItemWhereInput[]
  author?: Prisma.StringFilter<"FeedbackItem"> | string
  text?: Prisma.StringFilter<"FeedbackItem"> | string
  hotelDept?: Prisma.StringFilter<"FeedbackItem"> | string
  hotelName?: Prisma.StringFilter<"FeedbackItem"> | string
  hotelRegion?: Prisma.StringFilter<"FeedbackItem"> | string
  satisfactionFeedbackId?: Prisma.StringNullableFilter<"FeedbackItem"> | string | null
  improvementFeedbackId?: Prisma.StringNullableFilter<"FeedbackItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FeedbackItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FeedbackItem"> | Date | string
  satisfactionFeedback?: Prisma.XOR<Prisma.FeedbackNullableScalarRelationFilter, Prisma.FeedbackWhereInput> | null
  improvementFeedback?: Prisma.XOR<Prisma.FeedbackNullableScalarRelationFilter, Prisma.FeedbackWhereInput> | null
}, "id">

export type FeedbackItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  author?: Prisma.SortOrder
  text?: Prisma.SortOrder
  hotelDept?: Prisma.SortOrder
  hotelName?: Prisma.SortOrder
  hotelRegion?: Prisma.SortOrder
  satisfactionFeedbackId?: Prisma.SortOrderInput | Prisma.SortOrder
  improvementFeedbackId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FeedbackItemCountOrderByAggregateInput
  _max?: Prisma.FeedbackItemMaxOrderByAggregateInput
  _min?: Prisma.FeedbackItemMinOrderByAggregateInput
}

export type FeedbackItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.FeedbackItemScalarWhereWithAggregatesInput | Prisma.FeedbackItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.FeedbackItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FeedbackItemScalarWhereWithAggregatesInput | Prisma.FeedbackItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FeedbackItem"> | string
  author?: Prisma.StringWithAggregatesFilter<"FeedbackItem"> | string
  text?: Prisma.StringWithAggregatesFilter<"FeedbackItem"> | string
  hotelDept?: Prisma.StringWithAggregatesFilter<"FeedbackItem"> | string
  hotelName?: Prisma.StringWithAggregatesFilter<"FeedbackItem"> | string
  hotelRegion?: Prisma.StringWithAggregatesFilter<"FeedbackItem"> | string
  satisfactionFeedbackId?: Prisma.StringNullableWithAggregatesFilter<"FeedbackItem"> | string | null
  improvementFeedbackId?: Prisma.StringNullableWithAggregatesFilter<"FeedbackItem"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FeedbackItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FeedbackItem"> | Date | string
}

export type FeedbackItemCreateInput = {
  id?: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  createdAt: Date | string
  updatedAt: Date | string
  satisfactionFeedback?: Prisma.FeedbackCreateNestedOneWithoutSatisfactionInput
  improvementFeedback?: Prisma.FeedbackCreateNestedOneWithoutImprovementInput
}

export type FeedbackItemUncheckedCreateInput = {
  id?: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  satisfactionFeedbackId?: string | null
  improvementFeedbackId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type FeedbackItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  satisfactionFeedback?: Prisma.FeedbackUpdateOneWithoutSatisfactionNestedInput
  improvementFeedback?: Prisma.FeedbackUpdateOneWithoutImprovementNestedInput
}

export type FeedbackItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  satisfactionFeedbackId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  improvementFeedbackId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackItemCreateManyInput = {
  id?: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  satisfactionFeedbackId?: string | null
  improvementFeedbackId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type FeedbackItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  satisfactionFeedbackId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  improvementFeedbackId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackItemListRelationFilter = {
  every?: Prisma.FeedbackItemWhereInput
  some?: Prisma.FeedbackItemWhereInput
  none?: Prisma.FeedbackItemWhereInput
}

export type FeedbackItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FeedbackItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  author?: Prisma.SortOrder
  text?: Prisma.SortOrder
  hotelDept?: Prisma.SortOrder
  hotelName?: Prisma.SortOrder
  hotelRegion?: Prisma.SortOrder
  satisfactionFeedbackId?: Prisma.SortOrder
  improvementFeedbackId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FeedbackItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  author?: Prisma.SortOrder
  text?: Prisma.SortOrder
  hotelDept?: Prisma.SortOrder
  hotelName?: Prisma.SortOrder
  hotelRegion?: Prisma.SortOrder
  satisfactionFeedbackId?: Prisma.SortOrder
  improvementFeedbackId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FeedbackItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  author?: Prisma.SortOrder
  text?: Prisma.SortOrder
  hotelDept?: Prisma.SortOrder
  hotelName?: Prisma.SortOrder
  hotelRegion?: Prisma.SortOrder
  satisfactionFeedbackId?: Prisma.SortOrder
  improvementFeedbackId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FeedbackItemCreateNestedManyWithoutSatisfactionFeedbackInput = {
  create?: Prisma.XOR<Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput> | Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput[] | Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput[]
  connectOrCreate?: Prisma.FeedbackItemCreateOrConnectWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemCreateOrConnectWithoutSatisfactionFeedbackInput[]
  createMany?: Prisma.FeedbackItemCreateManySatisfactionFeedbackInputEnvelope
  connect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
}

export type FeedbackItemCreateNestedManyWithoutImprovementFeedbackInput = {
  create?: Prisma.XOR<Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput> | Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput[] | Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput[]
  connectOrCreate?: Prisma.FeedbackItemCreateOrConnectWithoutImprovementFeedbackInput | Prisma.FeedbackItemCreateOrConnectWithoutImprovementFeedbackInput[]
  createMany?: Prisma.FeedbackItemCreateManyImprovementFeedbackInputEnvelope
  connect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
}

export type FeedbackItemUncheckedCreateNestedManyWithoutSatisfactionFeedbackInput = {
  create?: Prisma.XOR<Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput> | Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput[] | Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput[]
  connectOrCreate?: Prisma.FeedbackItemCreateOrConnectWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemCreateOrConnectWithoutSatisfactionFeedbackInput[]
  createMany?: Prisma.FeedbackItemCreateManySatisfactionFeedbackInputEnvelope
  connect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
}

export type FeedbackItemUncheckedCreateNestedManyWithoutImprovementFeedbackInput = {
  create?: Prisma.XOR<Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput> | Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput[] | Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput[]
  connectOrCreate?: Prisma.FeedbackItemCreateOrConnectWithoutImprovementFeedbackInput | Prisma.FeedbackItemCreateOrConnectWithoutImprovementFeedbackInput[]
  createMany?: Prisma.FeedbackItemCreateManyImprovementFeedbackInputEnvelope
  connect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
}

export type FeedbackItemUpdateManyWithoutSatisfactionFeedbackNestedInput = {
  create?: Prisma.XOR<Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput> | Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput[] | Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput[]
  connectOrCreate?: Prisma.FeedbackItemCreateOrConnectWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemCreateOrConnectWithoutSatisfactionFeedbackInput[]
  upsert?: Prisma.FeedbackItemUpsertWithWhereUniqueWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemUpsertWithWhereUniqueWithoutSatisfactionFeedbackInput[]
  createMany?: Prisma.FeedbackItemCreateManySatisfactionFeedbackInputEnvelope
  set?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  disconnect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  delete?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  connect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  update?: Prisma.FeedbackItemUpdateWithWhereUniqueWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemUpdateWithWhereUniqueWithoutSatisfactionFeedbackInput[]
  updateMany?: Prisma.FeedbackItemUpdateManyWithWhereWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemUpdateManyWithWhereWithoutSatisfactionFeedbackInput[]
  deleteMany?: Prisma.FeedbackItemScalarWhereInput | Prisma.FeedbackItemScalarWhereInput[]
}

export type FeedbackItemUpdateManyWithoutImprovementFeedbackNestedInput = {
  create?: Prisma.XOR<Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput> | Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput[] | Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput[]
  connectOrCreate?: Prisma.FeedbackItemCreateOrConnectWithoutImprovementFeedbackInput | Prisma.FeedbackItemCreateOrConnectWithoutImprovementFeedbackInput[]
  upsert?: Prisma.FeedbackItemUpsertWithWhereUniqueWithoutImprovementFeedbackInput | Prisma.FeedbackItemUpsertWithWhereUniqueWithoutImprovementFeedbackInput[]
  createMany?: Prisma.FeedbackItemCreateManyImprovementFeedbackInputEnvelope
  set?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  disconnect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  delete?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  connect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  update?: Prisma.FeedbackItemUpdateWithWhereUniqueWithoutImprovementFeedbackInput | Prisma.FeedbackItemUpdateWithWhereUniqueWithoutImprovementFeedbackInput[]
  updateMany?: Prisma.FeedbackItemUpdateManyWithWhereWithoutImprovementFeedbackInput | Prisma.FeedbackItemUpdateManyWithWhereWithoutImprovementFeedbackInput[]
  deleteMany?: Prisma.FeedbackItemScalarWhereInput | Prisma.FeedbackItemScalarWhereInput[]
}

export type FeedbackItemUncheckedUpdateManyWithoutSatisfactionFeedbackNestedInput = {
  create?: Prisma.XOR<Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput> | Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput[] | Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput[]
  connectOrCreate?: Prisma.FeedbackItemCreateOrConnectWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemCreateOrConnectWithoutSatisfactionFeedbackInput[]
  upsert?: Prisma.FeedbackItemUpsertWithWhereUniqueWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemUpsertWithWhereUniqueWithoutSatisfactionFeedbackInput[]
  createMany?: Prisma.FeedbackItemCreateManySatisfactionFeedbackInputEnvelope
  set?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  disconnect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  delete?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  connect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  update?: Prisma.FeedbackItemUpdateWithWhereUniqueWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemUpdateWithWhereUniqueWithoutSatisfactionFeedbackInput[]
  updateMany?: Prisma.FeedbackItemUpdateManyWithWhereWithoutSatisfactionFeedbackInput | Prisma.FeedbackItemUpdateManyWithWhereWithoutSatisfactionFeedbackInput[]
  deleteMany?: Prisma.FeedbackItemScalarWhereInput | Prisma.FeedbackItemScalarWhereInput[]
}

export type FeedbackItemUncheckedUpdateManyWithoutImprovementFeedbackNestedInput = {
  create?: Prisma.XOR<Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput> | Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput[] | Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput[]
  connectOrCreate?: Prisma.FeedbackItemCreateOrConnectWithoutImprovementFeedbackInput | Prisma.FeedbackItemCreateOrConnectWithoutImprovementFeedbackInput[]
  upsert?: Prisma.FeedbackItemUpsertWithWhereUniqueWithoutImprovementFeedbackInput | Prisma.FeedbackItemUpsertWithWhereUniqueWithoutImprovementFeedbackInput[]
  createMany?: Prisma.FeedbackItemCreateManyImprovementFeedbackInputEnvelope
  set?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  disconnect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  delete?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  connect?: Prisma.FeedbackItemWhereUniqueInput | Prisma.FeedbackItemWhereUniqueInput[]
  update?: Prisma.FeedbackItemUpdateWithWhereUniqueWithoutImprovementFeedbackInput | Prisma.FeedbackItemUpdateWithWhereUniqueWithoutImprovementFeedbackInput[]
  updateMany?: Prisma.FeedbackItemUpdateManyWithWhereWithoutImprovementFeedbackInput | Prisma.FeedbackItemUpdateManyWithWhereWithoutImprovementFeedbackInput[]
  deleteMany?: Prisma.FeedbackItemScalarWhereInput | Prisma.FeedbackItemScalarWhereInput[]
}

export type FeedbackItemCreateWithoutSatisfactionFeedbackInput = {
  id?: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  createdAt: Date | string
  updatedAt: Date | string
  improvementFeedback?: Prisma.FeedbackCreateNestedOneWithoutImprovementInput
}

export type FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput = {
  id?: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  improvementFeedbackId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type FeedbackItemCreateOrConnectWithoutSatisfactionFeedbackInput = {
  where: Prisma.FeedbackItemWhereUniqueInput
  create: Prisma.XOR<Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput>
}

export type FeedbackItemCreateManySatisfactionFeedbackInputEnvelope = {
  data: Prisma.FeedbackItemCreateManySatisfactionFeedbackInput | Prisma.FeedbackItemCreateManySatisfactionFeedbackInput[]
  skipDuplicates?: boolean
}

export type FeedbackItemCreateWithoutImprovementFeedbackInput = {
  id?: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  createdAt: Date | string
  updatedAt: Date | string
  satisfactionFeedback?: Prisma.FeedbackCreateNestedOneWithoutSatisfactionInput
}

export type FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput = {
  id?: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  satisfactionFeedbackId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type FeedbackItemCreateOrConnectWithoutImprovementFeedbackInput = {
  where: Prisma.FeedbackItemWhereUniqueInput
  create: Prisma.XOR<Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput>
}

export type FeedbackItemCreateManyImprovementFeedbackInputEnvelope = {
  data: Prisma.FeedbackItemCreateManyImprovementFeedbackInput | Prisma.FeedbackItemCreateManyImprovementFeedbackInput[]
  skipDuplicates?: boolean
}

export type FeedbackItemUpsertWithWhereUniqueWithoutSatisfactionFeedbackInput = {
  where: Prisma.FeedbackItemWhereUniqueInput
  update: Prisma.XOR<Prisma.FeedbackItemUpdateWithoutSatisfactionFeedbackInput, Prisma.FeedbackItemUncheckedUpdateWithoutSatisfactionFeedbackInput>
  create: Prisma.XOR<Prisma.FeedbackItemCreateWithoutSatisfactionFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutSatisfactionFeedbackInput>
}

export type FeedbackItemUpdateWithWhereUniqueWithoutSatisfactionFeedbackInput = {
  where: Prisma.FeedbackItemWhereUniqueInput
  data: Prisma.XOR<Prisma.FeedbackItemUpdateWithoutSatisfactionFeedbackInput, Prisma.FeedbackItemUncheckedUpdateWithoutSatisfactionFeedbackInput>
}

export type FeedbackItemUpdateManyWithWhereWithoutSatisfactionFeedbackInput = {
  where: Prisma.FeedbackItemScalarWhereInput
  data: Prisma.XOR<Prisma.FeedbackItemUpdateManyMutationInput, Prisma.FeedbackItemUncheckedUpdateManyWithoutSatisfactionFeedbackInput>
}

export type FeedbackItemScalarWhereInput = {
  AND?: Prisma.FeedbackItemScalarWhereInput | Prisma.FeedbackItemScalarWhereInput[]
  OR?: Prisma.FeedbackItemScalarWhereInput[]
  NOT?: Prisma.FeedbackItemScalarWhereInput | Prisma.FeedbackItemScalarWhereInput[]
  id?: Prisma.StringFilter<"FeedbackItem"> | string
  author?: Prisma.StringFilter<"FeedbackItem"> | string
  text?: Prisma.StringFilter<"FeedbackItem"> | string
  hotelDept?: Prisma.StringFilter<"FeedbackItem"> | string
  hotelName?: Prisma.StringFilter<"FeedbackItem"> | string
  hotelRegion?: Prisma.StringFilter<"FeedbackItem"> | string
  satisfactionFeedbackId?: Prisma.StringNullableFilter<"FeedbackItem"> | string | null
  improvementFeedbackId?: Prisma.StringNullableFilter<"FeedbackItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FeedbackItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FeedbackItem"> | Date | string
}

export type FeedbackItemUpsertWithWhereUniqueWithoutImprovementFeedbackInput = {
  where: Prisma.FeedbackItemWhereUniqueInput
  update: Prisma.XOR<Prisma.FeedbackItemUpdateWithoutImprovementFeedbackInput, Prisma.FeedbackItemUncheckedUpdateWithoutImprovementFeedbackInput>
  create: Prisma.XOR<Prisma.FeedbackItemCreateWithoutImprovementFeedbackInput, Prisma.FeedbackItemUncheckedCreateWithoutImprovementFeedbackInput>
}

export type FeedbackItemUpdateWithWhereUniqueWithoutImprovementFeedbackInput = {
  where: Prisma.FeedbackItemWhereUniqueInput
  data: Prisma.XOR<Prisma.FeedbackItemUpdateWithoutImprovementFeedbackInput, Prisma.FeedbackItemUncheckedUpdateWithoutImprovementFeedbackInput>
}

export type FeedbackItemUpdateManyWithWhereWithoutImprovementFeedbackInput = {
  where: Prisma.FeedbackItemScalarWhereInput
  data: Prisma.XOR<Prisma.FeedbackItemUpdateManyMutationInput, Prisma.FeedbackItemUncheckedUpdateManyWithoutImprovementFeedbackInput>
}

export type FeedbackItemCreateManySatisfactionFeedbackInput = {
  id?: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  improvementFeedbackId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type FeedbackItemCreateManyImprovementFeedbackInput = {
  id?: string
  author: string
  text: string
  hotelDept: string
  hotelName: string
  hotelRegion: string
  satisfactionFeedbackId?: string | null
  createdAt: Date | string
  updatedAt: Date | string
}

export type FeedbackItemUpdateWithoutSatisfactionFeedbackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  improvementFeedback?: Prisma.FeedbackUpdateOneWithoutImprovementNestedInput
}

export type FeedbackItemUncheckedUpdateWithoutSatisfactionFeedbackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  improvementFeedbackId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackItemUncheckedUpdateManyWithoutSatisfactionFeedbackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  improvementFeedbackId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackItemUpdateWithoutImprovementFeedbackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  satisfactionFeedback?: Prisma.FeedbackUpdateOneWithoutSatisfactionNestedInput
}

export type FeedbackItemUncheckedUpdateWithoutImprovementFeedbackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  satisfactionFeedbackId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeedbackItemUncheckedUpdateManyWithoutImprovementFeedbackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  hotelDept?: Prisma.StringFieldUpdateOperationsInput | string
  hotelName?: Prisma.StringFieldUpdateOperationsInput | string
  hotelRegion?: Prisma.StringFieldUpdateOperationsInput | string
  satisfactionFeedbackId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FeedbackItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  author?: boolean
  text?: boolean
  hotelDept?: boolean
  hotelName?: boolean
  hotelRegion?: boolean
  satisfactionFeedbackId?: boolean
  improvementFeedbackId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  satisfactionFeedback?: boolean | Prisma.FeedbackItem$satisfactionFeedbackArgs<ExtArgs>
  improvementFeedback?: boolean | Prisma.FeedbackItem$improvementFeedbackArgs<ExtArgs>
}, ExtArgs["result"]["feedbackItem"]>

export type FeedbackItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  author?: boolean
  text?: boolean
  hotelDept?: boolean
  hotelName?: boolean
  hotelRegion?: boolean
  satisfactionFeedbackId?: boolean
  improvementFeedbackId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  satisfactionFeedback?: boolean | Prisma.FeedbackItem$satisfactionFeedbackArgs<ExtArgs>
  improvementFeedback?: boolean | Prisma.FeedbackItem$improvementFeedbackArgs<ExtArgs>
}, ExtArgs["result"]["feedbackItem"]>

export type FeedbackItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  author?: boolean
  text?: boolean
  hotelDept?: boolean
  hotelName?: boolean
  hotelRegion?: boolean
  satisfactionFeedbackId?: boolean
  improvementFeedbackId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  satisfactionFeedback?: boolean | Prisma.FeedbackItem$satisfactionFeedbackArgs<ExtArgs>
  improvementFeedback?: boolean | Prisma.FeedbackItem$improvementFeedbackArgs<ExtArgs>
}, ExtArgs["result"]["feedbackItem"]>

export type FeedbackItemSelectScalar = {
  id?: boolean
  author?: boolean
  text?: boolean
  hotelDept?: boolean
  hotelName?: boolean
  hotelRegion?: boolean
  satisfactionFeedbackId?: boolean
  improvementFeedbackId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FeedbackItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "author" | "text" | "hotelDept" | "hotelName" | "hotelRegion" | "satisfactionFeedbackId" | "improvementFeedbackId" | "createdAt" | "updatedAt", ExtArgs["result"]["feedbackItem"]>
export type FeedbackItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  satisfactionFeedback?: boolean | Prisma.FeedbackItem$satisfactionFeedbackArgs<ExtArgs>
  improvementFeedback?: boolean | Prisma.FeedbackItem$improvementFeedbackArgs<ExtArgs>
}
export type FeedbackItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  satisfactionFeedback?: boolean | Prisma.FeedbackItem$satisfactionFeedbackArgs<ExtArgs>
  improvementFeedback?: boolean | Prisma.FeedbackItem$improvementFeedbackArgs<ExtArgs>
}
export type FeedbackItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  satisfactionFeedback?: boolean | Prisma.FeedbackItem$satisfactionFeedbackArgs<ExtArgs>
  improvementFeedback?: boolean | Prisma.FeedbackItem$improvementFeedbackArgs<ExtArgs>
}

export type $FeedbackItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FeedbackItem"
  objects: {
    satisfactionFeedback: Prisma.$FeedbackPayload<ExtArgs> | null
    improvementFeedback: Prisma.$FeedbackPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    author: string
    text: string
    hotelDept: string
    hotelName: string
    hotelRegion: string
    satisfactionFeedbackId: string | null
    improvementFeedbackId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["feedbackItem"]>
  composites: {}
}

export type FeedbackItemGetPayload<S extends boolean | null | undefined | FeedbackItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload, S>

export type FeedbackItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FeedbackItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FeedbackItemCountAggregateInputType | true
  }

export interface FeedbackItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FeedbackItem'], meta: { name: 'FeedbackItem' } }
  /**
   * Find zero or one FeedbackItem that matches the filter.
   * @param {FeedbackItemFindUniqueArgs} args - Arguments to find a FeedbackItem
   * @example
   * // Get one FeedbackItem
   * const feedbackItem = await prisma.feedbackItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FeedbackItemFindUniqueArgs>(args: Prisma.SelectSubset<T, FeedbackItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FeedbackItemClient<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FeedbackItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FeedbackItemFindUniqueOrThrowArgs} args - Arguments to find a FeedbackItem
   * @example
   * // Get one FeedbackItem
   * const feedbackItem = await prisma.feedbackItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FeedbackItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FeedbackItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeedbackItemClient<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeedbackItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackItemFindFirstArgs} args - Arguments to find a FeedbackItem
   * @example
   * // Get one FeedbackItem
   * const feedbackItem = await prisma.feedbackItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FeedbackItemFindFirstArgs>(args?: Prisma.SelectSubset<T, FeedbackItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__FeedbackItemClient<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeedbackItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackItemFindFirstOrThrowArgs} args - Arguments to find a FeedbackItem
   * @example
   * // Get one FeedbackItem
   * const feedbackItem = await prisma.feedbackItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FeedbackItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FeedbackItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeedbackItemClient<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FeedbackItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FeedbackItems
   * const feedbackItems = await prisma.feedbackItem.findMany()
   * 
   * // Get first 10 FeedbackItems
   * const feedbackItems = await prisma.feedbackItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const feedbackItemWithIdOnly = await prisma.feedbackItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FeedbackItemFindManyArgs>(args?: Prisma.SelectSubset<T, FeedbackItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FeedbackItem.
   * @param {FeedbackItemCreateArgs} args - Arguments to create a FeedbackItem.
   * @example
   * // Create one FeedbackItem
   * const FeedbackItem = await prisma.feedbackItem.create({
   *   data: {
   *     // ... data to create a FeedbackItem
   *   }
   * })
   * 
   */
  create<T extends FeedbackItemCreateArgs>(args: Prisma.SelectSubset<T, FeedbackItemCreateArgs<ExtArgs>>): Prisma.Prisma__FeedbackItemClient<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FeedbackItems.
   * @param {FeedbackItemCreateManyArgs} args - Arguments to create many FeedbackItems.
   * @example
   * // Create many FeedbackItems
   * const feedbackItem = await prisma.feedbackItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FeedbackItemCreateManyArgs>(args?: Prisma.SelectSubset<T, FeedbackItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FeedbackItems and returns the data saved in the database.
   * @param {FeedbackItemCreateManyAndReturnArgs} args - Arguments to create many FeedbackItems.
   * @example
   * // Create many FeedbackItems
   * const feedbackItem = await prisma.feedbackItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FeedbackItems and only return the `id`
   * const feedbackItemWithIdOnly = await prisma.feedbackItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FeedbackItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FeedbackItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FeedbackItem.
   * @param {FeedbackItemDeleteArgs} args - Arguments to delete one FeedbackItem.
   * @example
   * // Delete one FeedbackItem
   * const FeedbackItem = await prisma.feedbackItem.delete({
   *   where: {
   *     // ... filter to delete one FeedbackItem
   *   }
   * })
   * 
   */
  delete<T extends FeedbackItemDeleteArgs>(args: Prisma.SelectSubset<T, FeedbackItemDeleteArgs<ExtArgs>>): Prisma.Prisma__FeedbackItemClient<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FeedbackItem.
   * @param {FeedbackItemUpdateArgs} args - Arguments to update one FeedbackItem.
   * @example
   * // Update one FeedbackItem
   * const feedbackItem = await prisma.feedbackItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FeedbackItemUpdateArgs>(args: Prisma.SelectSubset<T, FeedbackItemUpdateArgs<ExtArgs>>): Prisma.Prisma__FeedbackItemClient<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FeedbackItems.
   * @param {FeedbackItemDeleteManyArgs} args - Arguments to filter FeedbackItems to delete.
   * @example
   * // Delete a few FeedbackItems
   * const { count } = await prisma.feedbackItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FeedbackItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, FeedbackItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeedbackItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FeedbackItems
   * const feedbackItem = await prisma.feedbackItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FeedbackItemUpdateManyArgs>(args: Prisma.SelectSubset<T, FeedbackItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeedbackItems and returns the data updated in the database.
   * @param {FeedbackItemUpdateManyAndReturnArgs} args - Arguments to update many FeedbackItems.
   * @example
   * // Update many FeedbackItems
   * const feedbackItem = await prisma.feedbackItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FeedbackItems and only return the `id`
   * const feedbackItemWithIdOnly = await prisma.feedbackItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FeedbackItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FeedbackItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FeedbackItem.
   * @param {FeedbackItemUpsertArgs} args - Arguments to update or create a FeedbackItem.
   * @example
   * // Update or create a FeedbackItem
   * const feedbackItem = await prisma.feedbackItem.upsert({
   *   create: {
   *     // ... data to create a FeedbackItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FeedbackItem we want to update
   *   }
   * })
   */
  upsert<T extends FeedbackItemUpsertArgs>(args: Prisma.SelectSubset<T, FeedbackItemUpsertArgs<ExtArgs>>): Prisma.Prisma__FeedbackItemClient<runtime.Types.Result.GetResult<Prisma.$FeedbackItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FeedbackItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackItemCountArgs} args - Arguments to filter FeedbackItems to count.
   * @example
   * // Count the number of FeedbackItems
   * const count = await prisma.feedbackItem.count({
   *   where: {
   *     // ... the filter for the FeedbackItems we want to count
   *   }
   * })
  **/
  count<T extends FeedbackItemCountArgs>(
    args?: Prisma.Subset<T, FeedbackItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FeedbackItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FeedbackItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FeedbackItemAggregateArgs>(args: Prisma.Subset<T, FeedbackItemAggregateArgs>): Prisma.PrismaPromise<GetFeedbackItemAggregateType<T>>

  /**
   * Group by FeedbackItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeedbackItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FeedbackItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FeedbackItemGroupByArgs['orderBy'] }
      : { orderBy?: FeedbackItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FeedbackItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFeedbackItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FeedbackItem model
 */
readonly fields: FeedbackItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FeedbackItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FeedbackItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  satisfactionFeedback<T extends Prisma.FeedbackItem$satisfactionFeedbackArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FeedbackItem$satisfactionFeedbackArgs<ExtArgs>>): Prisma.Prisma__FeedbackClient<runtime.Types.Result.GetResult<Prisma.$FeedbackPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  improvementFeedback<T extends Prisma.FeedbackItem$improvementFeedbackArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FeedbackItem$improvementFeedbackArgs<ExtArgs>>): Prisma.Prisma__FeedbackClient<runtime.Types.Result.GetResult<Prisma.$FeedbackPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FeedbackItem model
 */
export interface FeedbackItemFieldRefs {
  readonly id: Prisma.FieldRef<"FeedbackItem", 'String'>
  readonly author: Prisma.FieldRef<"FeedbackItem", 'String'>
  readonly text: Prisma.FieldRef<"FeedbackItem", 'String'>
  readonly hotelDept: Prisma.FieldRef<"FeedbackItem", 'String'>
  readonly hotelName: Prisma.FieldRef<"FeedbackItem", 'String'>
  readonly hotelRegion: Prisma.FieldRef<"FeedbackItem", 'String'>
  readonly satisfactionFeedbackId: Prisma.FieldRef<"FeedbackItem", 'String'>
  readonly improvementFeedbackId: Prisma.FieldRef<"FeedbackItem", 'String'>
  readonly createdAt: Prisma.FieldRef<"FeedbackItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FeedbackItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FeedbackItem findUnique
 */
export type FeedbackItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
  /**
   * Filter, which FeedbackItem to fetch.
   */
  where: Prisma.FeedbackItemWhereUniqueInput
}

/**
 * FeedbackItem findUniqueOrThrow
 */
export type FeedbackItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
  /**
   * Filter, which FeedbackItem to fetch.
   */
  where: Prisma.FeedbackItemWhereUniqueInput
}

/**
 * FeedbackItem findFirst
 */
export type FeedbackItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
  /**
   * Filter, which FeedbackItem to fetch.
   */
  where?: Prisma.FeedbackItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedbackItems to fetch.
   */
  orderBy?: Prisma.FeedbackItemOrderByWithRelationInput | Prisma.FeedbackItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeedbackItems.
   */
  cursor?: Prisma.FeedbackItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedbackItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedbackItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeedbackItems.
   */
  distinct?: Prisma.FeedbackItemScalarFieldEnum | Prisma.FeedbackItemScalarFieldEnum[]
}

/**
 * FeedbackItem findFirstOrThrow
 */
export type FeedbackItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
  /**
   * Filter, which FeedbackItem to fetch.
   */
  where?: Prisma.FeedbackItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedbackItems to fetch.
   */
  orderBy?: Prisma.FeedbackItemOrderByWithRelationInput | Prisma.FeedbackItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeedbackItems.
   */
  cursor?: Prisma.FeedbackItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedbackItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedbackItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeedbackItems.
   */
  distinct?: Prisma.FeedbackItemScalarFieldEnum | Prisma.FeedbackItemScalarFieldEnum[]
}

/**
 * FeedbackItem findMany
 */
export type FeedbackItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
  /**
   * Filter, which FeedbackItems to fetch.
   */
  where?: Prisma.FeedbackItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeedbackItems to fetch.
   */
  orderBy?: Prisma.FeedbackItemOrderByWithRelationInput | Prisma.FeedbackItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FeedbackItems.
   */
  cursor?: Prisma.FeedbackItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeedbackItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeedbackItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeedbackItems.
   */
  distinct?: Prisma.FeedbackItemScalarFieldEnum | Prisma.FeedbackItemScalarFieldEnum[]
}

/**
 * FeedbackItem create
 */
export type FeedbackItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
  /**
   * The data needed to create a FeedbackItem.
   */
  data: Prisma.XOR<Prisma.FeedbackItemCreateInput, Prisma.FeedbackItemUncheckedCreateInput>
}

/**
 * FeedbackItem createMany
 */
export type FeedbackItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FeedbackItems.
   */
  data: Prisma.FeedbackItemCreateManyInput | Prisma.FeedbackItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FeedbackItem createManyAndReturn
 */
export type FeedbackItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * The data used to create many FeedbackItems.
   */
  data: Prisma.FeedbackItemCreateManyInput | Prisma.FeedbackItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FeedbackItem update
 */
export type FeedbackItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
  /**
   * The data needed to update a FeedbackItem.
   */
  data: Prisma.XOR<Prisma.FeedbackItemUpdateInput, Prisma.FeedbackItemUncheckedUpdateInput>
  /**
   * Choose, which FeedbackItem to update.
   */
  where: Prisma.FeedbackItemWhereUniqueInput
}

/**
 * FeedbackItem updateMany
 */
export type FeedbackItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FeedbackItems.
   */
  data: Prisma.XOR<Prisma.FeedbackItemUpdateManyMutationInput, Prisma.FeedbackItemUncheckedUpdateManyInput>
  /**
   * Filter which FeedbackItems to update
   */
  where?: Prisma.FeedbackItemWhereInput
  /**
   * Limit how many FeedbackItems to update.
   */
  limit?: number
}

/**
 * FeedbackItem updateManyAndReturn
 */
export type FeedbackItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * The data used to update FeedbackItems.
   */
  data: Prisma.XOR<Prisma.FeedbackItemUpdateManyMutationInput, Prisma.FeedbackItemUncheckedUpdateManyInput>
  /**
   * Filter which FeedbackItems to update
   */
  where?: Prisma.FeedbackItemWhereInput
  /**
   * Limit how many FeedbackItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FeedbackItem upsert
 */
export type FeedbackItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
  /**
   * The filter to search for the FeedbackItem to update in case it exists.
   */
  where: Prisma.FeedbackItemWhereUniqueInput
  /**
   * In case the FeedbackItem found by the `where` argument doesn't exist, create a new FeedbackItem with this data.
   */
  create: Prisma.XOR<Prisma.FeedbackItemCreateInput, Prisma.FeedbackItemUncheckedCreateInput>
  /**
   * In case the FeedbackItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FeedbackItemUpdateInput, Prisma.FeedbackItemUncheckedUpdateInput>
}

/**
 * FeedbackItem delete
 */
export type FeedbackItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
  /**
   * Filter which FeedbackItem to delete.
   */
  where: Prisma.FeedbackItemWhereUniqueInput
}

/**
 * FeedbackItem deleteMany
 */
export type FeedbackItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeedbackItems to delete
   */
  where?: Prisma.FeedbackItemWhereInput
  /**
   * Limit how many FeedbackItems to delete.
   */
  limit?: number
}

/**
 * FeedbackItem.satisfactionFeedback
 */
export type FeedbackItem$satisfactionFeedbackArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Feedback
   */
  select?: Prisma.FeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Feedback
   */
  omit?: Prisma.FeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackInclude<ExtArgs> | null
  where?: Prisma.FeedbackWhereInput
}

/**
 * FeedbackItem.improvementFeedback
 */
export type FeedbackItem$improvementFeedbackArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Feedback
   */
  select?: Prisma.FeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Feedback
   */
  omit?: Prisma.FeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackInclude<ExtArgs> | null
  where?: Prisma.FeedbackWhereInput
}

/**
 * FeedbackItem without action
 */
export type FeedbackItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeedbackItem
   */
  select?: Prisma.FeedbackItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeedbackItem
   */
  omit?: Prisma.FeedbackItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackItemInclude<ExtArgs> | null
}
