
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GuestUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GuestUser
 * 
 */
export type GuestUserModel = runtime.Types.Result.DefaultSelection<Prisma.$GuestUserPayload>

export type AggregateGuestUser = {
  _count: GuestUserCountAggregateOutputType | null
  _avg: GuestUserAvgAggregateOutputType | null
  _sum: GuestUserSumAggregateOutputType | null
  _min: GuestUserMinAggregateOutputType | null
  _max: GuestUserMaxAggregateOutputType | null
}

export type GuestUserAvgAggregateOutputType = {
  lastTimeConnected: number | null
}

export type GuestUserSumAggregateOutputType = {
  lastTimeConnected: bigint | null
}

export type GuestUserMinAggregateOutputType = {
  id: string | null
  username: string | null
  email: string | null
  password: string | null
  phone: string | null
  gender: string | null
  photo: string | null
  language: string | null
  localLanguage: string | null
  room: string | null
  hotelId: string | null
  journeyId: string | null
  guestCategory: string | null
  guestCategoryClone: string | null
  checkoutDate: string | null
  notificationStatus: string | null
  lastTimeConnected: bigint | null
  newConnection: boolean | null
  isChatting: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GuestUserMaxAggregateOutputType = {
  id: string | null
  username: string | null
  email: string | null
  password: string | null
  phone: string | null
  gender: string | null
  photo: string | null
  language: string | null
  localLanguage: string | null
  room: string | null
  hotelId: string | null
  journeyId: string | null
  guestCategory: string | null
  guestCategoryClone: string | null
  checkoutDate: string | null
  notificationStatus: string | null
  lastTimeConnected: bigint | null
  newConnection: boolean | null
  isChatting: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GuestUserCountAggregateOutputType = {
  id: number
  username: number
  email: number
  password: number
  phone: number
  gender: number
  photo: number
  language: number
  localLanguage: number
  room: number
  hotelId: number
  journeyId: number
  guestCategory: number
  guestCategoryClone: number
  checkoutDate: number
  notificationStatus: number
  lastTimeConnected: number
  newConnection: number
  isChatting: number
  createdAt: number
  updatedAt: number
  hotelVisitedArray: number
  _all: number
}


export type GuestUserAvgAggregateInputType = {
  lastTimeConnected?: true
}

export type GuestUserSumAggregateInputType = {
  lastTimeConnected?: true
}

export type GuestUserMinAggregateInputType = {
  id?: true
  username?: true
  email?: true
  password?: true
  phone?: true
  gender?: true
  photo?: true
  language?: true
  localLanguage?: true
  room?: true
  hotelId?: true
  journeyId?: true
  guestCategory?: true
  guestCategoryClone?: true
  checkoutDate?: true
  notificationStatus?: true
  lastTimeConnected?: true
  newConnection?: true
  isChatting?: true
  createdAt?: true
  updatedAt?: true
}

export type GuestUserMaxAggregateInputType = {
  id?: true
  username?: true
  email?: true
  password?: true
  phone?: true
  gender?: true
  photo?: true
  language?: true
  localLanguage?: true
  room?: true
  hotelId?: true
  journeyId?: true
  guestCategory?: true
  guestCategoryClone?: true
  checkoutDate?: true
  notificationStatus?: true
  lastTimeConnected?: true
  newConnection?: true
  isChatting?: true
  createdAt?: true
  updatedAt?: true
}

export type GuestUserCountAggregateInputType = {
  id?: true
  username?: true
  email?: true
  password?: true
  phone?: true
  gender?: true
  photo?: true
  language?: true
  localLanguage?: true
  room?: true
  hotelId?: true
  journeyId?: true
  guestCategory?: true
  guestCategoryClone?: true
  checkoutDate?: true
  notificationStatus?: true
  lastTimeConnected?: true
  newConnection?: true
  isChatting?: true
  createdAt?: true
  updatedAt?: true
  hotelVisitedArray?: true
  _all?: true
}

export type GuestUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuestUser to aggregate.
   */
  where?: Prisma.GuestUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuestUsers to fetch.
   */
  orderBy?: Prisma.GuestUserOrderByWithRelationInput | Prisma.GuestUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GuestUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuestUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuestUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GuestUsers
  **/
  _count?: true | GuestUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GuestUserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GuestUserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GuestUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GuestUserMaxAggregateInputType
}

export type GetGuestUserAggregateType<T extends GuestUserAggregateArgs> = {
      [P in keyof T & keyof AggregateGuestUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGuestUser[P]>
    : Prisma.GetScalarType<T[P], AggregateGuestUser[P]>
}




export type GuestUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GuestUserWhereInput
  orderBy?: Prisma.GuestUserOrderByWithAggregationInput | Prisma.GuestUserOrderByWithAggregationInput[]
  by: Prisma.GuestUserScalarFieldEnum[] | Prisma.GuestUserScalarFieldEnum
  having?: Prisma.GuestUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GuestUserCountAggregateInputType | true
  _avg?: GuestUserAvgAggregateInputType
  _sum?: GuestUserSumAggregateInputType
  _min?: GuestUserMinAggregateInputType
  _max?: GuestUserMaxAggregateInputType
}

export type GuestUserGroupByOutputType = {
  id: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo: string | null
  language: string
  localLanguage: string
  room: string
  hotelId: string
  journeyId: string
  guestCategory: string
  guestCategoryClone: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint
  newConnection: boolean
  isChatting: boolean | null
  createdAt: Date
  updatedAt: Date
  hotelVisitedArray: string[]
  _count: GuestUserCountAggregateOutputType | null
  _avg: GuestUserAvgAggregateOutputType | null
  _sum: GuestUserSumAggregateOutputType | null
  _min: GuestUserMinAggregateOutputType | null
  _max: GuestUserMaxAggregateOutputType | null
}

export type GetGuestUserGroupByPayload<T extends GuestUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GuestUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GuestUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GuestUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GuestUserGroupByOutputType[P]>
      }
    >
  >



export type GuestUserWhereInput = {
  AND?: Prisma.GuestUserWhereInput | Prisma.GuestUserWhereInput[]
  OR?: Prisma.GuestUserWhereInput[]
  NOT?: Prisma.GuestUserWhereInput | Prisma.GuestUserWhereInput[]
  id?: Prisma.StringFilter<"GuestUser"> | string
  username?: Prisma.StringFilter<"GuestUser"> | string
  email?: Prisma.StringFilter<"GuestUser"> | string
  password?: Prisma.StringFilter<"GuestUser"> | string
  phone?: Prisma.StringFilter<"GuestUser"> | string
  gender?: Prisma.StringFilter<"GuestUser"> | string
  photo?: Prisma.StringNullableFilter<"GuestUser"> | string | null
  language?: Prisma.StringFilter<"GuestUser"> | string
  localLanguage?: Prisma.StringFilter<"GuestUser"> | string
  room?: Prisma.StringFilter<"GuestUser"> | string
  hotelId?: Prisma.StringFilter<"GuestUser"> | string
  journeyId?: Prisma.StringFilter<"GuestUser"> | string
  guestCategory?: Prisma.StringFilter<"GuestUser"> | string
  guestCategoryClone?: Prisma.StringNullableFilter<"GuestUser"> | string | null
  checkoutDate?: Prisma.StringFilter<"GuestUser"> | string
  notificationStatus?: Prisma.StringFilter<"GuestUser"> | string
  lastTimeConnected?: Prisma.BigIntFilter<"GuestUser"> | bigint | number
  newConnection?: Prisma.BoolFilter<"GuestUser"> | boolean
  isChatting?: Prisma.BoolNullableFilter<"GuestUser"> | boolean | null
  createdAt?: Prisma.DateTimeFilter<"GuestUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GuestUser"> | Date | string
  hotelVisitedArray?: Prisma.StringNullableListFilter<"GuestUser">
  token?: Prisma.XOR<Prisma.GuestTokenNullableScalarRelationFilter, Prisma.GuestTokenWhereInput> | null
  roomAmeneties?: Prisma.RoomAmenetiesListRelationFilter
  hotel?: Prisma.XOR<Prisma.HotelScalarRelationFilter, Prisma.HotelWhereInput>
}

export type GuestUserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  photo?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrder
  localLanguage?: Prisma.SortOrder
  room?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  guestCategory?: Prisma.SortOrder
  guestCategoryClone?: Prisma.SortOrderInput | Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  notificationStatus?: Prisma.SortOrder
  lastTimeConnected?: Prisma.SortOrder
  newConnection?: Prisma.SortOrder
  isChatting?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  hotelVisitedArray?: Prisma.SortOrder
  token?: Prisma.GuestTokenOrderByWithRelationInput
  roomAmeneties?: Prisma.RoomAmenetiesOrderByRelationAggregateInput
  hotel?: Prisma.HotelOrderByWithRelationInput
}

export type GuestUserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GuestUserWhereInput | Prisma.GuestUserWhereInput[]
  OR?: Prisma.GuestUserWhereInput[]
  NOT?: Prisma.GuestUserWhereInput | Prisma.GuestUserWhereInput[]
  username?: Prisma.StringFilter<"GuestUser"> | string
  email?: Prisma.StringFilter<"GuestUser"> | string
  password?: Prisma.StringFilter<"GuestUser"> | string
  phone?: Prisma.StringFilter<"GuestUser"> | string
  gender?: Prisma.StringFilter<"GuestUser"> | string
  photo?: Prisma.StringNullableFilter<"GuestUser"> | string | null
  language?: Prisma.StringFilter<"GuestUser"> | string
  localLanguage?: Prisma.StringFilter<"GuestUser"> | string
  room?: Prisma.StringFilter<"GuestUser"> | string
  hotelId?: Prisma.StringFilter<"GuestUser"> | string
  journeyId?: Prisma.StringFilter<"GuestUser"> | string
  guestCategory?: Prisma.StringFilter<"GuestUser"> | string
  guestCategoryClone?: Prisma.StringNullableFilter<"GuestUser"> | string | null
  checkoutDate?: Prisma.StringFilter<"GuestUser"> | string
  notificationStatus?: Prisma.StringFilter<"GuestUser"> | string
  lastTimeConnected?: Prisma.BigIntFilter<"GuestUser"> | bigint | number
  newConnection?: Prisma.BoolFilter<"GuestUser"> | boolean
  isChatting?: Prisma.BoolNullableFilter<"GuestUser"> | boolean | null
  createdAt?: Prisma.DateTimeFilter<"GuestUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GuestUser"> | Date | string
  hotelVisitedArray?: Prisma.StringNullableListFilter<"GuestUser">
  token?: Prisma.XOR<Prisma.GuestTokenNullableScalarRelationFilter, Prisma.GuestTokenWhereInput> | null
  roomAmeneties?: Prisma.RoomAmenetiesListRelationFilter
  hotel?: Prisma.XOR<Prisma.HotelScalarRelationFilter, Prisma.HotelWhereInput>
}, "id">

export type GuestUserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  photo?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrder
  localLanguage?: Prisma.SortOrder
  room?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  guestCategory?: Prisma.SortOrder
  guestCategoryClone?: Prisma.SortOrderInput | Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  notificationStatus?: Prisma.SortOrder
  lastTimeConnected?: Prisma.SortOrder
  newConnection?: Prisma.SortOrder
  isChatting?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  hotelVisitedArray?: Prisma.SortOrder
  _count?: Prisma.GuestUserCountOrderByAggregateInput
  _avg?: Prisma.GuestUserAvgOrderByAggregateInput
  _max?: Prisma.GuestUserMaxOrderByAggregateInput
  _min?: Prisma.GuestUserMinOrderByAggregateInput
  _sum?: Prisma.GuestUserSumOrderByAggregateInput
}

export type GuestUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.GuestUserScalarWhereWithAggregatesInput | Prisma.GuestUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.GuestUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GuestUserScalarWhereWithAggregatesInput | Prisma.GuestUserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  username?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  email?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  password?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  phone?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  gender?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  photo?: Prisma.StringNullableWithAggregatesFilter<"GuestUser"> | string | null
  language?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  localLanguage?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  room?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  hotelId?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  journeyId?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  guestCategory?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  guestCategoryClone?: Prisma.StringNullableWithAggregatesFilter<"GuestUser"> | string | null
  checkoutDate?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  notificationStatus?: Prisma.StringWithAggregatesFilter<"GuestUser"> | string
  lastTimeConnected?: Prisma.BigIntWithAggregatesFilter<"GuestUser"> | bigint | number
  newConnection?: Prisma.BoolWithAggregatesFilter<"GuestUser"> | boolean
  isChatting?: Prisma.BoolNullableWithAggregatesFilter<"GuestUser"> | boolean | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GuestUser"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GuestUser"> | Date | string
  hotelVisitedArray?: Prisma.StringNullableListFilter<"GuestUser">
}

export type GuestUserCreateInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenCreateNestedOneWithoutGuestUserInput
  roomAmeneties?: Prisma.RoomAmenetiesCreateNestedManyWithoutGuestUserInput
  hotel: Prisma.HotelCreateNestedOneWithoutGuestUsersInput
}

export type GuestUserUncheckedCreateInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  hotelId: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenUncheckedCreateNestedOneWithoutGuestUserInput
  roomAmeneties?: Prisma.RoomAmenetiesUncheckedCreateNestedManyWithoutGuestUserInput
}

export type GuestUserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenUpdateOneWithoutGuestUserNestedInput
  roomAmeneties?: Prisma.RoomAmenetiesUpdateManyWithoutGuestUserNestedInput
  hotel?: Prisma.HotelUpdateOneRequiredWithoutGuestUsersNestedInput
}

export type GuestUserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenUncheckedUpdateOneWithoutGuestUserNestedInput
  roomAmeneties?: Prisma.RoomAmenetiesUncheckedUpdateManyWithoutGuestUserNestedInput
}

export type GuestUserCreateManyInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  hotelId: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
}

export type GuestUserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
}

export type GuestUserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
}

export type GuestUserListRelationFilter = {
  every?: Prisma.GuestUserWhereInput
  some?: Prisma.GuestUserWhereInput
  none?: Prisma.GuestUserWhereInput
}

export type GuestUserOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type GuestUserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  photo?: Prisma.SortOrder
  language?: Prisma.SortOrder
  localLanguage?: Prisma.SortOrder
  room?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  guestCategory?: Prisma.SortOrder
  guestCategoryClone?: Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  notificationStatus?: Prisma.SortOrder
  lastTimeConnected?: Prisma.SortOrder
  newConnection?: Prisma.SortOrder
  isChatting?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  hotelVisitedArray?: Prisma.SortOrder
}

export type GuestUserAvgOrderByAggregateInput = {
  lastTimeConnected?: Prisma.SortOrder
}

export type GuestUserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  photo?: Prisma.SortOrder
  language?: Prisma.SortOrder
  localLanguage?: Prisma.SortOrder
  room?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  guestCategory?: Prisma.SortOrder
  guestCategoryClone?: Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  notificationStatus?: Prisma.SortOrder
  lastTimeConnected?: Prisma.SortOrder
  newConnection?: Prisma.SortOrder
  isChatting?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GuestUserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  photo?: Prisma.SortOrder
  language?: Prisma.SortOrder
  localLanguage?: Prisma.SortOrder
  room?: Prisma.SortOrder
  hotelId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  guestCategory?: Prisma.SortOrder
  guestCategoryClone?: Prisma.SortOrder
  checkoutDate?: Prisma.SortOrder
  notificationStatus?: Prisma.SortOrder
  lastTimeConnected?: Prisma.SortOrder
  newConnection?: Prisma.SortOrder
  isChatting?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GuestUserSumOrderByAggregateInput = {
  lastTimeConnected?: Prisma.SortOrder
}

export type GuestUserNullableScalarRelationFilter = {
  is?: Prisma.GuestUserWhereInput | null
  isNot?: Prisma.GuestUserWhereInput | null
}

export type GuestUserScalarRelationFilter = {
  is?: Prisma.GuestUserWhereInput
  isNot?: Prisma.GuestUserWhereInput
}

export type GuestUserCreateNestedManyWithoutHotelInput = {
  create?: Prisma.XOR<Prisma.GuestUserCreateWithoutHotelInput, Prisma.GuestUserUncheckedCreateWithoutHotelInput> | Prisma.GuestUserCreateWithoutHotelInput[] | Prisma.GuestUserUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.GuestUserCreateOrConnectWithoutHotelInput | Prisma.GuestUserCreateOrConnectWithoutHotelInput[]
  createMany?: Prisma.GuestUserCreateManyHotelInputEnvelope
  connect?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
}

export type GuestUserUncheckedCreateNestedManyWithoutHotelInput = {
  create?: Prisma.XOR<Prisma.GuestUserCreateWithoutHotelInput, Prisma.GuestUserUncheckedCreateWithoutHotelInput> | Prisma.GuestUserCreateWithoutHotelInput[] | Prisma.GuestUserUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.GuestUserCreateOrConnectWithoutHotelInput | Prisma.GuestUserCreateOrConnectWithoutHotelInput[]
  createMany?: Prisma.GuestUserCreateManyHotelInputEnvelope
  connect?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
}

export type GuestUserUpdateManyWithoutHotelNestedInput = {
  create?: Prisma.XOR<Prisma.GuestUserCreateWithoutHotelInput, Prisma.GuestUserUncheckedCreateWithoutHotelInput> | Prisma.GuestUserCreateWithoutHotelInput[] | Prisma.GuestUserUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.GuestUserCreateOrConnectWithoutHotelInput | Prisma.GuestUserCreateOrConnectWithoutHotelInput[]
  upsert?: Prisma.GuestUserUpsertWithWhereUniqueWithoutHotelInput | Prisma.GuestUserUpsertWithWhereUniqueWithoutHotelInput[]
  createMany?: Prisma.GuestUserCreateManyHotelInputEnvelope
  set?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
  disconnect?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
  delete?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
  connect?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
  update?: Prisma.GuestUserUpdateWithWhereUniqueWithoutHotelInput | Prisma.GuestUserUpdateWithWhereUniqueWithoutHotelInput[]
  updateMany?: Prisma.GuestUserUpdateManyWithWhereWithoutHotelInput | Prisma.GuestUserUpdateManyWithWhereWithoutHotelInput[]
  deleteMany?: Prisma.GuestUserScalarWhereInput | Prisma.GuestUserScalarWhereInput[]
}

export type GuestUserUncheckedUpdateManyWithoutHotelNestedInput = {
  create?: Prisma.XOR<Prisma.GuestUserCreateWithoutHotelInput, Prisma.GuestUserUncheckedCreateWithoutHotelInput> | Prisma.GuestUserCreateWithoutHotelInput[] | Prisma.GuestUserUncheckedCreateWithoutHotelInput[]
  connectOrCreate?: Prisma.GuestUserCreateOrConnectWithoutHotelInput | Prisma.GuestUserCreateOrConnectWithoutHotelInput[]
  upsert?: Prisma.GuestUserUpsertWithWhereUniqueWithoutHotelInput | Prisma.GuestUserUpsertWithWhereUniqueWithoutHotelInput[]
  createMany?: Prisma.GuestUserCreateManyHotelInputEnvelope
  set?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
  disconnect?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
  delete?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
  connect?: Prisma.GuestUserWhereUniqueInput | Prisma.GuestUserWhereUniqueInput[]
  update?: Prisma.GuestUserUpdateWithWhereUniqueWithoutHotelInput | Prisma.GuestUserUpdateWithWhereUniqueWithoutHotelInput[]
  updateMany?: Prisma.GuestUserUpdateManyWithWhereWithoutHotelInput | Prisma.GuestUserUpdateManyWithWhereWithoutHotelInput[]
  deleteMany?: Prisma.GuestUserScalarWhereInput | Prisma.GuestUserScalarWhereInput[]
}

export type GuestUserCreatehotelVisitedArrayInput = {
  set: string[]
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type GuestUserUpdatehotelVisitedArrayInput = {
  set?: string[]
  push?: string | string[]
}

export type GuestUserCreateNestedOneWithoutRoomAmenetiesInput = {
  create?: Prisma.XOR<Prisma.GuestUserCreateWithoutRoomAmenetiesInput, Prisma.GuestUserUncheckedCreateWithoutRoomAmenetiesInput>
  connectOrCreate?: Prisma.GuestUserCreateOrConnectWithoutRoomAmenetiesInput
  connect?: Prisma.GuestUserWhereUniqueInput
}

export type GuestUserUpdateOneWithoutRoomAmenetiesNestedInput = {
  create?: Prisma.XOR<Prisma.GuestUserCreateWithoutRoomAmenetiesInput, Prisma.GuestUserUncheckedCreateWithoutRoomAmenetiesInput>
  connectOrCreate?: Prisma.GuestUserCreateOrConnectWithoutRoomAmenetiesInput
  upsert?: Prisma.GuestUserUpsertWithoutRoomAmenetiesInput
  disconnect?: Prisma.GuestUserWhereInput | boolean
  delete?: Prisma.GuestUserWhereInput | boolean
  connect?: Prisma.GuestUserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GuestUserUpdateToOneWithWhereWithoutRoomAmenetiesInput, Prisma.GuestUserUpdateWithoutRoomAmenetiesInput>, Prisma.GuestUserUncheckedUpdateWithoutRoomAmenetiesInput>
}

export type GuestUserCreateNestedOneWithoutTokenInput = {
  create?: Prisma.XOR<Prisma.GuestUserCreateWithoutTokenInput, Prisma.GuestUserUncheckedCreateWithoutTokenInput>
  connectOrCreate?: Prisma.GuestUserCreateOrConnectWithoutTokenInput
  connect?: Prisma.GuestUserWhereUniqueInput
}

export type GuestUserUpdateOneRequiredWithoutTokenNestedInput = {
  create?: Prisma.XOR<Prisma.GuestUserCreateWithoutTokenInput, Prisma.GuestUserUncheckedCreateWithoutTokenInput>
  connectOrCreate?: Prisma.GuestUserCreateOrConnectWithoutTokenInput
  upsert?: Prisma.GuestUserUpsertWithoutTokenInput
  connect?: Prisma.GuestUserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GuestUserUpdateToOneWithWhereWithoutTokenInput, Prisma.GuestUserUpdateWithoutTokenInput>, Prisma.GuestUserUncheckedUpdateWithoutTokenInput>
}

export type GuestUserCreateWithoutHotelInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenCreateNestedOneWithoutGuestUserInput
  roomAmeneties?: Prisma.RoomAmenetiesCreateNestedManyWithoutGuestUserInput
}

export type GuestUserUncheckedCreateWithoutHotelInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenUncheckedCreateNestedOneWithoutGuestUserInput
  roomAmeneties?: Prisma.RoomAmenetiesUncheckedCreateNestedManyWithoutGuestUserInput
}

export type GuestUserCreateOrConnectWithoutHotelInput = {
  where: Prisma.GuestUserWhereUniqueInput
  create: Prisma.XOR<Prisma.GuestUserCreateWithoutHotelInput, Prisma.GuestUserUncheckedCreateWithoutHotelInput>
}

export type GuestUserCreateManyHotelInputEnvelope = {
  data: Prisma.GuestUserCreateManyHotelInput | Prisma.GuestUserCreateManyHotelInput[]
  skipDuplicates?: boolean
}

export type GuestUserUpsertWithWhereUniqueWithoutHotelInput = {
  where: Prisma.GuestUserWhereUniqueInput
  update: Prisma.XOR<Prisma.GuestUserUpdateWithoutHotelInput, Prisma.GuestUserUncheckedUpdateWithoutHotelInput>
  create: Prisma.XOR<Prisma.GuestUserCreateWithoutHotelInput, Prisma.GuestUserUncheckedCreateWithoutHotelInput>
}

export type GuestUserUpdateWithWhereUniqueWithoutHotelInput = {
  where: Prisma.GuestUserWhereUniqueInput
  data: Prisma.XOR<Prisma.GuestUserUpdateWithoutHotelInput, Prisma.GuestUserUncheckedUpdateWithoutHotelInput>
}

export type GuestUserUpdateManyWithWhereWithoutHotelInput = {
  where: Prisma.GuestUserScalarWhereInput
  data: Prisma.XOR<Prisma.GuestUserUpdateManyMutationInput, Prisma.GuestUserUncheckedUpdateManyWithoutHotelInput>
}

export type GuestUserScalarWhereInput = {
  AND?: Prisma.GuestUserScalarWhereInput | Prisma.GuestUserScalarWhereInput[]
  OR?: Prisma.GuestUserScalarWhereInput[]
  NOT?: Prisma.GuestUserScalarWhereInput | Prisma.GuestUserScalarWhereInput[]
  id?: Prisma.StringFilter<"GuestUser"> | string
  username?: Prisma.StringFilter<"GuestUser"> | string
  email?: Prisma.StringFilter<"GuestUser"> | string
  password?: Prisma.StringFilter<"GuestUser"> | string
  phone?: Prisma.StringFilter<"GuestUser"> | string
  gender?: Prisma.StringFilter<"GuestUser"> | string
  photo?: Prisma.StringNullableFilter<"GuestUser"> | string | null
  language?: Prisma.StringFilter<"GuestUser"> | string
  localLanguage?: Prisma.StringFilter<"GuestUser"> | string
  room?: Prisma.StringFilter<"GuestUser"> | string
  hotelId?: Prisma.StringFilter<"GuestUser"> | string
  journeyId?: Prisma.StringFilter<"GuestUser"> | string
  guestCategory?: Prisma.StringFilter<"GuestUser"> | string
  guestCategoryClone?: Prisma.StringNullableFilter<"GuestUser"> | string | null
  checkoutDate?: Prisma.StringFilter<"GuestUser"> | string
  notificationStatus?: Prisma.StringFilter<"GuestUser"> | string
  lastTimeConnected?: Prisma.BigIntFilter<"GuestUser"> | bigint | number
  newConnection?: Prisma.BoolFilter<"GuestUser"> | boolean
  isChatting?: Prisma.BoolNullableFilter<"GuestUser"> | boolean | null
  createdAt?: Prisma.DateTimeFilter<"GuestUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GuestUser"> | Date | string
  hotelVisitedArray?: Prisma.StringNullableListFilter<"GuestUser">
}

export type GuestUserCreateWithoutRoomAmenetiesInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenCreateNestedOneWithoutGuestUserInput
  hotel: Prisma.HotelCreateNestedOneWithoutGuestUsersInput
}

export type GuestUserUncheckedCreateWithoutRoomAmenetiesInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  hotelId: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenUncheckedCreateNestedOneWithoutGuestUserInput
}

export type GuestUserCreateOrConnectWithoutRoomAmenetiesInput = {
  where: Prisma.GuestUserWhereUniqueInput
  create: Prisma.XOR<Prisma.GuestUserCreateWithoutRoomAmenetiesInput, Prisma.GuestUserUncheckedCreateWithoutRoomAmenetiesInput>
}

export type GuestUserUpsertWithoutRoomAmenetiesInput = {
  update: Prisma.XOR<Prisma.GuestUserUpdateWithoutRoomAmenetiesInput, Prisma.GuestUserUncheckedUpdateWithoutRoomAmenetiesInput>
  create: Prisma.XOR<Prisma.GuestUserCreateWithoutRoomAmenetiesInput, Prisma.GuestUserUncheckedCreateWithoutRoomAmenetiesInput>
  where?: Prisma.GuestUserWhereInput
}

export type GuestUserUpdateToOneWithWhereWithoutRoomAmenetiesInput = {
  where?: Prisma.GuestUserWhereInput
  data: Prisma.XOR<Prisma.GuestUserUpdateWithoutRoomAmenetiesInput, Prisma.GuestUserUncheckedUpdateWithoutRoomAmenetiesInput>
}

export type GuestUserUpdateWithoutRoomAmenetiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenUpdateOneWithoutGuestUserNestedInput
  hotel?: Prisma.HotelUpdateOneRequiredWithoutGuestUsersNestedInput
}

export type GuestUserUncheckedUpdateWithoutRoomAmenetiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenUncheckedUpdateOneWithoutGuestUserNestedInput
}

export type GuestUserCreateWithoutTokenInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
  roomAmeneties?: Prisma.RoomAmenetiesCreateNestedManyWithoutGuestUserInput
  hotel: Prisma.HotelCreateNestedOneWithoutGuestUsersInput
}

export type GuestUserUncheckedCreateWithoutTokenInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  hotelId: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
  roomAmeneties?: Prisma.RoomAmenetiesUncheckedCreateNestedManyWithoutGuestUserInput
}

export type GuestUserCreateOrConnectWithoutTokenInput = {
  where: Prisma.GuestUserWhereUniqueInput
  create: Prisma.XOR<Prisma.GuestUserCreateWithoutTokenInput, Prisma.GuestUserUncheckedCreateWithoutTokenInput>
}

export type GuestUserUpsertWithoutTokenInput = {
  update: Prisma.XOR<Prisma.GuestUserUpdateWithoutTokenInput, Prisma.GuestUserUncheckedUpdateWithoutTokenInput>
  create: Prisma.XOR<Prisma.GuestUserCreateWithoutTokenInput, Prisma.GuestUserUncheckedCreateWithoutTokenInput>
  where?: Prisma.GuestUserWhereInput
}

export type GuestUserUpdateToOneWithWhereWithoutTokenInput = {
  where?: Prisma.GuestUserWhereInput
  data: Prisma.XOR<Prisma.GuestUserUpdateWithoutTokenInput, Prisma.GuestUserUncheckedUpdateWithoutTokenInput>
}

export type GuestUserUpdateWithoutTokenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
  roomAmeneties?: Prisma.RoomAmenetiesUpdateManyWithoutGuestUserNestedInput
  hotel?: Prisma.HotelUpdateOneRequiredWithoutGuestUsersNestedInput
}

export type GuestUserUncheckedUpdateWithoutTokenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  hotelId?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
  roomAmeneties?: Prisma.RoomAmenetiesUncheckedUpdateManyWithoutGuestUserNestedInput
}

export type GuestUserCreateManyHotelInput = {
  id?: string
  username: string
  email: string
  password: string
  phone: string
  gender: string
  photo?: string | null
  language: string
  localLanguage: string
  room: string
  journeyId: string
  guestCategory: string
  guestCategoryClone?: string | null
  checkoutDate: string
  notificationStatus: string
  lastTimeConnected: bigint | number
  newConnection: boolean
  isChatting?: boolean | null
  createdAt: Date | string
  updatedAt: Date | string
  hotelVisitedArray?: Prisma.GuestUserCreatehotelVisitedArrayInput | string[]
}

export type GuestUserUpdateWithoutHotelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenUpdateOneWithoutGuestUserNestedInput
  roomAmeneties?: Prisma.RoomAmenetiesUpdateManyWithoutGuestUserNestedInput
}

export type GuestUserUncheckedUpdateWithoutHotelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
  token?: Prisma.GuestTokenUncheckedUpdateOneWithoutGuestUserNestedInput
  roomAmeneties?: Prisma.RoomAmenetiesUncheckedUpdateManyWithoutGuestUserNestedInput
}

export type GuestUserUncheckedUpdateManyWithoutHotelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  photo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  localLanguage?: Prisma.StringFieldUpdateOperationsInput | string
  room?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategory?: Prisma.StringFieldUpdateOperationsInput | string
  guestCategoryClone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkoutDate?: Prisma.StringFieldUpdateOperationsInput | string
  notificationStatus?: Prisma.StringFieldUpdateOperationsInput | string
  lastTimeConnected?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  newConnection?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChatting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hotelVisitedArray?: Prisma.GuestUserUpdatehotelVisitedArrayInput | string[]
}


/**
 * Count Type GuestUserCountOutputType
 */

export type GuestUserCountOutputType = {
  roomAmeneties: number
}

export type GuestUserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roomAmeneties?: boolean | GuestUserCountOutputTypeCountRoomAmenetiesArgs
}

/**
 * GuestUserCountOutputType without action
 */
export type GuestUserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUserCountOutputType
   */
  select?: Prisma.GuestUserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * GuestUserCountOutputType without action
 */
export type GuestUserCountOutputTypeCountRoomAmenetiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RoomAmenetiesWhereInput
}


export type GuestUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  email?: boolean
  password?: boolean
  phone?: boolean
  gender?: boolean
  photo?: boolean
  language?: boolean
  localLanguage?: boolean
  room?: boolean
  hotelId?: boolean
  journeyId?: boolean
  guestCategory?: boolean
  guestCategoryClone?: boolean
  checkoutDate?: boolean
  notificationStatus?: boolean
  lastTimeConnected?: boolean
  newConnection?: boolean
  isChatting?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hotelVisitedArray?: boolean
  token?: boolean | Prisma.GuestUser$tokenArgs<ExtArgs>
  roomAmeneties?: boolean | Prisma.GuestUser$roomAmenetiesArgs<ExtArgs>
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.GuestUserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guestUser"]>

export type GuestUserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  email?: boolean
  password?: boolean
  phone?: boolean
  gender?: boolean
  photo?: boolean
  language?: boolean
  localLanguage?: boolean
  room?: boolean
  hotelId?: boolean
  journeyId?: boolean
  guestCategory?: boolean
  guestCategoryClone?: boolean
  checkoutDate?: boolean
  notificationStatus?: boolean
  lastTimeConnected?: boolean
  newConnection?: boolean
  isChatting?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hotelVisitedArray?: boolean
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guestUser"]>

export type GuestUserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  email?: boolean
  password?: boolean
  phone?: boolean
  gender?: boolean
  photo?: boolean
  language?: boolean
  localLanguage?: boolean
  room?: boolean
  hotelId?: boolean
  journeyId?: boolean
  guestCategory?: boolean
  guestCategoryClone?: boolean
  checkoutDate?: boolean
  notificationStatus?: boolean
  lastTimeConnected?: boolean
  newConnection?: boolean
  isChatting?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hotelVisitedArray?: boolean
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guestUser"]>

export type GuestUserSelectScalar = {
  id?: boolean
  username?: boolean
  email?: boolean
  password?: boolean
  phone?: boolean
  gender?: boolean
  photo?: boolean
  language?: boolean
  localLanguage?: boolean
  room?: boolean
  hotelId?: boolean
  journeyId?: boolean
  guestCategory?: boolean
  guestCategoryClone?: boolean
  checkoutDate?: boolean
  notificationStatus?: boolean
  lastTimeConnected?: boolean
  newConnection?: boolean
  isChatting?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hotelVisitedArray?: boolean
}

export type GuestUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "username" | "email" | "password" | "phone" | "gender" | "photo" | "language" | "localLanguage" | "room" | "hotelId" | "journeyId" | "guestCategory" | "guestCategoryClone" | "checkoutDate" | "notificationStatus" | "lastTimeConnected" | "newConnection" | "isChatting" | "createdAt" | "updatedAt" | "hotelVisitedArray", ExtArgs["result"]["guestUser"]>
export type GuestUserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  token?: boolean | Prisma.GuestUser$tokenArgs<ExtArgs>
  roomAmeneties?: boolean | Prisma.GuestUser$roomAmenetiesArgs<ExtArgs>
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.GuestUserCountOutputTypeDefaultArgs<ExtArgs>
}
export type GuestUserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
}
export type GuestUserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hotel?: boolean | Prisma.HotelDefaultArgs<ExtArgs>
}

export type $GuestUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GuestUser"
  objects: {
    token: Prisma.$GuestTokenPayload<ExtArgs> | null
    roomAmeneties: Prisma.$RoomAmenetiesPayload<ExtArgs>[]
    hotel: Prisma.$HotelPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    username: string
    email: string
    password: string
    phone: string
    gender: string
    photo: string | null
    language: string
    localLanguage: string
    room: string
    hotelId: string
    journeyId: string
    guestCategory: string
    guestCategoryClone: string | null
    checkoutDate: string
    notificationStatus: string
    lastTimeConnected: bigint
    newConnection: boolean
    isChatting: boolean | null
    createdAt: Date
    updatedAt: Date
    hotelVisitedArray: string[]
  }, ExtArgs["result"]["guestUser"]>
  composites: {}
}

export type GuestUserGetPayload<S extends boolean | null | undefined | GuestUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GuestUserPayload, S>

export type GuestUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GuestUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GuestUserCountAggregateInputType | true
  }

export interface GuestUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GuestUser'], meta: { name: 'GuestUser' } }
  /**
   * Find zero or one GuestUser that matches the filter.
   * @param {GuestUserFindUniqueArgs} args - Arguments to find a GuestUser
   * @example
   * // Get one GuestUser
   * const guestUser = await prisma.guestUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GuestUserFindUniqueArgs>(args: Prisma.SelectSubset<T, GuestUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GuestUserClient<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GuestUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GuestUserFindUniqueOrThrowArgs} args - Arguments to find a GuestUser
   * @example
   * // Get one GuestUser
   * const guestUser = await prisma.guestUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GuestUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GuestUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuestUserClient<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuestUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestUserFindFirstArgs} args - Arguments to find a GuestUser
   * @example
   * // Get one GuestUser
   * const guestUser = await prisma.guestUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GuestUserFindFirstArgs>(args?: Prisma.SelectSubset<T, GuestUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__GuestUserClient<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuestUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestUserFindFirstOrThrowArgs} args - Arguments to find a GuestUser
   * @example
   * // Get one GuestUser
   * const guestUser = await prisma.guestUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GuestUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GuestUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuestUserClient<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GuestUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GuestUsers
   * const guestUsers = await prisma.guestUser.findMany()
   * 
   * // Get first 10 GuestUsers
   * const guestUsers = await prisma.guestUser.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const guestUserWithIdOnly = await prisma.guestUser.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GuestUserFindManyArgs>(args?: Prisma.SelectSubset<T, GuestUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GuestUser.
   * @param {GuestUserCreateArgs} args - Arguments to create a GuestUser.
   * @example
   * // Create one GuestUser
   * const GuestUser = await prisma.guestUser.create({
   *   data: {
   *     // ... data to create a GuestUser
   *   }
   * })
   * 
   */
  create<T extends GuestUserCreateArgs>(args: Prisma.SelectSubset<T, GuestUserCreateArgs<ExtArgs>>): Prisma.Prisma__GuestUserClient<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GuestUsers.
   * @param {GuestUserCreateManyArgs} args - Arguments to create many GuestUsers.
   * @example
   * // Create many GuestUsers
   * const guestUser = await prisma.guestUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GuestUserCreateManyArgs>(args?: Prisma.SelectSubset<T, GuestUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GuestUsers and returns the data saved in the database.
   * @param {GuestUserCreateManyAndReturnArgs} args - Arguments to create many GuestUsers.
   * @example
   * // Create many GuestUsers
   * const guestUser = await prisma.guestUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GuestUsers and only return the `id`
   * const guestUserWithIdOnly = await prisma.guestUser.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GuestUserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GuestUserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GuestUser.
   * @param {GuestUserDeleteArgs} args - Arguments to delete one GuestUser.
   * @example
   * // Delete one GuestUser
   * const GuestUser = await prisma.guestUser.delete({
   *   where: {
   *     // ... filter to delete one GuestUser
   *   }
   * })
   * 
   */
  delete<T extends GuestUserDeleteArgs>(args: Prisma.SelectSubset<T, GuestUserDeleteArgs<ExtArgs>>): Prisma.Prisma__GuestUserClient<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GuestUser.
   * @param {GuestUserUpdateArgs} args - Arguments to update one GuestUser.
   * @example
   * // Update one GuestUser
   * const guestUser = await prisma.guestUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GuestUserUpdateArgs>(args: Prisma.SelectSubset<T, GuestUserUpdateArgs<ExtArgs>>): Prisma.Prisma__GuestUserClient<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GuestUsers.
   * @param {GuestUserDeleteManyArgs} args - Arguments to filter GuestUsers to delete.
   * @example
   * // Delete a few GuestUsers
   * const { count } = await prisma.guestUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GuestUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, GuestUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GuestUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GuestUsers
   * const guestUser = await prisma.guestUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GuestUserUpdateManyArgs>(args: Prisma.SelectSubset<T, GuestUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GuestUsers and returns the data updated in the database.
   * @param {GuestUserUpdateManyAndReturnArgs} args - Arguments to update many GuestUsers.
   * @example
   * // Update many GuestUsers
   * const guestUser = await prisma.guestUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GuestUsers and only return the `id`
   * const guestUserWithIdOnly = await prisma.guestUser.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GuestUserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GuestUserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GuestUser.
   * @param {GuestUserUpsertArgs} args - Arguments to update or create a GuestUser.
   * @example
   * // Update or create a GuestUser
   * const guestUser = await prisma.guestUser.upsert({
   *   create: {
   *     // ... data to create a GuestUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GuestUser we want to update
   *   }
   * })
   */
  upsert<T extends GuestUserUpsertArgs>(args: Prisma.SelectSubset<T, GuestUserUpsertArgs<ExtArgs>>): Prisma.Prisma__GuestUserClient<runtime.Types.Result.GetResult<Prisma.$GuestUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GuestUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestUserCountArgs} args - Arguments to filter GuestUsers to count.
   * @example
   * // Count the number of GuestUsers
   * const count = await prisma.guestUser.count({
   *   where: {
   *     // ... the filter for the GuestUsers we want to count
   *   }
   * })
  **/
  count<T extends GuestUserCountArgs>(
    args?: Prisma.Subset<T, GuestUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GuestUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GuestUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GuestUserAggregateArgs>(args: Prisma.Subset<T, GuestUserAggregateArgs>): Prisma.PrismaPromise<GetGuestUserAggregateType<T>>

  /**
   * Group by GuestUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GuestUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GuestUserGroupByArgs['orderBy'] }
      : { orderBy?: GuestUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GuestUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGuestUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GuestUser model
 */
readonly fields: GuestUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GuestUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GuestUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  token<T extends Prisma.GuestUser$tokenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuestUser$tokenArgs<ExtArgs>>): Prisma.Prisma__GuestTokenClient<runtime.Types.Result.GetResult<Prisma.$GuestTokenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  roomAmeneties<T extends Prisma.GuestUser$roomAmenetiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuestUser$roomAmenetiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoomAmenetiesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  hotel<T extends Prisma.HotelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HotelDefaultArgs<ExtArgs>>): Prisma.Prisma__HotelClient<runtime.Types.Result.GetResult<Prisma.$HotelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GuestUser model
 */
export interface GuestUserFieldRefs {
  readonly id: Prisma.FieldRef<"GuestUser", 'String'>
  readonly username: Prisma.FieldRef<"GuestUser", 'String'>
  readonly email: Prisma.FieldRef<"GuestUser", 'String'>
  readonly password: Prisma.FieldRef<"GuestUser", 'String'>
  readonly phone: Prisma.FieldRef<"GuestUser", 'String'>
  readonly gender: Prisma.FieldRef<"GuestUser", 'String'>
  readonly photo: Prisma.FieldRef<"GuestUser", 'String'>
  readonly language: Prisma.FieldRef<"GuestUser", 'String'>
  readonly localLanguage: Prisma.FieldRef<"GuestUser", 'String'>
  readonly room: Prisma.FieldRef<"GuestUser", 'String'>
  readonly hotelId: Prisma.FieldRef<"GuestUser", 'String'>
  readonly journeyId: Prisma.FieldRef<"GuestUser", 'String'>
  readonly guestCategory: Prisma.FieldRef<"GuestUser", 'String'>
  readonly guestCategoryClone: Prisma.FieldRef<"GuestUser", 'String'>
  readonly checkoutDate: Prisma.FieldRef<"GuestUser", 'String'>
  readonly notificationStatus: Prisma.FieldRef<"GuestUser", 'String'>
  readonly lastTimeConnected: Prisma.FieldRef<"GuestUser", 'BigInt'>
  readonly newConnection: Prisma.FieldRef<"GuestUser", 'Boolean'>
  readonly isChatting: Prisma.FieldRef<"GuestUser", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"GuestUser", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GuestUser", 'DateTime'>
  readonly hotelVisitedArray: Prisma.FieldRef<"GuestUser", 'String[]'>
}
    

// Custom InputTypes
/**
 * GuestUser findUnique
 */
export type GuestUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
  /**
   * Filter, which GuestUser to fetch.
   */
  where: Prisma.GuestUserWhereUniqueInput
}

/**
 * GuestUser findUniqueOrThrow
 */
export type GuestUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
  /**
   * Filter, which GuestUser to fetch.
   */
  where: Prisma.GuestUserWhereUniqueInput
}

/**
 * GuestUser findFirst
 */
export type GuestUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
  /**
   * Filter, which GuestUser to fetch.
   */
  where?: Prisma.GuestUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuestUsers to fetch.
   */
  orderBy?: Prisma.GuestUserOrderByWithRelationInput | Prisma.GuestUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuestUsers.
   */
  cursor?: Prisma.GuestUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuestUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuestUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuestUsers.
   */
  distinct?: Prisma.GuestUserScalarFieldEnum | Prisma.GuestUserScalarFieldEnum[]
}

/**
 * GuestUser findFirstOrThrow
 */
export type GuestUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
  /**
   * Filter, which GuestUser to fetch.
   */
  where?: Prisma.GuestUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuestUsers to fetch.
   */
  orderBy?: Prisma.GuestUserOrderByWithRelationInput | Prisma.GuestUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuestUsers.
   */
  cursor?: Prisma.GuestUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuestUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuestUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuestUsers.
   */
  distinct?: Prisma.GuestUserScalarFieldEnum | Prisma.GuestUserScalarFieldEnum[]
}

/**
 * GuestUser findMany
 */
export type GuestUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
  /**
   * Filter, which GuestUsers to fetch.
   */
  where?: Prisma.GuestUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuestUsers to fetch.
   */
  orderBy?: Prisma.GuestUserOrderByWithRelationInput | Prisma.GuestUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GuestUsers.
   */
  cursor?: Prisma.GuestUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuestUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuestUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuestUsers.
   */
  distinct?: Prisma.GuestUserScalarFieldEnum | Prisma.GuestUserScalarFieldEnum[]
}

/**
 * GuestUser create
 */
export type GuestUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
  /**
   * The data needed to create a GuestUser.
   */
  data: Prisma.XOR<Prisma.GuestUserCreateInput, Prisma.GuestUserUncheckedCreateInput>
}

/**
 * GuestUser createMany
 */
export type GuestUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GuestUsers.
   */
  data: Prisma.GuestUserCreateManyInput | Prisma.GuestUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GuestUser createManyAndReturn
 */
export type GuestUserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * The data used to create many GuestUsers.
   */
  data: Prisma.GuestUserCreateManyInput | Prisma.GuestUserCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GuestUser update
 */
export type GuestUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
  /**
   * The data needed to update a GuestUser.
   */
  data: Prisma.XOR<Prisma.GuestUserUpdateInput, Prisma.GuestUserUncheckedUpdateInput>
  /**
   * Choose, which GuestUser to update.
   */
  where: Prisma.GuestUserWhereUniqueInput
}

/**
 * GuestUser updateMany
 */
export type GuestUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GuestUsers.
   */
  data: Prisma.XOR<Prisma.GuestUserUpdateManyMutationInput, Prisma.GuestUserUncheckedUpdateManyInput>
  /**
   * Filter which GuestUsers to update
   */
  where?: Prisma.GuestUserWhereInput
  /**
   * Limit how many GuestUsers to update.
   */
  limit?: number
}

/**
 * GuestUser updateManyAndReturn
 */
export type GuestUserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * The data used to update GuestUsers.
   */
  data: Prisma.XOR<Prisma.GuestUserUpdateManyMutationInput, Prisma.GuestUserUncheckedUpdateManyInput>
  /**
   * Filter which GuestUsers to update
   */
  where?: Prisma.GuestUserWhereInput
  /**
   * Limit how many GuestUsers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GuestUser upsert
 */
export type GuestUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
  /**
   * The filter to search for the GuestUser to update in case it exists.
   */
  where: Prisma.GuestUserWhereUniqueInput
  /**
   * In case the GuestUser found by the `where` argument doesn't exist, create a new GuestUser with this data.
   */
  create: Prisma.XOR<Prisma.GuestUserCreateInput, Prisma.GuestUserUncheckedCreateInput>
  /**
   * In case the GuestUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GuestUserUpdateInput, Prisma.GuestUserUncheckedUpdateInput>
}

/**
 * GuestUser delete
 */
export type GuestUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
  /**
   * Filter which GuestUser to delete.
   */
  where: Prisma.GuestUserWhereUniqueInput
}

/**
 * GuestUser deleteMany
 */
export type GuestUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuestUsers to delete
   */
  where?: Prisma.GuestUserWhereInput
  /**
   * Limit how many GuestUsers to delete.
   */
  limit?: number
}

/**
 * GuestUser.token
 */
export type GuestUser$tokenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestToken
   */
  select?: Prisma.GuestTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestToken
   */
  omit?: Prisma.GuestTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestTokenInclude<ExtArgs> | null
  where?: Prisma.GuestTokenWhereInput
}

/**
 * GuestUser.roomAmeneties
 */
export type GuestUser$roomAmenetiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoomAmeneties
   */
  select?: Prisma.RoomAmenetiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoomAmeneties
   */
  omit?: Prisma.RoomAmenetiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoomAmenetiesInclude<ExtArgs> | null
  where?: Prisma.RoomAmenetiesWhereInput
  orderBy?: Prisma.RoomAmenetiesOrderByWithRelationInput | Prisma.RoomAmenetiesOrderByWithRelationInput[]
  cursor?: Prisma.RoomAmenetiesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RoomAmenetiesScalarFieldEnum | Prisma.RoomAmenetiesScalarFieldEnum[]
}

/**
 * GuestUser without action
 */
export type GuestUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuestUser
   */
  select?: Prisma.GuestUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuestUser
   */
  omit?: Prisma.GuestUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestUserInclude<ExtArgs> | null
}
